### ISSUE TITLE
cmd/upspin-deploy: add script for wiping Store and Dir quickly

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#108]
We could upspin-deploy -delete and then -create again. But it's fast and easy to just do the following:

`gsutil -m rm gs://<project>-store/** `
(wipes the store)

and to wipe the dir, we need to be able to SSH into the machine hosting the dirserver PD, cd into the dirserver mount point and then rm -rf * or at least rm -f *.

The second part is a little tricky because ssh doesn't work by default after upspin-deploy -create (it seems like it should, but I just tried it with Rob and we had to add a new ssh rule to make it possible). So, maybe upspin-deploy -create needs to create the SSH firewall rule too. Connecting to the instance via ssh can be done via gsutil as well. Then from there we can do something like 

```
sudo cd `mount |grep dirserver | head -1`; sudo rm -f *
```

and kick the store and dir servers, possibly via `kubectl delete pod <dir/store>`

**Comment by adg** [comment]
It must be made very hard to do this by mistake.

**Comment by robpike** [comment]
New docs cover how to do this and I think are all we need.
