### ISSUE TITLE
cmd/upspin-deploy: both instances of DirServer have log=debug on

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#109]
Because we don't have a way of differentiating the log level based on the project ID. This might be too verbose for prod, especially given the new 5GB/month limit.

But we could simply add another placeholder variable called LOGLEVEL and set it in the Docker file (log=LOGLEVEL). Then in upspin-deploy we'd replace it like we replace PROJECT and PREFIX, depending on the project name.

It's a little more custom than what regular users need, but we already have customization for upspin.io. Maybe this is not so bad?

**Comment by adg** [comment]
I'm going to close this for now. We can reopen or create a new issue when/if this becomes a problem.
