### ISSUE TITLE
serverutil/perm: order of Access+Writers matters

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#125]
If a Writers file is first put without the Access file permitting the StoreServer to read it, the StoreServer won't be notified of it. So, the order matters: when a Writers file is modified/added, it must already be visible to servers. The solution is to either poll (Lookup) or close the watcher and re-start it every so often.

**Comment by adg** [comment]
> I'll file a separate issue and look into it.

Did you end up doing this? I don't see it. Maybe I'm just missing it.

**Comment by edpin** [comment]
No, because I fixed it with CL/7890.
