### ISSUE TITLE
all: snapshots, docs, and easy creation

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#131]
The Writers file must include the snapshot user explicitly, or else (better) implicitly, because otherwise the user cannot create the directory to store the snapshots.

Whatever the result, the process must be implemented, tested, documented, and added to the signup and/or setup docs.

**Comment by robpike** [comment]
https://upspin-review.googlesource.com/8160 makes a step in the right direction. It has the upspin snapshot command create the user+snapshot@example.com record in the key server if it is not already there.

Docs could still use work.

**Comment by adg** [comment]
I think this will mostly flow out of resolving #411, but also that it is such an unfocused issue that it should be closed.
