### ISSUE TITLE
storage: administration

### ISSUE THREAD

**Issue by n2vi** [upspin/upspin#138]
We wish to have a storeserver administrative command that will report how much total space an upspin user is consuming.    We'd like another command that the user can run to clean up any garbage, by which I mean any storage not pointed to from the user's directory tree.

This seems not to be possible in the current design.  We're contemplating various paths forward.

Option 1.  Populate the owner field in GCS bucket object metadata.   (But I'm having trouble finding where I saw this documented.)

Option 2.  Create GCS object names of the form  username/hash.   (But https://cloud.google.com/storage/docs/best-practices advises against this.)

Option 3.  Log, perhaps in storeserver VM persistent disk, all writes.

Before we go far down that path, we should confirm that we want to continue using GCS rather than a "local filesystem" approach on persistent disk.    For storage pricing and easy parallelism, we'd prefer GCS if the latency penalty is ok.   There may be a change to the Remote API that would save redirects (issue #139).

**Comment by robpike** [comment]
This issue is pretty much handled by the upspin-audit command.
