### ISSUE TITLE
test: do end-to-end tests with cache in the middle

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#156]
The integration test should deploy {store,dir}caches and test end-to-end. It might be possible, with some testenv and runner tweaks to get the integration test to simply do one run with caches.

cc @presotto

**Comment by adg** [comment]
We should bump the priority on this. If we had had this then we wouldn't have run into [this issue](https://upspin-review.googlesource.com/c/8122/).

**Comment by edpin** [comment]
Given CL/8501, I think this just became a little easier to tackle. I will give it a try.

**Comment by edpin** [comment]
Note that in this bug I'm referring to the integration tests in test/. 
CL/8501 added an end-to-end test that covers auth and the basics. We should put it through the ringer next.

**Comment by presotto** [comment]
given that 8501 is end to end with the cache in the middle, it does solve
this problem. Not sure what more you need.

**Comment by edpin** [comment]
We want to run all permutations of tests that we have in test/, such as "put a link", "delete errors", "watch non-existent file", etc, etc, etc. It it a bit pedantic, but it's great for finding issues that fall in between the cracks. 

For example, we do have tests for access, snapshots, and watch in dir/server but we added them to test/ to exercise that implementation in all flavors of packers, inprocess vs remote, etc. It has found issues before. Adding the cache should not break anything and those tests will help ensure that.

**Comment by presotto** [comment]
Ya, you should be able to just slip the cache in between your current
tests. The bind cache thing is a problem though.  We should figure out a
better solution.

**Comment by robpike** [comment]
There are tests for this now. Are they enough to close this issue?

**Comment by edpin** [comment]
I would like to add the cache to the middle of the integration tests in test/. Maybe it could be another issue if you prefer, but I originally had envisioned this behavior here.
