### ISSUE TITLE
store/server: do not allow Delete unless server owner

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#172]
Fuller description a few messages down.

**Comment by edpin** [comment]
I'd like to tackle this as this helps alleviate storage pricing pressure in larger shared servers.

I propose we handle this in two parts:
1. Part I handles changes to Perm, to allow a single account as the deleter.
2. Part II is implementing the garbage collector.

Part I is as follows:
- WrapStore is updated to contain a slice of usernames as a parameter, the `deleters` parameter.
- In store.Delete, we simply check against that identity list.
- The rest continues as usual. No changes needed to Perm itself or WrapDir.
- When starting the cmd/storeserver or cmd/upspinserver, the names of the DirServers are already given (via the store's Config). That list of names becomes the `deleters` parameter to WrapStore.

Part II requires an intersection between references used and existing. We can design that later, but it would probably involve each DirServer sending the StoreServer its list of used references. The StoreServer can authenticate these lists as coming from their rightful DirServers and then proceed to enumerate what needs to be deleted and delete them itself.

The main caveat is for the StoreServer to know whether it's done collecting information from all the DirServers that may use it for data storage. The `upspinserver` has only one, typically, but it's conceivable to have more. And the `storeserver` is likely to have many. TBD...

**Comment by adg** [comment]
> I'd like to tackle this as this helps alleviate storage pricing pressure in larger shared servers.

Is that a real issue? Seems like a low priority to me. We need to design the garbage collector first.

I have issues with your plan for part 1, but I don't think there's any reason to tackle this now. Almost all of our users run their own dir/store servers, and will do for some time.

**Comment by adg** [comment]
> WrapStore is updated to contain a slice of usernames as a parameter, the deleters parameter.

Why are we providing deleters as a parameter? Shouldn't we have a `Deleters` file alongside the `Writers` file?

**Comment by edpin** [comment]
To avoid complexity, we could simply say only the StoreServer can delete. It just needs to know its DirServers, which is not as trivial as I mentioned earlier (the store server's config file only lists the DirServers that store the StoreServer's user's root, not all DirServers that may write to it).

I'm not opposed to a Deleters file. It might be the cleaner solution. But it is more admin complexity, so we need to weigh the pros and cons. Most users won't need to see or update it ever, so it does not seem that bad to me. @robpike seemed to disfavor it, so please comment.

**Comment by adg** [comment]
It seems to me that the design of the GC would feed directly into this decision.
