### ISSUE TITLE
store: implement on-disk store server

### ISSUE THREAD

**Issue by adg** [upspin/upspin#173]
We need an implementation of `upspin.StoreServer` that uses local disk instead of Google Cloud Storage.

**Comment by jots** [comment]
It would be good if it was made clear on the home page that google cloud storage is required.  Got golang and upspin installed before I hit this show stopper.

**Comment by adg** [comment]
@jots I'm sorry about this! Hopefully we can get this done quickly so that you can get involved.

We do have this in the signup doc:

> While it is straightforward to deploy one's own servers, it is a more complex
> process that is documented in "Setting up `upspinserver`".

And in that doc:

> It assumes that you will be storing your data in Google Cloud Storage,
> a restriction that may be relaxed in time.

I suppose we could move the reference to cloud storage into signup.md directly. Would you have noticed it there?

**Comment by jots** [comment]
Not a big deal, I appreciate you creating this system.  (and now I have golang installed! :-) ) 
I would have noticed it on upspin.io homepage.

I started doing steps on  https://upspin.io/doc/signup.md and this para had me thinking that it would all be on my server (just assuming "store server" meant my own.)

"Next you need to decide whether you are going to deploy your own Upspin directory and store servers, or use those maintained by someone else."

So maybe right there:
"Next you need to decide whether you are going to deploy your own Upspin directory and store servers (store server requires use of google cloud storage), or use those maintained by someone else."

thanks.

**Comment by adg** [comment]
I sent this change: https://upspin-review.googlesource.com/8002

**Comment by adg** [comment]
I'm working on actually implementing this now.

**Comment by jdiez17** [comment]
Ah, I was about to take a crack at this but since @adg is on the job I'll stand aside. My only question is: how do remote client Get blobs if LinkBase is not available? Presumably they communicate directly with the Storage Server?

**Comment by tgulacsi** [comment]
Can we use Camlistore's diskpacked storage?
Can I implement it? What does it need?

**Comment by hydro-b** [comment]
I was also a bit surprised to find out I needed Google Cloud Storage. Especially after the intro about storing your data locally. A cloud is not local for me ;). I'll start evaluating upspin as soon as "local storage" servers are supported. Thanks for working on it!

**Comment by fawick** [comment]
IANAL but: Since GCP billing is not available for private individuals in Europe and I would need a paid GCP storage bucket for upspinserver there currently seems to be no legal way to run an own upspin server here.  

(GCP require their European customers to be businesses for reasons I do not understand.)

**Comment by adg** [comment]
This is now done, everyone! As per the [updated instructions](https://upspin.io/doc/server_setup.md), you can now skip the `upspin setupstorage` part if you don't want to use Google Cloud Storage with `upspinserver`.

**Comment by adg** [comment]
@tgulacsi if the licenses are compatible, and I believe they are, then bringing in diskpacked is probably worth doing. Want to file a separate issue about it? We can discuss how to proceed with that there.

**Comment by riking** [comment]
You should probably have put the `backend=Disk` string somewhere in the documentation.

**Comment by adg** [comment]
@riking thanks, I filed #245
