### ISSUE TITLE
client: check Writer is plausible when verifying DirEntry

### ISSUE THREAD

**Issue by n2vi** [upspin/upspin#179]
To protect from a malicious/compromised/compelled directory server, the client should confirm that Writer is either Owner or currently has write permission in the directory before verifying its signature on a DirEntry.

**Comment by robpike** [comment]
I'm not sure the first request can work. I might allow writers while creating a tree but then mark the tree read-only once it's done. That's a reasonable thing to do but would cause problems if we required the Writer to have write permission at read time.

**Comment by n2vi** [comment]
If your home directory is on Upspin, you don't want a bad directory server putting files in ~/bin signed by some random user.

We could possibly fall back to trust-but-verify like we do with key server, but I'm continuing to look for a better answer.

**Comment by n2vi** [comment]
New proposal:   Introduce a new "Sign" right in Access files, implied by Write or Create but also available to be explicitly granted.   Typically this would only be done when freezing a directory by making it read only. 
 When verifying a file signature, confirm that the signer has Sign rights in the directory.   Owner would always have Sign rights, so most tests can be done without calling WhichAccess.

**Comment by n2vi** [comment]
Summary of discussion this afternoon:

We like the idea of not introducing a Sign permission but instead checking Write permission against a historical Access file, hashed as part of the file signature.  There is mechanism that would need to be created to get those old Access files from the directory server, and there is backwards compatibility with old signatures to arrange, but something along these lines can likely be made to work.

While we all ponder this matter further, I'm tempted to add an experimental version to client-side DirEntry signature verification, behind a flag "-tinfoil", checking that the signer is either the owner or currently has Write permission.  As Rob notes above, this check fails in the important case of directories that have been made read-only after collaboration.  But that may be rare enough to tolerate by people who would be motivated to set -tinfoil.  (Remember, we're just guarding here against a malicious/compromised/compelled directory server, which we hope is unlikely to happen in real life.)

**Comment by robpike** [comment]
The problem with that solution is that it complicates the user experience significantly. I'd prefer a solution that provided the security without visible complexity.

One suggestion that has been made is that we maintain a verifiable log of Access file modifications, thereby allowing us to determine if a user had write permission in the past. This sounds expensive, but the check (on the client) would only be necessary when the Writer field does not name a user who is currently a writer, which would in practice be very unusual.

**Comment by n2vi** [comment]
Change 8505 (https://upspin-review.googlesource.com/8505) adequately covers this for now, under the flag -prudent.

Re-open when some better idea occurs to someone.
