### ISSUE TITLE
dir/server/tree: write logs should be rotated and cleaned up periodically

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#184]
To be designed.

Things to keep in mind:
* Impacts the Order number in Watch.
* Backup/mirror caches may need a long history.
* Log disk is small in capacity.
* Some design choices may require a wipe (and thus be backward incompatible).
* Coordinating snapshots and log rotation may involve coordination between different layers (log is very low level and "dumb" currently).

**Comment by edpin** [comment]
I wrote a proposal designdoc. Comments are very welcome -- smaller ones can go on the doc itself, longer one might be better suited for this issue.

[Log Rotation Designdoc](https://docs.google.com/document/d/1sU1isH1jhywxYOwS8E3Sn-gWswXIJw1LdZResGkkZ-I/edit?usp=sharing)

Thanks.

**Comment by adg** [comment]
I think this is done now.
