### ISSUE TITLE
launch: Need a plan for paying for outbound emails

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#185]
Currently, we send 2 emails for each sign up: a welcome email to the user and an internal email to the upspin list. Our free SendGrid account can handle 20,000 emails per month. That should be enough for a while.

But the inflection point, if it's coming, may happen very quickly. We don't want to have our emails suspended suddenly. 

I think it would be prudent to have a credit card on file with SendGrid or a plan of action to monitor and react quickly shall we cross the free threshold.

**Comment by Splizard** [comment]
As a backup you can send the email from Go. 
https://github.com/go-gomail/gomail
You can send email directly from Go, you don't need a specific SMTP server (I have proven otherwise).
