### ISSUE TITLE
rpc: remove ping

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#189]
Currently, pings are not crossing the network. But all servers need to implement Ping due to upspin.Service

If we're not going to implement rpc.Ping, we might as well delete it from upspin.Service.

HOWEVER:

There's a benefit to Ping besides the bind cache (in package bind): it could be part of the GCP healthcheck and we could configure GCP to use it in the future for error reporting and autoscaling -- might come in handy for the keyserver one day.

**Comment by adg** [comment]
Ping is a no-op at the RPC layer now. We should remove it.
