### ISSUE TITLE
dir/server: reconsider log vs watch synchronization

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#190]
If CL/7817 goes in, Puts and Deletes will be synchronized with Watch on a tree (per user tree, not globally).

This might be too restrictive.

We may be able to relax this if instead of a Lock in the log we use the tree.watcher channel to let the watcher know how many new units of work there are. Or, even better, if we can simply bypass the reading of the log file in watch altogether by using the channel.

This requires some logic changes and a careful calibration of the channel buffer size to we're less likely to be in a situation where the watcher goroutine is preventing tree modifications by not draining the channel fast enough.

**Comment by adg** [comment]
Is this issue still relevant?
