### ISSUE TITLE
doc: make it clear that signup works without dir/store servers

### ISSUE THREAD

**Issue by adg** [upspin/upspin#210]
Quoth [@davidcrawshaw](https://twitter.com/davidcrawshaw/status/834180207582072832):

> should it be enough to signup with http://key.upspin.io  and then ls you? does not seem to work. do I need a dir server first?

It actually is possible to use Upspin without having a dir or store server for one's own use. If you just want to read Upspin files, you can provide any host name to the `-server` (or `-dir` and `-store`) flags.

We should think about changing the required-ness of those flags.

**Comment by crawshaw** [comment]
Misunderstanding the signup document, I signed up with:

```upspin signup -server=key.upspin.io david@zentus.com```

The result was this, which I found unenlightening:

```
$ upspin ls nf@wh3rd.net/pub/
upspin: ls: dir/remote.Glob("remote,upspin.adg.tech:443"): information withheld:
	dir/server.Glob:
	nf@wh3rd.net/pub:
	dir/server.listDir
```

Modifying my config to point to dir.upspin.io and store.upspin.io means this command now succeeds:

```
$ upspin ls nf@wh3rd.net/pub/
nf@wh3rd.net/pub/Access
nf@wh3rd.net/pub/augie.jpg
nf@wh3rd.net/pub/augie.png
nf@wh3rd.net/pub/folk.mp3
```

But I confess I don't understand why. I assumed searching for nf@wh3rd.net would substitute different dir/store servers.

**Comment by adg** [comment]
I actually messed up the permissions on the `/pub/` directory, so the first error message was real and expected. I think it's just a coincidence that you changed your config while I was fixing my `Access` file. 😄 

So I think the value you provided as `-server` was just ignored, and will continue to be unless you try to create your user root or put a file.

If you want to see all the calls made by the upspin command, specify the `-log=debug` flag as the first arg.

**Comment by crawshaw** [comment]
OK, good to know.

It would be nice if the error message said both less and more. As a command line user I don't have any use for the stack-like trace through `dir/server.Glob` and `dir/server.listDir`.

And "information withheld" is not nearly as obvious as the common computer error "access denied".

**Comment by adg** [comment]
> And "information withheld" is not nearly as obvious as the common computer error "access denied".

"Information withheld" is distinct from "Access denied" in that it doesn't tell you *anything* about the namespace. If you get a "Permission" error (our equivalent to "Access denied") then you know you are allowed to *know about* it, just not allowed to do whatever it is you're doing. If you get "Information withheld" then you don't even know if you're allowed to know. 😄

**Comment by dgnorton** [comment]
If `-server example.com` is used during signup, can the key server be updated with the correct domain later on after setting up a real server? `upspin signup -help` gives useful info but probing some of the other commands that look promising doesn't (e.g., `setupdomain -help` and `setupserver -help`).

**Comment by edpin** [comment]
The keyserver can be updated by the user him/herself (provided they have the right keys). 

One can update the store and dir endpoints as well as their keys.

See `upspin user -put`.

**Comment by adg** [comment]
We should make that clear in the docs for `upspin signup` too.

**Comment by robpike** [comment]
The signup command requires that -dir and -store flags both be set or that -server is set, which is equivalent. Should this requirement be dropped?

**Comment by adg** [comment]
This will also flow out of #411.
