### ISSUE TITLE
cmd/upspin: shell should remember recent history

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#213]
It's a very useful feature to press [arrow up] and have it show me the last few commands I typed, instead of the annoying ^[[A that I get currently.

**Comment by robpike** [comment]
Although I feel your pain, I'd like to avoid making the shell a lovely tool and encourage people to use the native environment.

Someone's going to want to add color and cursor addressing and history and variables and quoting and on and on, and that's not a good plan.

**Comment by edpin** [comment]
I could almost predict this answer. But I had to ask, since it's the single most annoying thing in the universe. :-)

But it makes sense. I will use upspinfs.
