### ISSUE TITLE
doc: Clarify use of +suffix in email address

### ISSUE THREAD

**Issue by RalphCorderoy** [upspin/upspin#215]
Section "Users" in https://upspin.io/doc/overview.md says

> Some email services provide a way to modify the user name to allow multiple addresses to refer to the same user. The usual syntax is to follow the user’s name before the @ with a plus sign and a suffix. Upspin uses this technique to allow a user to own multiple Upspin services.

It's unclear if the user needs an email server that accepts emails to `user+foo@...` to make use of this, or whether upspin is just borrowing the syntax and only ever uses the suffix-less email address. (A hyphen is a common alternative to the plus in MTAs.)

**Comment by ibrasho** [comment]
> Users in Upspin are identified by an email address that, within Upspin, is called the user name. When the user is first registered with the system, the address is used to verify the user’s identity; after that, it just serves as the user’s identifier, for example, ann@example.com.

It seems that is just an example. The user identifier is just the email address used during registration.

The real issue is if the user is using a service that treats `amy@server.com` as a different address than `amy+may@server.com`. The `+` sign is a valid character in the local part of an email address, and therefore could be used to differentiate addresses.

**Comment by edpin** [comment]
The only time you need a mail server to deliver email to you is during the initial registration. At that point ann@example.com must be able to receive email. Once that's done, Ann can create a new sub-account for ann+music@example.com or ann+photos@example.com. Upspin treats +suffix as being a separate Upspin account (with possibly different keys) but "owned" by the non-suffixed user.

You can create a suffixed user with the cmd/uspin user -put command. The format of the file is the same as the output of cmd/upspin user. 

Note that new users automatically get a +snapshot suffixed user, with the same public key. A +snapshot suffix is special in its own ways as it enables automatic snapshotting of one's root.

**Comment by RalphCorderoy** [comment]
So if xyzzy.com doesn't support `+` as a user can I use my email address `foo+bar@xyzzy.com` for initial registration? And that gives me the `foo+bar+snapshot` sub-account, etc?
If `foo@xyzzy.com`, someone else, beat me to initial registration, does my initial registration fail as I look like their sub-account?

**Comment by edpin** [comment]
You can't have more than one + in your account name. So, foo+bar@ belongs to foo@ and only foo@ or foo+bar@ itself can make changes to it on the keyserver.

If foo@ is already registered, you can register foo+bar@, but if foo@ decides to change your public key or which dir and store servers you use, foo@ is allowed to do so, currently.

**Comment by RalphCorderoy** [comment]
(This is getting off-topic from clarifying the docs now, but if a sub-account wasn't a valid email address then the conflict couldn't arise.)

**Comment by 4ad** [comment]
I don't understand the rationale behind `+suffix` syntax. In the light of @robpike's [The Hideous Name](https://research.swtch.com/name), this seems particularly bizarre. Why create "alternate roots" when you can simply partition your root directory?

**Comment by edpin** [comment]
A suffixed user allows a user to setup new users without requiring them to have valid email accounts. For example, if you want your thermostat controlled by Upspin, perhaps it could be called `me+thermostat@example.com` and there would be no need for `example.com` to support email for the +thermostat account in order to signup (click on links from emails), since `cmd/uspspin user -put` can do that once you generate a set of keys with `cmd/upspin keygen`. 

We can do better at documenting these things. That's what this issue is for.

**Comment by edpin** [comment]
One more note on the thermostat example: since thermostat is a different user with a different set of keys, you can grant it few or no rights to your main root and not worry too much if it gets compromised or has security flaws as it does not have *your* keys.

**Comment by 4ad** [comment]
@edpin That is not what I meant. I know what `+suffix` does in upspin. The question was about *syntax*, not semantics.

**Comment by robpike** [comment]
@4ad I admit it's hideous, and we did agonize about the right answer. The problem was that we needed a way for a single user to be able to control multiple keys for multiple servers, and without introducing something like a mount point, which would require a much more complex architecture interface, there weren't many options. It was an expedient hack. Like most expedient hacks, it is hideous, but expedient.

The whole way email addresses are used is much less important when you keep in mind it's basically bootstrapping the system. I expect things will get smoother eventually, but the suffix notation does the job for now and may stay, perhaps more hidden.

**Comment by edpin** [comment]
With Rob's answer and the CL to clarify the docs, I think we can close this issue now. Right @RalphCorderoy @4ad ?

**Comment by RalphCorderoy** [comment]
I'm happy with however you judge it. The CL doesn't seem to warn not to register `foo+upspin@example.com` as a primary user because of problems down the line with +snapshot failing due to two pluses.

**Comment by adg** [comment]
@RalphCorderoy to my reading, the CL makes it impossible to signup as any user name with a +suffix.

**Comment by RalphCorderoy** [comment]
Here's how I think it could be reasonably interpreted.

    Users in Upspin are identified by an email address that, within Upspin, is
    called the user name.
    When the user is first registered with the system, the address is used to
    verify the user's identity; after that, it just serves as the user's
    identifier, for example, `ann@example.com`.

OK, I'll register `foo+upspin@example.com`.

    Some email services provide a way to modify the user name to allow multiple
    addresses to refer to the same user.
    The usual syntax is to follow the user's name before the `@` with a plus sign
    and a *suffix*.
    Upspin uses this technique to allow a user to own multiple Upspin services.
    For example, `ann+camera@example.com` might be the Upspin user name for an
    Internet-connected video camera owned by `ann@example.com`.

Giving `foo+upspin+camera@example.com`.  Hmm, will that be a problem?

    Suffixed users belong to their primary user (the one without the suffix).

OK.  My "user's name" is `foo+upspin` as that's what's "before the `@`".

    Primary users can therefore make changes to entries on the key server for their
    name with a suffix.

OK.

    For example, `ann@example.com` may change the keys and the store and directory
    endpoints for`ann+camera@example.com`.

OK.

    The converse, however, is not allowed: `ann+camera@example.com` cannot make
    changes to `ann@example.com`.

Good.

    Suffixed users can be created only by their owners.

That's fine.

    For this reason, they do not require a working email address.

Ah, OK, so `foo+upspin+camera@example.com` isn't going to be emailed and I don't need to consider if that address works.

I think there either needs to be a warning not to use a plus in the username part of the email address, and this document might not be the right place for that warning, or the code needs to reject an attempt to register so the warning isn't needed and the error message can explain instead.

But if you think the interpretation is unlikely then that's fine.

I don't understand the meaning of the key.upspin.io/log file, but I did try a bit of a search on it that might show one such primary user with a plus.

    $ egrep -o '[^"]+@[^"]+' log | grep + | rev | sort -Vu | rev >all
    $
    $ grep '+.*+' all
    $ grep +@ all
    $ grep '@.*+' all
    $ sed 's/+[^@]*//' all | uniq >root
    $
    $ while read e; do fgrep -q "$e" log || echo "$e"; done <root
    logln@protonmail.com
    $
    $ egrep -o 'logln[^@]*@protonmail.com' log | sort -Vu
    logln+snapshot@protonmail.com
    logln+upspin@protonmail.com
    $

So perhaps it's already happened.

**Comment by edpin** [comment]
Correct. We never meant to allow it and the CL closed that loophole.

**Comment by edpin** [comment]
@RalphCorderoy yes, it has happened a few times. It was an error. We never intended for this to be allowed. I will clarify further.

**Comment by RalphCorderoy** [comment]
I found a couple of recent commits that have altered the code in this area to error.
Linking them from here for reference.
‣ cmd/upspin: fail early on signups with suffixes 5c006f119654037e41c8870370b3b57f25e85135
‣ cmd/keyserver: do not allow signups from suffixed users 37570194ba1fd0b408a0ff7ebb82024a2d218967

**Comment by edpin** [comment]
I think we're at a good state now. Please re-open if there are missing pieces that need further checks or clarification. Thanks.

**Comment by rfielding** [comment]
I didn't setup my privileges correctly when running upspin-ui, and had gone into it to use it locally. I tried to reset everything by adding a new key to my services account; and wiping out my ~/.ssh/$email key and ~/upspin dir.  I have a new keypair, but now I can't register $email with upspin-ui.

Any advice on how to get unstuck from this?

**Comment by RalphCorderoy** [comment]
Try asking on https://groups.google.com/forum/#!forum/upspin
