### ISSUE TITLE
pack/ee: replace AES-CTR with Chacha20

### ISSUE THREAD

**Issue by david415** [upspin/upspin#219]
Replace all usage of AES in counter mode with Chacha20 or is there a reason not to?

**Comment by adg** [comment]
What's the reason *for* doing it?

**Comment by n2vi** [comment]
Chacha20 is faster on low end processors, and we do support it in our TLS ciphersuites as a client option.

But as the archival format on storage servers where we want commonality, I don't see sufficient justification.
