### ISSUE TITLE
KeyServer for ann@example.com should run on example.com

### ISSUE THREAD

**Issue by bestouff** [upspin/upspin#220]
The KeyServer is the only central element of the whole (if you don't count DNS, but even this is distributed). Why not going the full route and allow running a KeyServer on one's own domain ?

**Comment by edpin** [comment]
That could fragment the namespace if not done carefully. One would need to know the authoritative keyserver for a user and then reconcile/reject discrepancies. But it's something to consider. We're just not there yet as it increases complexity.

**Comment by bestouff** [comment]
How about having the domain announce its keyserver through a DNS record, and if not using the default global keyserver(s) ?

**Comment by adg** [comment]
This is essentially a duplicate of issue #216, so I'll close this one.
