### ISSUE TITLE
dir/server: The creation of a snapshot does not trigger a new event in Watch

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#229]
This is because a snapshot has already been written to the log. 

Watch(-1) will work on a snapshot iff the snapshot has already been created. But if I'm waiting for a file or directory to appear under my watched path, I won't get that event.

Likely not an issue anyone cares deeply about but worth keeping track of it, at least for documentation purposes for now. I'll see if it's an easy fix.

**Comment by robpike** [comment]
Maybe just forbid that operation. It's almost pointless to support.

**Comment by edpin** [comment]
It's useful in testing and turns out it wasn't much code.

**Comment by adg** [comment]
The fewer differences there are between snapshot trees and normal trees,
the better.
I'm glad Ed made it work.
