### ISSUE TITLE
doc: describe multi-device usage

### ISSUE THREAD

**Issue by fawick** [upspin/upspin#234]
I am unsure how to use Upspin on more than one client device, e.g. a laptop A and a workstation B. 

* Shall I simply copy `~/upspin` folder from A to B and then run `upspin keygen -secretseed` on B? 
* Or would I copy `~/.ssh/*.upspinkey` to B, too?
* Or would I signup as new `user+deviceB@example.com`?

**Comment by n2vi** [comment]
Copy ~/upspin and ~/.ssh/*.upspinkey on the second device and you should be
good to go.

It is intentionally that simple, so that people can easily create redundant
devices and so that they can viscerally appreciate the need to protect
~/.ssh from theft.

**Comment by fawick** [comment]
Okay, than "by accident" I already did the right thing last night. Thanks @n2vi!

I would like to add this piece of information as a section to a new document `/doc/usage_examples` (as I proposed in #235), so that it "by accident" becomes "as documented"

I can come up with a PR on Gerrit tonight.

Is my understanding correct that re-running `upspin keygen -secretseed <...>` on B is fully equivalent to copying ~/.ssh/*.upspinkey when I use the seed that I got when ran `upspin signup`?

**Comment by robpike** [comment]
Yes, your understanding is correct.

Another thing we should explain better is how to be multiple users on the same machine, for instance oneself and a separate administrator.

**Comment by DeedleFake** [comment]
Is there any way to use multiple keys? For SSH, for example, I like to use seperate keys for different devices so that I can revoke a key if a device gets stolen or otherwise compromised.

Also, I was just able to do `upspin signup -server=<server> <username>`, then `upspin keygen`, and then `upspin user | upspin user -put` on a new device without copying the key from the device I did `upspin signup` on earlier and it seems to have just worked without any kind of verification. Doesn't that mean that anyone could do that from anywhere and get access to all of my stuff?

**Comment by adg** [comment]
@DeedleFake one way to use multiple keys is to create multiple Upspin users and put them all in the root Access file for the main user. 

> Also, I was just able to do upspin signup -server=<server> <username>, then upspin keygen, and then upspin user | upspin user -put on a new device without copying the key from the device I did upspin signup on earlier and it seems to have just worked without any kind of verification. Doesn't that mean that anyone could do that from anywhere and get access to all of my stuff?

That sounds weird. Would you care to file a separate issue describing (in as much detail as you are able) the steps you took to end up there?

**Comment by DeedleFake** [comment]
> one way to use multiple keys is to create multiple Upspin users and put them all in the root Access file for the main user.

That works, but that requires a seperate e-mail address for every machine I use. I have about 5 machines I use on a regular basis that I would consider accessing upspin with.

**Comment by stapelberg** [comment]
> @DeedleFake one way to use multiple keys is to create multiple Upspin users and put them all in the root Access file for the main user.

If I add `read,list: michael+x1c@stapelberg.ch` to `michael@stapelberg.ch/Access`, does that mean that michael+x1c can read and list files _stored_ underneath michael@stapelberg.ch/, or does it also mean that michael+x1c can read and list files _shared with_ michael@stapelberg.ch?

**Comment by robpike** [comment]
The former. The scope of Access files is the directory they are in and subdirectories; the access they grant to one user is not affected by the presence of another user also in the Access file.

**Comment by stapelberg** [comment]
Thanks for clarifying. What is the intended way for my friends to share a file with all my devices, then? Would it be idiomatic to create a group called e.g. `michael@stapelberg.ch/Group/alldevices` and ask people to share files with that group by default?

**Comment by robpike** [comment]
That's what I would do.
