### ISSUE TITLE
doc: describe sharing dirserver/storeserver between group users

### ISSUE THREAD

**Issue by fawick** [upspin/upspin#235]
In case I have set-up a upspinserver for my domain `example.com`, how would I add more group users to it? Is it sufficient for them to run `upspin signup  -server=upspin.example.com numbertwo@example.com` or would I need to add permission for them somehow?

**Comment by edpin** [comment]
If you own the domain you can create new users using the upspin user -put command. But there are two caveats:
1) You need to prove you own the domain by adding a TXT record to your DNS as explained here: 
https://github.com/upspin/upspin/blob/master/doc/server_setup.md#set-up-your-domain
2) You cannot edit (nor delete) the user later on. Only the user who has the private key can update their user with the keyserver (and no one can delete a user, ever).

However, what I think you're asking is how to allow new users (whether part of your domain or not) to write to your server. 

You need to update the Writers file in `upspin-store@example.com/Group/Writers` to include every user allowed to write to your store server. That will enable them to create roots and directories and store files with your server.
https://github.com/upspin/upspin/blob/master/doc/server_setup.md#configure-upspinserver

Let me know if this helps.

**Comment by fawick** [comment]
Thank you @edpin, you are absolutely right, I indeed meant to ask how to setup the required write permissions and I now understand from your comment what I would need to do.

I would like to propose a new documentation item, then:

## Current situation
https://github.com/upspin/upspin/blob/master/doc/server_setup.md#configure-upspinserver states that the file `upspin@example.cop/Group/Writers` is written but it does not say that I would need to edit this file for any further user. 

https://upspin.io/doc/signup.md states:

> If you are planning to join an existing Upspin directory and store server, ask the administrator to add 
> your username to the store’s Writers group. (They’ll know what to do.) This will grant you permission 
> to create your tree in that directory and store data in that store server.

So, the puzzle piece for aspiring Upspin administrators that is missing is in the docs is: "How do I add usernames to the Writers group?" The docs assume an admin would already know that.

## New doc item Usage Examples

I propose a new Markdown document `/doc/usage_examples.md` that describes common things to do when working with Upspin, starting with  

- How do I allow another family member/friend to use the server I set up
- How can I use multiple devices in parallel (see #234)

I can come up with a first draft for this and submit it to the codereview server tonight.

What do you think?

/cc: @adg

**Comment by swetland** [comment]
Does one need to restart the server or otherwise inform it that you've modified the Writers file?

**Comment by gkelly** [comment]
@swetland, upspinserver watches Writers.  However, when I first started upspinserver it didn't monitor Writers properly.  I unstuck it by restarting it and haven't seen it miss updates to Writers since.

**Comment by edpin** [comment]
@fawick yes, an example doc with a few common scenarios would be great. Please. And thank you!
@swetland Yes, what @gkelly said. There is indeed a possible situation where the Writers file gets "stuck" (see issue #125). A restart will fix it for now.

**Comment by fawick** [comment]
Did I overlook a trigger for making the new document available on https://upspin.io?

**Comment by adg** [comment]
@fawick nope, we just haven't pushed it out yet. Will do shortly.
