### ISSUE TITLE
Use XDG Base Directory Specification for config files

### ISSUE THREAD

**Issue by adrianlzt** [upspin/upspin#237]
Instead of using ``$HOME/upspin/config`` use a standardized path like:
```
$HOME/.config/upspin/config
```

**Comment by 4ad** [comment]
That would be awful, please no.

**Comment by adrianlzt** [comment]
Awful but standard? 🎉

**Comment by 4ad** [comment]
Roman numerals were standard too. For millennia.

**Comment by adg** [comment]
I'm not particularly fond of `.config` but I would like to give people the choice as to where they store their stuff.

It should be possible for people to store their upspin configuration and cache files somewhere. There's the `-config` flag already, so your config can live anywhere, but `upspinfs` also needs some facility to specify the cache location, which I believe is hard-coded at the moment.

**Comment by awly** [comment]
Maybe provide an `$UPSPIN_PATH` env var (defaulting to `$HOME/upspin/`) so that people with custom locations won't have to specify `-config` all the time?

**Comment by adg** [comment]
I'm also a bit repulsed by adding more environment variables. They are quite mysterious on Windows, for one thing.

People who want to specify `-config` every time could use a shell alias or script:

```
alias upspin="$HOME/bin/upspin -config=/path/to/config"
````

**Comment by adrianlzt** [comment]
Ok, I just thought that everyone was following the standard, but it's ok for me to go with the alias. Thanks

**Comment by adg** [comment]
> upspinfs also needs some facility to specify the cache location, which I believe is hard-coded at the moment.

This is not quite true; I filed #246 with the full details.

**Comment by adg** [comment]
@adrianlzt thanks for the issue report. 👍
