### ISSUE TITLE
github: provide more detail in the repository description

### ISSUE THREAD

**Issue by mdlayher** [upspin/upspin#238]
At the moment, the repository description is:

> Upspin https://upspin.io

A search for "upspin" doesn't really say anything about what the repository is for.

https://github.com/search?utf8=%E2%9C%93&q=upspin

![selection130](https://cloud.githubusercontent.com/assets/1926905/23265033/696e1d40-f9b1-11e6-984d-536a16d8db5b.png)

**Comment by robpike** [comment]
The README.md file has lots of information but you're right that the repo string could be more informative or at least less terse.

**Comment by mdlayher** [comment]
Yep, that's exactly what I mean.

Perhaps a shortened version of this could be used:
> Upspin is an experimental project to build a framework for naming and sharing files and other data securely, uniformly, and globally: a global name system of sorts.

**Comment by robpike** [comment]
That seems longer that I think is customary, but I took a stab. I think with that text and the link to click on, it should be fine. I'm not sure it's necessary for GitHub search to find it using that text, since the web site is there and the keywords are present. Push back if you disagree.

**Comment by mdlayher** [comment]
> Upspin: A framework for naming everyone's everything. 

Works for me!  Thanks.  Closing.
