### ISSUE TITLE
doc: some confusion about where to run 'upspin setup*' commands

### ISSUE THREAD

**Issue by driusan** [upspin/upspin#240]
I've been trying to follow the instructions [here](https://upspin.io/doc/server_setup.md) for setting up a upspinserver on an AWS instance.

When getting to the `upspin setupserver -domain=example.com -host=upspin.example.com` part, the command fails because the instructions say to run "setupdomain" on the server and update the txt records, but the `~/upspin/deploy` directory was never created on the workstation which the instructions say to run  the `setupserver` command from. After copying them to the workstation and fixing permissions, it's still failing because the public keys on the server aren't correct, it having some up with its own public/private keys for the same username somehow.

When I run `upspin user` on the workstation I get a different public key than when I run it on the server I'm attempting to setup. On the server, it's accompanied by the error "upspin: user: local configuration differs from public record in key server:"

After running `upspin user -put` on the server and pasting the output from `upspin user` on the workstation with the correct key, the key on the server is not updated and `upspin user` continues to show the old, incorrect key. Neither `-force`, nor `-in` seems to affect it. There's no error message from `upspin user -put`.

I'm not really sure where to go from here in order to fix this situation I've gotten myself into..

**Comment by rwcarlsen** [comment]
You need to run setupdomain and setupserver on your local workstation.

**Comment by adg** [comment]
@driusan as @rwcarlsen points out, you need to run all the `upspin` commands on your workstation, not the server. 

Given the confusion here, I wonder what we could do differently. Is there something in the docs that threw you off? Or is there something we're not saying? Should we call out more clearly where each set of commands should be run?

**Comment by rwcarlsen** [comment]
On my first try, I ran the setup commands on my vps first instead of my local workstation.  A more careful reading of the docs resolved the issues, but it is not terribly obvious.

**Comment by swetland** [comment]
I admit to making a similar mistake: I did setupuser on a workstation but then tried to setupdomain on the server.  Re-reading the docs I discovered that I was doing it wrong.  

Perhaps something like this could be added to the end of the list in Prerequisites:

* A workstation upon which you have installed upspin and configured your user.  You will run various upspin setup* commands *on the workstation* to register your server with the key server and configure your server, remotely, from the workstation.

**Comment by driusan** [comment]
@adg I eventually got it working, but I think my confusion arises from two points:

1. The fact that the document is called "Setting up upspinserver" implies that it should be followed on the server if you're not reading it closely, until you get to the point where it explicitly says to run the command on the workstation. Simply stating upfront that the `setup*` commands should be run on the workstation as @swetland suggests would probably help.
2. It turns out that my real problem had nothing to do with the keys. Since I'm not using Google Cloud, I had the same problem that someone else pointed out on the mailing list about setting the txt record literally on '@.domain' instead of on the root of the domain. When this happens and the key server can't validate the txt record because it's on the wrong domain, the error message is just a generic 'permission denied' error. I thought this was related to the fact that `upspin user` was complaining that the keys not matching for the user, but it turns out it couldn't validate the txt record.

**Comment by awly** [comment]
The docs could also add a fake "hostname" to command examples, e.g.:
`you@workstation $ upspin setupserver -domain=example.com -host=upspin.example.com`
