### ISSUE TITLE
nit: use .github/ISSUE_TEMPLATE.md instead of prose in CONTRIBUTING.md

### ISSUE THREAD

**Issue by stapelberg** [upspin/upspin#243]
To increase the chance that users actually fill in the fields described in CONTRIBUTING.md (I missed them at first) when filing new issues, consider using a GitHub issue template. See https://github.com/i3/i3/blob/next/.github/ISSUE_TEMPLATE.md for an example, see https://github.com/blog/2111-issue-and-pull-request-templates for the corresponding blog post.

**Comment by adg** [comment]
I'm lukewarm on this.

The quality of issue reports we're getting seems pretty high at the moment, and many of them are not "issue reports" so much as feature requests or other things that don't really fit the template. I'm not sure that adding more boilerplate to the issue reports would help or hinder at this point.

Does anyone else have thoughts on this?

**Comment by robpike** [comment]
I think with the quality we're seeing now (thanks everyone!) there is no need for more process like this. In time, it may become necessary.

**Comment by adg** [comment]
I'll close this for now. We can revisit as the project grows.
