### ISSUE TITLE
doc: confusing messages guiding setup server process

### ISSUE THREAD

**Issue by adrianlzt** [upspin/upspin#244]
When deploying a custom server, after executing the setupdomain command:
```
$ upspin setupdomain -domain=example.com
...
After that, the next step is to run 'upspin setupstorage'.
```

But reading the [doc](https://upspin.io/doc/server_setup.md) seems that ``setupstorage`` has to be used only if deploying in Google Cloud.

Doc is not really clear neither:
```
At a later step, the upspin setupserver command will register your server user for you automatically.
```

**Comment by stapelberg** [comment]
I ran into the same issue: https://upspin.io/doc/server_setup.md states:

> Once the TXT record is in place, the key server will permit you to register the newly-created users that will identify the servers you will deploy (as well as any other users you may choose to give Upspin user names within example.com). At a later step, the upspin setupserver command will register your server user for you automatically.

Which is, as @adrianlzt notes, a very different message than what the `upspin setupdomain` prints. Notably, the message quoted above could be improved by adding a reference to _how_ one can register the newly-created users.

**Comment by adg** [comment]
Related to issue #240

**Comment by adrianlzt** [comment]
[This line](https://github.com/upspin/upspin/blob/6f7b2d79bd286388ae31c95898f91dc4eb668024/cmd/upspin/setupserver.go#L29) should be also changed:
```
Setupserver is the final step of setting up an upspinserver.
It assumes that you have run 'setupdomain' and 'setupstorage'.
```

**Comment by adrianlzt** [comment]
Also: https://github.com/upspin/upspin/blob/6f7b2d79bd286388ae31c95898f91dc4eb668024/cmd/upspin/setupdomain.go#L29

**Comment by adg** [comment]
I sent this change: https://upspin-review.googlesource.com/8065
