### ISSUE TITLE
cmd/cacheserver/cacheutil: need a way to provide other cacheserver flags

### ISSUE THREAD

**Issue by adg** [upspin/upspin#246]
I'd like to run my local cacheserver with a larger cache size, which is achieved by passing a flag, but `cacheutil.Start` only passes through the `-writethrough`, `-cachedir`, and `-log` flags (and I'm not sure that it should be passing through `-log`).

Maybe there should be a cache configuration file somewhere for things like `-cachedir` and `-cachesize`.

**Comment by robpike** [comment]
I believe this is fixed now. Closing.
