### ISSUE TITLE
No root for user error in local deploy

### ISSUE THREAD

**Issue by adrianlzt** [upspin/upspin#247]
I'm trying to deploy a upspin server inside a docker container. I have done some workarounds to almost have it working.
Then I stopped and try to start it again but is falling ([full log](https://gist.github.com/adrianlzt/6d8cf5afb5d993da2f694403248fad11)):

```
2017/02/24 00:10:17.556351 factotum.NewFromDir("/root/upspin/server"): d8315b2b7b44f64dd083e8c01e4ad103a4b89e80d5f6b33d23205d02f31e20b6
2017/02/24 00:10:17.556801 Store and Directory servers initialized.
2017/02/24 00:10:17.557046 Storing data under /root/upspin/server/storage
2017/02/24 00:10:17.559090 https: not on GCE; serving HTTPS on "0.0.0.0:443" using provided certificates
2017/02/24 00:10:17.559394 https: WARNING: using self-signed test certificates.
2017/02/24 00:10:17.560372 dir/remote.Dial("unassigned")("upspin@upspin.undo.it", "remote,upspin.undo.it:443")
2017/02/24 00:10:17.560627 dir/remote.Lookup("remote,upspin.undo.it:443")("upspin@upspin.undo.it/Group/Writers")
2017/02/24 00:10:17.577006 dir/server/tree.recoverFromLog: Tree is all caught up for user upspin@upspin.undo.it
2017/02/24 00:10:17.577455 dir/server/tree.sendCurrentAndWatch: error adding watcher: user upspin@upspin.undo.it: dir/server/tree.LogIndex.Root: item does not exist: no root for user
...
```

Seems some problem with the local storage, but don't know what to do.

```
[root@94bcaa982884 opt]# tree /root/upspin/server/
/root/upspin/server/
|-- Writers
|-- dirserver-logs
|   |-- tree.index.adrianlzt@gmail.com
|   |-- tree.index.upspin@upspin.undo.it
|   |-- tree.log.adrianlzt@gmail.com
|   |-- tree.log.upspin@upspin.undo.it
|   |-- tree.root.adrianlzt@gmail.com
|   `-- tree.root.upspin@upspin.undo.it
|-- public.upspinkey
|-- secret.upspinkey
|-- serverconfig.json
`-- storage
    `-- N0
        `-- N0MzNjA3OTA3OTZBNjE0QUEzMEQzQUJCQUI0NkUzNTRENjM3MTgwNkI4MTBGREM2MTQ0RkJBREQwRkQ4MUQ4NA
```

Permissions is not an issue, as server is running as root.

**Comment by adrianlzt** [comment]
Seems related with #245 and https://github.com/upspin/upspin/issues/173#issuecomment-281882636

**Comment by adg** [comment]
@adrianlzt why do you say that?

**Comment by adrianlzt** [comment]
Sorry, just looking some other issues and those two seems related because they handle disk storage. But I was supposing.

**Comment by adg** [comment]
Can you describe the steps you took to get into this state? What is the output from the previous invocations of `upspinserver`?

It doesn't look like there is enough in your `storage/` directory for those trees to exist.

I'd try just erasing the `upspin/server` directory and run `upspin setupserver` again.

**Comment by adrianlzt** [comment]
Thanks, working!
```
~/upspin $ upspin get adrianlzt@gmail.com/hello
Hello, Upspin
```

The previous time I tried to run ``setupserver`` it _half_ failed because my computer (the one running ``setupserver`` was not accepting LetsEncrypt CA). I added it and rerun the command.

Then was failing the server for the same reason. Added certs, restart and failed.
