### ISSUE TITLE
Invalid DNS record name in Linode

### ISSUE THREAD

**Issue by tarcisio** [upspin/upspin#248]
Hello,

I can't create the DNS record required by domain validation.
Linode's control panel throw an error "invalid name".

What version of Upspin are you using?
I use the "go get -u upspin.io/cmd/..." command today.

What operating system and processor architecture are you using?
Linux Ubuntu 16.04.2 LTS Kernel 4.8.6-x86_64 GNU/Linux

What did you do?
I was trying to setup my own domain (https://upspin.io/doc/server_setup.md)

What did you expect to see?
A valid dns record name

What did you see instead?
A record name that is impossible to create

`
upspin@server:~$ upspin setupdomain -domain=example.com

Domain configuration and keys for the user
        upspin@example.com
were generated and placed under the directory:
        /home/upspin/upspin/deploy/example.com
If you lose the keys you can re-create them by running this command
        upspin keygen -where /home/upspin/upspin/deploy/example.com -secretseed xxxxx-nadut
Write this command down and store it in a secure, private place.
Do not share your private key or this command with anyone.

To prove that tarcisio@domain.com is the owner of example.com,
add the following record to example.com's DNS zone:

        NAME    TYPE    TTL     DATA
        @       TXT     15m     upspin:6fbf4defc68013xxxxx

Once the DNS change propagates the key server will use the TXT record to verify
that tarcisio@domain.com is authorized to register users under example.com.

After that, the next step is to run 'upspin setupstorage'.

`

**Comment by adg** [comment]
@tarcisio is this because they say `@` is an invalid character?

**Comment by tarcisio** [comment]
@adg 

the exact message is:

> Name contains invalid characters.
> You have entered an invalid record name.

**Comment by adg** [comment]
Right, so basically the `@` is a convention that some registrars use to mean "no sub-domain". Try leaving that field blank?

I think this change to the docs will help address this: https://upspin-review.googlesource.com/c/7978/

**Comment by tarcisio** [comment]
@adg It works!

Thank you!
