### ISSUE TITLE
key/server: Appears to Allow Overriding Keys without Authorization

### ISSUE THREAD

**Issue by DeedleFake** [upspin/upspin#249]
Adapted from a comment in #234. To make sure that I cover all the details of what I did in what order, I'm just going to explain everything that I did.

I started experimenting with upspin earlier in the day. I followed the `Signing up a new user` guide until the `Creating your Upspin directory`, at which point I switched to the `Setting up upspinserver`. I followed that guide, skipping the `Set up the Google Cloud Storage service`, until the `Test connectivity` section, at which point I ran into a number of issues involving acme and Traefik, which I was trying to run the server behind.

One thing to note is that while I was signing up the user, I accidentally used the wrong server address, forgetting to put the `upspin` subdomain on it that I decided to use. After that, I always used the correct address.

By the time I got it working, I had switched to another machine and didn't have easy access to the keys on the original machine. I installed the upspin commands on the new machine, and then ran the following series of commands:

    $ upspin signup -server=<server> <username> # This partially worked, and then failed saying that user already had a key on the key server, which is what I expected.
    $ upspin keygen
    $ upspin user | upspin user -put # This is the weird one.
    $ upspin setupdomain -domain=<domain>
    $ upspin setupserver -domain=deedlefake.com -host=upspin.deedlefake.com

At this point, I gained access to the server, despite not using the key I had generated in the first place. The key server simply allowed me to overwrite its key with the newly generated one.

**Comment by DeedleFake** [comment]
And switching back to the original machine, I am once again able to run `upspin user | upspin user -put` and override the keys on the key server. It says

> upspin: user: local configuration differs from public record in key server:
> public key in configuration does not match key server

but then it overwrites them anyways, giving me full control over the account.

**Comment by n2vi** [comment]
You, sir, have uncovered the first---and an extremely serious---security bug.  We're making T-shirts and you will get the very first one; thank you so very much!

Initial fix is checked in.  We want to think a bit more about a more thorough fix and test before we make the broader announcement for people to patch.

Sorry for the delay responding.   I was helping with some of the other security excitement of the week until a few minutes ago.

**Comment by n2vi** [comment]
DeedleFake, as far as I know we've never met.  If you'll contact me offline at grosse@gmail.com, I'd like to coordinate with you about a broader security announcement of your finding and the patch.  But also fine if you prefer to skip it.
