### ISSUE TITLE
keys: transient error

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#251]
This transient error has been seen at least twice, once by me. Anonymized here.

$ upspin info XXX
upspin: info: dir/remote.Glob("remote,upspin.XXX:443"): I/O error:
        rpc.Invoke: 401 Unauthorized: rpc.SessionForRequest: I/O error:
        user XXX@XXX:
        rpc.PublicUserKeyService:
        key/usercache.Lookup:
        key/remote.Lookup("remote,key.upspin.io:443"):
        rpc.Invoke: 401 Unauthorized: rpc.SessionForRequest: permission denied:
        user not authenticated

$ upspin ls XXX
<works fine>

$ upspin info XXX
<works fine>

**Comment by swetland** [comment]
Saw this one again a couple hours ago today, but it did not happen when I poked the server again just now.

**Comment by edpin** [comment]
I've seen this multiple times. I suspect it has to do with the logic in rpc/client.Invoke. There's a retry loop there that I want to investigate more closely but haven't gotten around to doing yet.

Tentatively assigning to me for further investigation.

**Comment by robpike** [comment]
I saw it once today, making about 4 times total for me. I've been doing upspin shell a lot lately for irrelevant reasons, and it may be relevant that I think each time the error occurred it was the first interaction in the shell session, and it never recurred in each session.

**Comment by edpin** [comment]
I have a fix for one class of errors. It might be the bulk of what we're seeing:

https://upspin-review.googlesource.com/c/8080/

**Comment by edpin** [comment]
I think that CL fixed it. Re-open if you see it again please.
