### ISSUE TITLE
Docs for adding / enabling new users (creating root?)

### ISSUE THREAD

**Issue by nicpottier** [upspin/upspin#257]
What version of Upspin are you using?
f6ffb42  

What operating system and processor architecture are you using?
ubuntu 16.04 / amd64

What did you do?
Followed instructions to set up non google backed Ubuntu server here:
  https://upspin.io/doc/server_setup_ubuntu.md

Can do a hello world put/get with my own user. No problems there.
Edited `server/Writers` to add others in my organization (one per line), restarted server.
Had new user register, set dir and storage to our upspin host, all good.

However, when user tries to ls their root they get:
```
upspin ls foo@bar.com/
upspin: ls: client.Lookup: item does not exist:
dir/remote.Lookup("remote,upspin.bar.com:443"):
dir/server/tree.Lookup:
user foo@bar.com: dir/server/tree.LogIndex.Root: no root for user
```

Guessing there is a step I am missing to create the user's root? Poking around all over the place and I'm missing what that might be.

What did you expect to see?
User being able to use upspin server.

What did you see instead?
Error above.

**Comment by nicpottier** [comment]
Thought maybe this would work but no dice either.. 
```
% upspin mkdir foo@bar.com/
upspin: mkdir: client.MakeDirectory: permission denied:
dir/remote.Put("remote,upspin.bar.com:443"):
user foo@bar.com: serverutil/perm.Put: user not authorized
```

**Comment by rubiojr** [comment]
@nicpottier had that problem yesterday. Editing the server/Writers file won't work, I had to use `upspin setupwriters` IIRC.

**Comment by nicpottier** [comment]
@rubiojr Thank you! that did it.. don't know how I missed that command, have been looking everywhere.

**Comment by fawick** [comment]
I ran into a similar problem two nights ago (#235). There is a change in review that adds more documentation: https://upspin-review.googlesource.com/c/7984/

**Comment by nicpottier** [comment]
Thanks, that would have done it! Didn't think to look at PRs on googlesource.. hope things move to Github at some point.
