### ISSUE TITLE
License Nit

### ISSUE THREAD

**Issue by scottstephens** [upspin/upspin#258]
The license is mostly BSD 3-clause, except it replaces "the copyright holder" in the third clause with "Google Inc." The copyright notice at the top specifies that it's "Copyright (c) 2016 The Upspin Authors." 

I think you may want to switch the third clause to the standard, since it seems you accept outside contributors and do not require copyright assignment. (The contributor license agreement, though it grants liberal rights to Google, does not assign the copyright to Google.)

**Comment by adg** [comment]
Hi! Thanks for filing this issue. I've run this by our lawyers (specialists in open source licensing) and they believe it is fine as-is. I'm inclined to trust their judgment. Thanks again.

**Comment by sprstnd** [comment]
I'd like to speak with these lawyers on the reasoning behind the use of such wording. How does the CLA play into this decision? How would I contact them directly?

Little things like choice of license and CLA cripple projects. I'd expect your contribution numbers to be in the hundreds.
