### ISSUE TITLE
implementing upspin.io/cloud/storage.Storage with database/sql.DB

### ISSUE THREAD

**Issue by fawick** [upspin/upspin#259]
The package comment for upspin.io/cloud/storage states 

> Package storage implements a low-level interface for storing blobs in stable storage such as a database.

As an experiment, I would like to take this literally and consider implementing `storage.Storage` based on `database/sql.DB` as package `upspin.io/cloud/sqldb`.
 
- Is this something that would be interesting and useful for the Upspin project?
- Is there any work ongoing already? IIRC camlistore did something similar with sqlite for the indexer. 

My initial raw idea is to use a very naive single table with the two columns, one for the ref and one for the []byte. I expect one major challenge to be how to define a sensible limit for the size of second column.  `upspin.io/upspin.BlockSize` might be good start but since that constant is not a hard limit but can be overruled by the clients, it might not be good choice for the SQL column width after all. SQLite has the BLOB type which might work nicely. In general, I guess at lease `CREATE TABLE` needs to be made driver-specific in a switch-statement over `driverName`. 

The call to `store/server.New` (and eventually `sqldb.storageImpl.Dial`) would take the parameters `"backend=SQL"`, `"driverName=<...>`, and `dataSource=<...>`. The values `driverName` and `dataSource` would be used as parameters for the call to `sql.Open`. 

I reckon I can implement the interface methods `Put`, `Download` and `Delete` of `storage.Storage` in a very straight-forward fashion as `INSERT INTO`, `SELECT-FROM-WHERE`, or `DELETE` respectively.

**Comment by adg** [comment]
We actually did this at one point, because we wanted to use Cloud SQL for storing DirServer data. In the end we realized that with such a simple Get/Put/Delete interface we were getting none of the advantages of an SQL database but with all of the drawbacks.

In Camlistore it makes sense to use SQL for the indexer because they actually use SQL indexes and queries.

So, yes, it's possible to do what you suggest, but the question is: why do you want to do it?

**Comment by fawick** [comment]
I can see the point of pulling in all SQL drawbacks. 
My reason for doing it simply is that I want to become more familiar with the Upspin codebase and the idea above seemed doable enough in terms of coming up with something that I could hand in for review and getting feedback.

To be honest I feel a bit overwhelmed and scared by diving right in and starting with something as complicated as a web-based storage hoster (S3, B2 etc.), although I agree that coming up with a `storage.Storage` for these is more useful for the Upspin community in general.

**Comment by fawick** [comment]
Given that the Upspin project team has already implemented, evaluated, and scrapped the idea, I abandon it and close the issue. No need to reinvent the square wheel twice.
