### ISSUE TITLE
cmd/upspin: don't require gcloud command-line tool to set up gcp servers

### ISSUE THREAD

**Issue by broady** [upspin/upspin#261]
The [server setup](https://upspin.io/doc/server_setup.md) instructions require the use of the gcloud SDK.

All of these operations can be done from cmd/upspin. To create a service account, you'll need a shell project with the IAM API enabled.

Have people go through an OAuth flow (similar to "gcloud auth login"), make sure the target project has the storage_api API enabled (might want to prompt people if it isn't already enabled).

One downside is that you need to hardcode the client_id and client_secret into cmd/upspin (gcloud also has this for "gcloud auth login"), but it'd help ease installation.

**Comment by robpike** [comment]
Anything that makes installation easier and less error-prone is fine by me.

**Comment by robpike** [comment]
This is now possible. Closing.

**Comment by adg** [comment]
Huh? Where?

**Comment by robpike** [comment]
Apologies, misread the issue.

**Comment by robpike** [comment]
How about now?

**Comment by adg** [comment]
Really this should be a feature of upspin-setupstorage-gcp, in the gcp repo. Maybe we should close this and open an issue in that repo.

**Comment by adg** [comment]
cc @edpin

**Comment by adg** [comment]
upspin-ui makes this somewhat redundant.
