### ISSUE TITLE
valid: valid.User should fail for "all@upspin.io"

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#262]
Since that will never be a valid user name, we might as well reject it early to prevent that from being misused (for example, if a system automatically appends user names to a Writers file and someone tricks it into adding "all@upspin.io".

Easy to handle, but I want to make sure no one can find a reason not to.

**Comment by robpike** [comment]
The trick is to separate when it's invalid (a user adding it to a file) and valid (an entry already present in the parsed Access list).

**Comment by edpin** [comment]
Yes, but valid is only used in parsing user input. It's not called when parsing already validated entries. In your second scenario, we would call user.Parse to check it, but not valid.User. (There might be corner cases, but we should fix them if they do exist).

**Comment by robpike** [comment]
I suggest you try it and see what breaks.
