### ISSUE TITLE
cloud/https: suppress HTTP log messages unless -log=debug

### ISSUE THREAD

**Issue by swetland** [upspin/upspin#263]
I'm seeing this sort of thing in my server logs and am not sure if it's expected noise, actionable, or what...

Feb 23 07:59:22 debian upspinserver[16395]: 2017/02/23 07:59:22 http: TLS handshake error from 127.0.0.1:54820: acme/autocert: missing server name
Feb 23 10:05:13 debian upspinserver[16395]: 2017/02/23 10:05:13 http: TLS handshake error from 127.0.0.1:54822: acme/autocert: missing server name
Feb 23 10:59:42 debian upspinserver[16395]: 2017/02/23 10:59:42 http: TLS handshake error from 127.0.0.1:54824: acme/autocert: missing server name
Feb 23 12:14:20 debian upspinserver[16395]: 2017/02/23 12:14:20 http: TLS handshake error from 127.0.0.1:54826: acme/autocert: missing server name
Feb 23 12:16:25 debian upspinserver[16395]: 2017/02/23 12:16:25 http: TLS handshake error from 127.0.0.1:54828: acme/autocert: missing server name
Feb 23 21:57:26 debian upspinserver[16395]: 2017/02/23 21:57:26 http: TLS handshake error from 127.0.0.1:54856: acme/autocert: missing server name
Feb 24 01:20:05 debian upspinserver[16395]: 2017/02/24 01:20:05 http: TLS handshake error from 127.0.0.1:54866: EOF
Feb 24 01:20:06 debian upspinserver[16395]: 2017/02/24 01:20:06 http: TLS handshake error from 127.0.0.1:54868: tls: unsupported SSLv2 handshake received
Feb 24 01:20:06 debian upspinserver[16395]: 2017/02/24 01:20:06 http: TLS handshake error from 127.0.0.1:54870: tls: client offered an unsupported, maximum protocol version of 300
Feb 24 01:20:06 debian upspinserver[16395]: 2017/02/24 01:20:06 http: TLS handshake error from 127.0.0.1:54872: 400 urn:acme:error:malformed: Issuance for IP addresses not supported
Feb 24 01:20:06 debian upspinserver[16395]: 2017/02/24 01:20:06 http: TLS handshake error from 127.0.0.1:54878: acme/autocert: missing certificate
Feb 24 01:20:06 debian upspinserver[16395]: 2017/02/24 01:20:06 http: TLS handshake error from 127.0.0.1:54880: acme/autocert: missing certificate
Feb 24 01:20:06 debian upspinserver[16395]: 2017/02/24 01:20:06 http: TLS handshake error from 127.0.0.1:54882: acme/autocert: missing certificate
Feb 24 01:36:28 debian upspinserver[16395]: 2017/02/24 01:36:28 http: TLS handshake error from 127.0.0.1:54884: acme/autocert: missing server name
Feb 24 02:51:54 debian upspinserver[16395]: 2017/02/24 02:51:54 http: TLS handshake error from 127.0.0.1:54898: acme/autocert: missing server name
Feb 24 03:11:15 debian upspinserver[16395]: 2017/02/24 03:11:15 http: TLS handshake error from 127.0.0.1:54900: acme/autocert: missing server name
Feb 24 03:11:15 debian upspinserver[16395]: 2017/02/24 03:11:15 http: TLS handshake error from 127.0.0.1:54902: acme/autocert: missing server name
Feb 24 03:11:16 debian upspinserver[16395]: 2017/02/24 03:11:16 http: TLS handshake error from 127.0.0.1:54904: acme/autocert: missing server name
Feb 24 05:58:48 debian upspinserver[16395]: 2017/02/24 05:58:48 http: TLS handshake error from 127.0.0.1:54936: acme/autocert: missing server name
Feb 24 11:09:41 debian upspinserver[16395]: 2017/02/24 11:09:41 http: TLS handshake error from 127.0.0.1:54950: 400 urn:acme:error:badNonce: JWS has invalid anti-replay nonce d-Eb4uC6oojAZgKWjWyWUK_ZJe61k-IsGKH4tMYaN0Q
Feb 24 11:31:27 debian upspinserver[16395]: 2017/02/24 11:31:27 http: TLS handshake error from 127.0.0.1:54954: acme/autocert: missing server name
Feb 24 16:42:28 debian upspinserver[16395]: 2017/02/24 16:42:28 http: TLS handshake error from 127.0.0.1:54956: acme/autocert: missing server name

Setup is a debian 8 image on linode, configured per the "install on ubuntu" instructions (systemd + xinetd).

**Comment by adg** [comment]
These are benign errors, generated when a client attempts a TLS connection without knowing the server name. These are likely bots of some kind, not actual clients.

We should suppress these kinds of HTTP errors except when `-log=debug` is set. It's possible to configure an `http.Server`'s `ErrorLog` field, and we should do that in the `upspin.io/cloud/https` package.
