### ISSUE TITLE
cmd/upspin: unhelpful error when mistyping a subcommand

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#264]
On a brand new machine, a typo such as `s/signup/singup/` causes an error related to missing `config`:

```
$ upspin singup -h
upspin: singup: config.FromFile: item does not exist: open /Users/jacekm/upspin/config: no such file or directory
$
```

It would be more helpful if the error said something like "singup: invalid command" or if it acted as if user ran `upspin -h`.

**Comment by robpike** [comment]
This is just a question of the order in which things are done. I think I can take care of it easily.
