### ISSUE TITLE
cmd/upspin: should there be an FTP like client for managing stores?

### ISSUE THREAD

**Issue by nicpottier** [upspin/upspin#265]
`upspin shell` is almost this but I'm not sure it is meant to be. So putting this out there to be shot down or discussed. This is the kind of thing I might bite off and try to implement.

But anyways, as I've been playing with upspin, I would have really liked an ftp like interface. A hypothetical session below:

```
% upspin connect foo@bar.com

foo@bar.com/> ls
Permission Denied

foo@bar.com/> cd public

foo@bar.com/public> ls
Access
shared.doc
logo.jpg

foo@bar.com/public> lpwd
/Users/foo/Downloads

foo@bar.com/public> lls
new_logo.jpg

foo@bar.com/public> put new_logo.jpg
32kb transferred in .5 secs.

foo@bar.com/public> ls
Access
shared.doc
logo.jpg
new_logo.jpg

foo@bar.com/public> get logo.jpg
62kb transferred in .3 secs.

foo@bar.com/public> mkdir assets

foo@bar.com/public> cd assets

foo@bar.com/public/assets> connect jane@bar.com/public

jane@bar.com/public>
```

etc...

Does this make any sense to exist in the upspin world?

**Comment by awly** [comment]
IMO upspinfs looks a lot more convenient because you may use any tools you like. As opposed to implementing a limited set in the shell.

**Comment by swetland** [comment]
I think the advantage for a ftp-style client is when dealing with higher latency, lower bandwidth situations, especially with larger files, where tools that interact with the filesystem tend to assume local and fast and don't give good feedback for more sluggish transports.

**Comment by fawick** [comment]
It is not hard to fully rewrite the FTP example to using chdir/cp/rm with an `upspinfs`-mount. But I see a usecase for a client that distinguishes between local and "Upspin cloud" might be beneficial when FUSE is not available, e.g. on Windows.

**Comment by nicpottier** [comment]
Is there a quick start of any kind for the fusefs support? I played around
with it briefly but couldn't get it working on OSX, undoubtedly because I
installed the wrong fusefs driver or something.

Though I do agree that mounting virtual filesystems is great, I'm not sure
that addresses all the same use cases. Then again it may not be a use case
upspin sees itself solving.

**Comment by robpike** [comment]
Make sure you have 3.5 or later of OS X FUSE from https://osxfuse.github.io/. Earlier versions had problems.

Your point that the setup instructions are lacking is on point.

**Comment by adg** [comment]
It would actually be really easy to write this as a stand-alone tool. It need not be part of the `upspin` command. I suggest you take a crack at it and see if it's useful for you. It needn't be part of the core distribution.

**Comment by adg** [comment]
Another way of going about this would be to add `cd` and relative path names to `upspin shell`. That would be hard to design but could do the job well.

**Comment by nicpottier** [comment]
Thanks may just do that.

**Comment by robpike** [comment]
I prefer not to rush into making upspin shell nicer to use.  See also #213.

It's an administration and debugging tool, but as soon as we start making it nice to use, it becomes a honeypot for features that promote it as a permanent shell-like tool. I want to discourage that.

**Comment by nicpottier** [comment]
Just to be clear was saying I might bite off writing a standalone client, not jamming `cd` into `shell`.

**Comment by adg** [comment]
While I encourage anyone to develop new and better ways of interacting with the Upspin name space, I don't think this specific issue needs to be resolved by the core project. The upspinfs, upspin shell, and the browser in exp, cover many of the potential use cases.
