### ISSUE TITLE
cmd/upspin: snapshot command should create snapshot user

### ISSUE THREAD

**Issue by adg** [upspin/upspin#269]
The `upspin snapshot` command creates a user root if it doesn't exist. 

I think it should also register the snapshot user with the key server if it doesn't exist.

**Comment by fawick** [comment]
Does this imply that the [creation of the snapshot user in `keyserver`](https://github.com/upspin/upspin/blob/master/cmd/keyserver/signup.go#L246) will be removed? 

I just stumbled over the fact that `keyserver` does not add a store or dir for the snapshot user.

**Comment by adg** [comment]
@fawick that seems like the right thing to do, yeah.
