### ISSUE TITLE
cmd/upspin: setupstorage: account for alternate storage backends

### ISSUE THREAD

**Issue by andybons** [upspin/upspin#270]
With reviews coming in for S3 and B2 coming down the pike, the `setupstorage` command will need to make less assumptions and allow for specifying the specific backend the user wants.

/cc @fawick

**Comment by fawick** [comment]
Agreed. We need to add the package imports to `/store/server/server.go` and more tests for `server.New` too.

```go
import (
[...]
        _ "upspin.io/cloud/storage/amazons3"
        _ "upspin.io/cloud/storage/b2cs"
)
```

**Comment by swetland** [comment]
Should setupstorage be required for the local disk storage backend as well?  Right now, I believe local disk is the default, but I recall @robpike mentioning wanting to emphasize the dangers of non-backed-up local storage.

Perhaps requiring the user to explicitly say "setupstorage --localdisk" or whatnot (and spit out a brief warning about dangers of data loss in absence of replication or backups) would be worthwhile.

**Comment by robpike** [comment]
Let's spend some time figuring out how to minimize external dependencies as new implementations come along. I don't want the main upspin repository to contain the entire open source world. This will take some planning and perhaps a way to remote a Storage implementation, the way we can remote a DirServer or StoreServer today.

**Comment by fawick** [comment]
How about we put the S3 and B2 implementations in for the time being so users have an alternative to GCS and local disk. Both only depend on a single further GitHub-repo each, and Upspin is not vendoring dependencies at the moment.  We can still draw the (temporary) line in the sand for any further `Storage`s right after that.

I expect Upspin to gain more traction with these storage options, bringing in new users and contributors.
 
The way S3 and B2 are storing the refs is probably not going to be affected by refactoring and remoting the `Storage` implementations, so any stored data remains upwards-compatible. And the `upspinserver` executables needs to be replaced in the running instances, anyway, so there might as well be a (semi-)manual migration of the server config.

**Comment by adg** [comment]
> Let's spend some time figuring out how to minimize external dependencies

Worth mentioning is that the `upspin setupstorage` command links a bunch of the Google Cloud SDK into `cmd/upspin`. An extension of `setupstorage` to work with other platforms will further add to that dependency morass.

We should consider moving the server-setup related commands (`setupdomain`, `setupstorage`, `setupserver`, `setupwriters`) into a new command, `upspin-setup`.

**Comment by swetland** [comment]
It would definitely be nice to not have to download and build the rpc or support libraries for every possible backend (including not building the GCS stuff if not using GCS) if you're not using them.  Saves a bit on build time and binary size...

**Comment by adg** [comment]
The new plan:

- refactor `cmd/upspinserver` into a package `serverutil/upspinserver`,
- do the same for `cmd/upspin-setupstorage`,
- provide a new `cmd/upspinserver` that imports the on-disk storage implementation, and calls `serverutil/upspinserver.Main` to do the work,
- move `cloud/storage/gcp` to a new repository `gcp.upspin.io`,
- in the `gcp` repo, create a `cmd/upspinserver` and `cmd/upspin-setupstorage` that link in the Google Cloud storage implementation.

Then people who want to deploy servers that support Google Cloud Storage can execute
```
$ go get gcp.upspin.io/cmd/{upspin-setupstorage,upspinserver}
```
and get the right dependencies and resulting binaries.

For other cloud services, we'll create repositories for them, and they will contain parallel commands that link in the storage back ends for those services.

I will soon commit a series of changes that comprise the refactoring part of this task.

**Comment by robpike** [comment]
s/comprise/compose/

**Comment by robpike** [comment]
This is largely done, at least by example for GCP and AWS. Closing.
