### ISSUE TITLE
cmd/upspin: keygen should not clobber existing keys 

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#271]
Unless the -where flag is not the default value. Or perhaps only if -force is used. 

Even though it saves the old private key, it could be more careful to confirm with the user when key rotation is about to happen.

Helps prevent accidents.

**Comment by adg** [comment]
I think `-force` is probably the way to go, although it should have a different name. (`-rotate`?) @n2vi?

**Comment by edpin** [comment]
I think -rotate is a good idea. I'm sending a tentative CL. Please take a look:
https://upspin-review.googlesource.com/8201
