### ISSUE TITLE
cmd/upspin: keygen and rotate should attempt to match user keys

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#272]
When switching between users by copying keys or soft linking them, it might be possible for a secret2.upspinkey to end up with old keys from multiple users.

It would be nice to have the user name next to the key, if we happen to know it. In some cases it can be known by checking the default config file if one exists and double checking the public key with the keyserver.

This prevents a situation where I need to manually match an old key rotated by accident to one of my users.

**Comment by adg** [comment]
If #271 happens would this be necessary?

I'm still not sure how `upspin keygen` can reliably know who the user is.

**Comment by edpin** [comment]
It's possible to do some tricks with loading the config file if one is found. But it now seems less desirable and could possibly be confusing too. So, closing.
