### ISSUE TITLE
cmd/upspin: make keyserver configurable in signup

### ISSUE THREAD

**Issue by adrianlzt** [upspin/upspin#276]
https://github.com/upspin/upspin/blob/master/cmd/upspin/signup.go#L182

Will be great that it could be changed by param to use another keyserver.

**Comment by edpin** [comment]
I don't think we want to do this because if the user managed to override the keyserver field in an existing config file, then the signup URL could be wrong. There's no guarantee that other keyservers (if any were to exist) would implement this signup flow.

**Comment by adrianlzt** [comment]
I have found this trying to create a test environment, with my own key, dir and storage server.
Anyways, if the user modify the keyserver, after signup, it won't work neither.

**Comment by adg** [comment]
A reasonable feature request IMO.

**Comment by gbbr** [comment]
I have found myself also wanting to use this with a local instance of the `keyserver`. Mostly for development means and for learning about Upspin. Would it be possible to add this as a flag to `upspin signup`?

I am happy to commit to this work if there are no objections.

**Comment by adg** [comment]
@gbbr your help would be most appreciated!

**Comment by gbbr** [comment]
So, I've shyly created a reference implementation (probably lots of newbie mistakes there) to stimulate the discussion here.

Some things I don't like:
- The `-insecure` flag on the `signup` sub-command. I'd love to avoid it.
- The automatic creation of rpc clients with `NoSecurity` level when the dialled address is local. What if somebody runs a TLS server locally and is forced to use `NoSecurity` on it? It would break.

I'm not sure how to tackle this and if the above are actually issues. It seems that all servers (key, dir, store) have support for running without TLS, but the upspin command itself has a hard time dealing with it. With the current CL I was able to set up all servers locally and interact with them (put, get, list).
