### ISSUE TITLE
cmd/keyserver: use YAML for mail configuration file

### ISSUE THREAD

**Issue by adrianlzt** [upspin/upspin#279]
``parseMailConfig`` read three lines from the given file, assuming the first one is the key, second one userName and third password.

Maybe will be better to change that file to a YAML and parse using the ``valsFromYAML`` [function](https://github.com/upspin/upspin/blob/master/config/initconfig.go#L242).

**Comment by adg** [comment]
Thanks for the suggestion, but how is that an improvement?

**Comment by adrianlzt** [comment]
Seems a little bit strange that the format of a file is the order of the lines.
In the rest of configuration files you use key:value, that is readable, nor this one.

**Comment by adg** [comment]
I suppose this would be a fine change. It's hard for me to get excited about it though.

**Comment by adg** [comment]
The mail config is actually just one line now (a sendgrid token). Not worth its weight in YAML.
