### ISSUE TITLE
cmd/upspin: document that setupserver is not for cluster deployments

### ISSUE THREAD

**Issue by adrianlzt** [upspin/upspin#281]
If we generate a config with ``setupdomain`` using the flag ``-cluster``, below the directory named ``$domain`` two dirs are created, ``dirserver`` and ``storeserver``:
```
└── localhost
    ├── dirserver
    │   ├── config
    │   ├── public.upspinkey
    │   └── secret.upspinkey
    └── storeserver
        ├── config
        ├── public.upspinkey
        └── secret.upspinkey
```

If we continue the process executing ``setupserver``, help says:
```
  -host name
    	host name of upspinserver (empty implies the cluster dir.domain and store.domain)
```

But ``-host`` [could not be empty](https://github.com/upspin/upspin/blob/6f7b2d79bd286388ae31c95898f91dc4eb668024/cmd/upspin/setupserver.go#L49). And setting ``-host`` to ``$domain`` fails because it looks conf files in ``localhost/serverconfig.json``.

**Comment by adg** [comment]
I can see how this is confusing for you.

`upspin setupserver` is for configuring an `upspinserver`. If you are deploying separate `dirserver` and `storeserver` instances then you needn't use `setupserver`. 

What instructions are you following for configuring a cluster deployment?

**Comment by adrianlzt** [comment]
I was reading the code and trying to understand how all pieces works.

**Comment by adg** [comment]
We'll need to clarify in the command documentation that `setupserver` is only for configuring `upspinserver` instances.

**Comment by adg** [comment]
Rolling this into issue #244
