### ISSUE TITLE
doc: document that Group files may only be modified by the owner

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#283]
In a recent situation, a permission denied error happened when I tried to update a Group file that granted me write rights to it.

Contents of `other@example.com/Access`:
```
*:aGroup
...
```
And contents of `other@example.com/Group/aGroup`:
```
me@example.com
...
```

It may be because updating a Group file causes the Access that depends on it to be revoked while it's happening. Need to investigate further.

**Comment by n2vi** [comment]
access/access.go:607 enforces the rule, which I think is sound, that only the owner can write Access and Group files.

**Comment by adg** [comment]
It's even in [the documentation](https://upspin.io/doc/access_control.md):

> Access control files are named exactly Access. Like Group files, they are plain text files and are stored in the owner’s Upspin tree, only the owner may write them,

Makes total sense, too.

**Comment by edpin** [comment]
The documentation says this of _Group_ files:

```
Group files are always readable and writable by the owner, but otherwise act as regular
items within the Upspin name space as far as client I/O is concerned.
```

It's not clear only owners can write Group files from that sentence. However, that's what the code implies, yes.

**Comment by adg** [comment]
@edpin quite right. I think the behavior is correct, but the docs are not. I updated this issue to track the doc change.

**Comment by edpin** [comment]
I made the doc change already. :-)

**Comment by adg** [comment]
Great!
