### ISSUE TITLE
doc: Explain briefly key advantage versus existing solutions

### ISSUE THREAD

**Issue by wernight** [upspin/upspin#287]
On https://github.com/upspin/upspin/README or on https://upspin.io/doc/overview.md it should quickly explain:

 - Where is the data stored? (for example reading the example of Facebook to Twitter, what if you host your data on your machine, then you Facebook would need to proxy and self-host a copy of your data; so please briefly address this issue there)
 - How is that different from Drive/DropBox/Photos/...? All these cloud solution have CLI interfaces and a URL can be seen as a unique name to a user's resource (case of Google Photos for example).

**Comment by robpike** [comment]
I believe this is covered by #177.
