### ISSUE TITLE
cmd/upspin: Usage string could be more precise

### ISSUE THREAD

**Issue by griesemer** [upspin/upspin#288]
`upspin signup -help` produces
```
upspin [-config=<file>] signup [flags] <username>
```
leaving the (naive) impression that only a username (e-mail address) needs to be provided. I've read the documents elsewhere which indicate that a `-dir` and `-store` argument are needed, but from the command help one might then conclude (and I did) that upspin would choose some sensible defaults. The error is clear again:
```
upspin: signup: -dir and -store must both be provided
```
Suggestion: Make the -dir and -store argument explicit in the Usage string; they are not optional.

**Comment by clebs** [comment]
Hi!
I am a first timer here and I would like to contribute with this task as it looks quite easy and I get the chance to get familiar with the upspin contribution process, which is not fully clear to me right now.

I do not know if this issue is accepted nor what the usage should look like, but I am happy to discuss about it!

**Comment by edpin** [comment]
Hi @clebs. Most certainly you can. Please assign this to yourself and write a short proposal here of how you plan on fixing it. @griesemer made a suggestion already. Is there anything else? 

Since this is a small task, after you make it public how you plan on fixing it, you can submit a tentative change list  with it. (For larger issues we encourage more discussion here before a CL is proposed).

Thanks!

**Comment by edpin** [comment]
Please also see #210.

**Comment by clebs** [comment]
Hi @edpin, thanks for the swift response!
I have been reading the docs and found the following:

> Here is the first step. Run this shell command, substituting your email address and directory and store servers:
> `$ upspin signup -dir=dir.example.com -store=store.example.com you@gmail.com`
> Or, if the directory and store servers run on the same host, specify that host name with the -server flag:
> `$ upspin signup -server=upspin.example.com you@gmail.com`

So either dir+store flags are given or -server flag. My proposal (based on [docopt](http://docopt.org/)) would be:
`upspin [-config=<file>] signup (-dir=<dir server> -store=<store server> | -server=<dir and store host>) [flags] <username>`

Also the point in #210 is pretty valid and those flags could become optional in the future, it would be enough to replace the `()` with `[]` in the help message.

Regarding the assignment of the issue, I am afraid I am not able to assign it to myself as I do not have permission... Could you assign it to me?

Thank you!

**Comment by adg** [comment]
> My proposal (based on docopt) would be:
upspin [-config=<file>] signup (-dir=<dir server> -store=<store server> | -server=<dir and store host>) [flags] <username>

I'd prefer to show two separate usage lines:

```
upspin [-config=<file>] signup -dir=<dir server> -store=<store server> [flags] <username>
upspin [-config=<file>] signup -server=<dir and store host> [flags] <username>
```

To me that's a lot clearer than using my brain to parse the parents and pipe.

**Comment by edpin** [comment]
+1 to what @adg suggested.

I haven't figured out why @clebs is not assignable to this by me. Maybe @adg knows why?

**Comment by adg** [comment]
@edpin because they are not a member of the upspin GitHub organization. I have sent them an invitation to join a special 'upspin/assignees' team that we can use for this purpose. That's what we do for Go, at any rate.

**Comment by clebs** [comment]
Hi,

I just joined the organisation, thanks for the invite!

Indeed, a two line usage is more user friendly that the one with the OR. I will submit a change with it.

**Comment by clebs** [comment]
Hi @edpin,

just submitted the change here: https://upspin-review.googlesource.com/c/8241

Please let me know if I did something wrong, it is the first time I use this code review tool.

Thanks!
