### ISSUE TITLE
dirserver per directory/file instead of per user 

### ISSUE THREAD

**Issue by Burning-Daylight** [upspin/upspin#294]
At the moment given user can only use one dirserver and plans for dirserver mirrors are mentioned in the docs. It might be useful if a user could use multiple dirservers. It could work like this: each folder/file has a dirserver associated with it, when a new folder/file is created, it inherits the dirserver from its parent. However when a user starts to access a dir/file from a different location via dirserverB, dirserverB claims responsibility for the accessed dir/file and if dirserverA grants it (doesn't need it atm) - dirserverB becomes the primary source of information on the given file/dir. Responsible servers can be geo-distributed and change dynamically upon demand. This could also be a way to implement the 'offline' usage. If the localhost@dirserver is responsible for the current file/dir(was responsible before the network partitioning), then it is possible to modify the file/dir, because any other dirserver will not be able to claim reponsibility for the dir/file since localhost@dirserver will not be able to give it up.

**Comment by awly** [comment]
I'm actually (slowly) working on something similar to what you describe.
It's a multiplexing DirServer, that matches all RPCs based on path prefix and forwards them to the appropriate desitnation DirServer.

Haven't quite figured out the security model for that yet however. It would be quite burdensome to manually create user accounts for each node and manage their permissions towards each other.

**Comment by adg** [comment]
Why not use multiple trees serviced by multiple DirServers and then use
links to tie them together?

**Comment by awly** [comment]
Hmm, I didn't about links.
You would still need a root upspinserver and all leaf upspinservers with separate users and Writers containing the root one? Or would they only need to add actual owner user account to Writers?

**Comment by adg** [comment]
You mean the store Writers file? Yeah you'd need to put all the accounts in there, I think.

**Comment by Burning-Daylight** [comment]
Can you change a tree owner dynamically in this case? Do I get it right: you suggest to overlay trees (using links) from multiple (static?) users, one DirServer per user.

**Comment by edpin** [comment]
You can't change a tree owner once it's established, but you can grant full rights to your other users.

Or, you could setup all your users to have the same set of keys.

One easy way to do what adg@ describes is to create me@example.com, me+subtree1@example.com, me+subtree2@example.com, etc. All can be served by their own set of servers. Then me@example.com would have links to the other trees somewhere, possibly the root.

The best solution depends on exactly what problem you're trying to solve.

**Comment by Burning-Daylight** [comment]
How would you transfer a tree (or a part of a tree) from DirServer@me+subtree1 to DirServer@me+subtree2.

**Comment by edpin** [comment]
@Burning-Daylight, what do you mean by transfer? Are you assuming you already wrote the bytes? In that case, you'd copy them to the new tree. That would be a fast operation since the blocks would not need to be copied. But if you want them copied to a new store server too, then you'd have to copy them. 

On the other hand, if you start out with this setup, there's nothing to transfer.

**Comment by Burning-Daylight** [comment]
@edpin thx, sounds good

**Comment by edpin** [comment]
Closing now. Re-open if necessary.
