### ISSUE TITLE
all: reduce external dependencies. 

### ISSUE THREAD

**Issue by adg** [upspin/upspin#296]
- First focus on removing dependencies from commands, then later think about moving code that has large dependencies to a separate repo.
- The `upspin` command is a great place to start. The [dependency graph](https://godoc.org/upspin.io/cmd/upspin?import-graph&hide=1) is illuminating.
  - [ ] `upspin.io/metrics` brings in a lot of Google Cloud dependencies that are irrelevant to `cmd/upspin`. The GCP metric saver should only be linked in by binaries that need it. (#295)
  - [ ] The `setupstorage` command also brings in Google Cloud deps; if we split this into a separate command then we can remove those deps from the common case.
- There are more thoughts but we ran out of time. Let's keep updating this issue.

cc @robpike @andybons

**Comment by adg** [comment]
Another setupstorage related issue: https://github.com/upspin/upspin/issues/270#issuecomment-282589021

**Comment by adg** [comment]
Now that we have moved all the cloud-related stuff to the `gcp.upspin.io` repository, the core repo now only has these external dependencies:

```
bazil.org/fuse
bazil.org/fuse/fs
bazil.org/fuse/fuseutil
github.com/golang/protobuf/proto
github.com/russross/blackfriday
github.com/shurcooL/sanitized_anchor_name
golang.org/x/crypto/acme
golang.org/x/crypto/acme/autocert
golang.org/x/crypto/hkdf
golang.org/x/net/context
golang.org/x/net/context/ctxhttp
golang.org/x/text/cases
golang.org/x/text/internal
golang.org/x/text/internal/tag
golang.org/x/text/language
golang.org/x/text/runes
golang.org/x/text/secure/bidirule
golang.org/x/text/secure/precis
golang.org/x/text/transform
golang.org/x/text/unicode/bidi
golang.org/x/text/unicode/norm
golang.org/x/text/width
gopkg.in/yaml.v2
```

**Comment by robpike** [comment]
W00T!
