### ISSUE TITLE
cmd/upspin: implement findUpspinBinaries for Windows

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#297]
It's only there for Unix now, which is mostly because I don't have a good way to test a Windows implementation. It's harder than on Unix because of things like .exe, but not by much.

The only problem caused by its absence is failure to report their existence in the upspin commands help messages, but that should still be addressed.

**Comment by fawick** [comment]
I can give it a shot.

Should I wait for https://upspin-review.googlesource.com/c/8104/ to be merged or I should I cherry-pick it now? Would that give me trouble with Gerrit when I load up my changes later?

**Comment by robpike** [comment]
Start when you like. It can't merge before 8104, but other than that all is well.
