### ISSUE TITLE
cmd/upspin: helper tool to pack/unpack user configuration

### ISSUE THREAD

**Issue by awly** [upspin/upspin#301]
For a (probably common) scenario of enabling access to your account on another machine, a user currently has to:
- copy `~/upspin/config` to new machine
- copy `~/.ssh/*.upspinkey` to new machine

It's covered at https://upspin.io/doc/usage_examples.md, but i propose to make it simpler.

```
user@host1 $ upspin pack-config
Configuration stored in upspin-config.tar.gz
user@host1 $ scp upspin-config.tar.gz user@host2:.
user@host2 $ upspin unpack-config upspin-config.tar.gz
Configuration applied
```

The main benefit is that unpack-config will handle directory creation, permissions and possible file conflicts (save user from accidentally overwriting another key pair).

I volunteer to implement it, as long as nobody objects to the idea.

**Comment by adg** [comment]
I'm a bit nervous about packing up people's private keys into a tarball. @n2vi ?

**Comment by awly** [comment]
It could also provide some basic encryption on top with a one-off user-specified passphrase.

The main theme is to prevent as much human error as possible when transferring keys around one's machines (messing up naming, sending over an insecure channel, having overly open permissions on keys, etc).

**Comment by adg** [comment]
If the tarball were encrypted with a pass phrase then that would actually make the feature quite useful, in that it would provide a secure way to sneakernet my keys somewhere else.

I'd like Eric to weigh in on this.

**Comment by n2vi** [comment]
I concur with adg@.   In other systems, people are known to shoot
themselves in the foot by exporting secrets.

Let's see how far we can get with packaging up config and such but
insisting that users retype the secretseed proquints.  That's something
they won't be tricked into doing;  they will know they are giving away
their secret and have long enough while typing to pause and reflect on
whether this is really what they intended.

**Comment by adg** [comment]
> Let's see how far we can get with packaging up config and such but
> insisting that users retype the secretseed proquints. 

I agree with the strategy.

If we generate keys from the proquints, all that's leftis their config file. The whole process is:

1. Copy `$HOME/upspin/config` on one machine to `$HOME/upspin/config` on another.
2. Run `upspin keygen -secretseed <proquint>`

(Perhaps that should be suggested as the best practice on the [Usage Examples page](https://upspin.io/doc/usage_examples.md)?)

**Comment by n2vi** [comment]
Yes, modulo resolving the issue of whether we should do something better
than having -secretseed on the command line.

**Comment by awly** [comment]
> If we generate keys from the proquints, all that's leftis their config file. The whole process is:
> Copy $HOME/upspin/config on one machine to $HOME/upspin/config on another.
> Run upspin keygen -secretseed <proquint>

This seems fine. And theoretically the config can be generated on the destination host, given just the username.
So it should be possible to make a different helper command (`upspin login`?) that takes username and the seed as input, and generates keys and the config.

I'm concerned about the usability aspect of this however. 
Some users (myself included) will only backup their keys and will miss/forget to write down the secret seed. It's not stressed enough in the docs. Keys are easy to back up after the fact, but the seed is gone with your scrollback/terminal window.
These users will fall back to copying their keys around.

Perhaps i'll make a packaging tool for my own personal use instead.

**Comment by adg** [comment]
> Some users (myself included) will only backup their keys and will miss/forget to write down the secret seed. It's not stressed enough in the docs.

That's a serious usability issue, then. Filed #307

**Comment by n2vi** [comment]
Note that the secret seed is in secret.upspinkey, so even if someone forgot to write it down or lost the piece of paper, they still can use our recommended approach.

**Comment by robpike** [comment]
Need to document that it is written there too, in case you missed it at keygen time.

**Comment by robpike** [comment]
Closing in favor of #307.
