### ISSUE TITLE
cmd/upspinfs: always show current user's tree in upspinfs root

### ISSUE THREAD

**Issue by adg** [upspin/upspin#302]
When you first mount upspinfs, the mount point has no files or directories. As you `cd` into various Upspin trees those directory entries are shown in the root. It would be more user-friendly if we always showed the current user's root in the upspinfs root.

What do you think @presotto ?

**Comment by derekchiang** [comment]
This makes 100% sense to me.  I'd go one step further and allow for a configurable option where you can specify the paths that you want to mount by default.  That way you can specify a list of friends's paths that you frequent.

**Comment by presotto** [comment]
You can do that just by running a shell script that is:

upspinfs <mtpt>&
ls -d <mtpt>/friend1 > /dev/null 2>&1 &
ls -d <mtpt>/friend2 > /dev/null 2>&1 &
...

Just as easy as putting some config file somewhere and more versatile.  I
added showing your home directory (and snapshot directory) to upspinfs
already.

**Comment by adg** [comment]
> I added showing your home directory (and snapshot directory) to upspinfs already.

Then this issue is resolved. We can open another issue about showing other stuff in the root at startup, if there's interest.
