### ISSUE TITLE
all: use config.Homedir() instead of $HOME

### ISSUE THREAD

**Issue by fawick** [upspin/upspin#303]
At the moment, some commands and the flags package rely on `os.Getenv("HOME")`, which is not set in a default Windows environment. So, if not specified otherwise with command-line flags, some of the used directories and files are relative to the current working directory on Windows. One example is the default value of the `-config` flag of `cmd/upspin`.

This should be replaced something like with `config.Homedir`

I identified the following occurences in 99d71574b2cd2e0cdde8ec6a2252afffdd32c4f9, there may be more.

- [ ] `cmd/cacheserver/main.go` for `cfgPath`, `letsPath`
- [ ] `cmd/upspin`, in the `kegen`, `setup(domain|storage|server|writers)`, and `signup` subcommands.
- [ ] `cmd/upspin-deploy`
- [x] `flags/flags.go` for `defaultCacheDir`, `defaultConfig`

**Comment by fawick** [comment]
The function `upspin.io/config.Homedir()` is not suited as replacement for `os.Getenv()` in flag initializations (often package variables), as it returns a string and an error.

I proposed a helper function `upspin.io/flags.JoinWithHome` similar to `filepath.Join` in  https://upspin-review.googlesource.com/c/8144/

I opted to not use `upspin.io/config.Homedir()` in that because I thought it be more expensive than  `os.Getenv`.

**Comment by robpike** [comment]
I believe though that config.Homedir is the right approach, but it is two-valued. We should add a second function in the config package (not a method on upspin.Config) that returns the home directory of the user and panics if it cannot be found. If there is no home directory nothing will work anyway.

```
// Home returns the home directory of the user, or panics if it cannot find one.
func Home() string { ... }
```

**Comment by fawick** [comment]
Okay, I'll update CL 8144.

**Comment by robpike** [comment]
Closed by 8144.
