### ISSUE TITLE
bind: show error if key server could not be reached

### ISSUE THREAD

**Issue by adrianlzt** [upspin/upspin#305]
[Currently](https://github.com/upspin/upspin/tree/6993c7ad61f054a0d8e44d921a23df51dfc2cb5e), if we ask for a user different from the one defined in our configuration file, and keyserver could not be reached, the response of upspin cmd is:
```
$ upspin ls other@gmail.com/
upspin: ls: client.Lookup:
	Client.DirServer:
	user other@gmail.com: bind.DirServerFor: no directory endpoints found
```

I suggest capturing the error generated by [``key.Lookup(userName)``](https://github.com/upspin/upspin/blob/6993c7ad61f054a0d8e44d921a23df51dfc2cb5e/bind/bind.go#L211) and return a connection error if it fails.

``key.Lookup(userName)`` will try, at first instance, to resolve directory server from the configuration file ([here](https://github.com/upspin/upspin/blob/6993c7ad61f054a0d8e44d921a23df51dfc2cb5e/key/usercache/cache.go#L81) and [here](https://github.com/upspin/upspin/blob/6993c7ad61f054a0d8e44d921a23df51dfc2cb5e/key/usercache/cache.go#L188)).
If the user asks for their own files, it will work without contacting with the keyserver, but if asks for another user, and keyserver is unavailable, it should return a connection error.

``bind.go`` [also adds](https://github.com/upspin/upspin/blob/6993c7ad61f054a0d8e44d921a23df51dfc2cb5e/bind/bind.go#L204) the dirServer defined in the config file to the ``endpoints`` slice if the queried user is the same defined in the config file. But that behavior is repeated by ``key.Lookup``, so I think it could be safely deleted.

**Comment by edpin** [comment]
I think @presotto should decide.

**Comment by adg** [comment]
> I suggest capturing the error generated by key.Lookup(userName) and return a connection error if it fails.

Agree that this is what should happen. The current error is bad, especially considering we have not implemented multiple dir servers and aren't sure how that might even work.

**Comment by presotto** [comment]
Fine by me.  If I ever get around to disconnected behaviour, I'll have to create a keyserver proxy anyways or nothing will work so this change won't break that. I'll go look at the CL again.
