### ISSUE TITLE
doc: stress the importance of remembering secret seeds

### ISSUE THREAD

**Issue by adg** [upspin/upspin#307]
@awly [commented](https://github.com/upspin/upspin/issues/301#issuecomment-284032442) that:

> Some users (myself included) will only backup their keys and will miss/forget to write down the secret seed. It's not stressed enough in the docs.

We should perhaps be over-the-top in prompting users to write these strings down.

**Comment by robpike** [comment]
Reopening as the correct followup to #301. Rather than automating the copying of keys, which is dangerous, we should push harder on the idea of recreating them from proquints.

See also #355
