### ISSUE TITLE
cmd/upspin: need an easy way to wipe an upspinserver and start fresh

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#309]
If one wants to start from scratch again, one needs to manually wipe all the store data and the dirserver logs directory before re-deploying.

There should be an easy mechanism for that, perhaps an upspin-wipe subcommand.

**Comment by robpike** [comment]
We should not automate wiping all a user's data. Too easy to get wrong or invoke accidentally.

Better to give the recipe, warn like mad, and let users take responsibility for their own demise.

**Comment by n2vi** [comment]
It is said Dave is drafting such a recipe based on his recent experience,
and I will test that out as soon as ready.

**Comment by adg** [comment]
Dave submitted a change to `doc/server_setup.md`.
