### ISSUE TITLE
cmd/upspinserver: Current auth mechanism does not work behind Apache with mod_proxy

### ISSUE THREAD

**Issue by SebastianZaha** [upspin/upspin#311]
While attempting to run upspinserver on a machine that already runs an Apache web server, behind mod_proxy, I am getting the following in all rpc calls:

```        
rpc.Invoke: 401 Unauthorized: rpc.SessionForRequest: invalid operation:
invalid auth request in header
```

I read the code handling the "Upspin-Auth-Request" header, and I think the issue is explained by the assumptions below. Apologies if this proves to be incorrect, I am willing to further inspect & debug if this first analysis is wrong.

The mentioned header is a 5 part comma separated header, written by the go code as 5 separate header lines, that upon parsing on the other end of the rpc are again stored and checked as 5 string values.

```	
authRequest, ok := r.Header[authRequestHeader]
if ok && len(authRequest) != 5 {
	return nil, errors.E(errors.Invalid, errors.Str("invalid auth request in header"))
}
```

I rebuilt & ran the server to log this value as received by the server rpc in my mod_proxy setup, and it apppears to be read as a single string, with the 5 values joined and comma separated. 
 
It seems relying on HTTP servers & proxies to keep the headers as written (on multiple lines) is not correct according to the rfc [1] :

> It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.

Although I did not 100% verify that it is mod_proxy that is concatenating the fields, it seems extremely likely. The following quote from an Apache known problems page seems to confirm this [2] :

> The HTTP specifications say that it is legal to merge headers with duplicate names into one (separated by commas). Some browsers that support Cookies don't like merged headers and prefer that each Set-Cookie header is sent separately. When parsing the headers returned by a CGI, Apache will explicitly avoid merging any Set-Cookie headers.

[1] https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
[2] https://httpd.apache.org/docs/2.0/misc/known_client_problems.html#cookie-merge

**Comment by SebastianZaha** [comment]
Can confirm upspinserver works in my setup with the above linked naive change that merges the auth tokens in a single header line. 

I can try to make proper CL as well, if someone can suggest what the elegant / correct way is to encode or escape the auth tokens. The host token at least has "," as a valid character as far as I can tell.

**Comment by edpin** [comment]
Hi @SebastianZaha. That's great you got it to work. I wonder however if the client portion of your change is needed, if you're saying that it is Apache that is concatenating the headers. If I understand this right, you may only need to check whether the headers have been concatenated in `server.go`, right?

Would something like this work?

```
if len(authRequest) == 1 && strings.Contains(authRequest, ",")  {
    // strings.Split and populate authRequest so that it contains the 5 fields needed or error out.
}
```
