### ISSUE TITLE
repo: add custom import paths for other repos

### ISSUE THREAD

**Issue by adg** [upspin/upspin#319]
We just added the upspin/android repo and will soon have an upspin/cloud repo, and they should have custom import paths like our core repo's `"upspin.io/..."`. Since we've already taken the bare domain's namespace we'll need to use a sub-domain.

I suggest `"x.upspin.io/android/..."`. Other ideas?

**Comment by awly** [comment]
Why not `android.upspin.io/`, `cloud.upspin.io/`?
Seems confusing to have `$GOPATH/src/upspin.io` be a repo and `$GOPATH/src/x.upspin.io` not.

**Comment by adg** [comment]
@awly that'd work. It's a bit more troublesome to administer as we'd need to add a CNAME record to our DNS for each repo.

**Comment by adg** [comment]
I just realized this doesn't make sense for the `android` repo because it doesn't have any Go code in it. But it will matter for cloud, etc.

**Comment by adg** [comment]
Although maybe we want to do it anyway so you can fetch it with `go get -d`. Hm.

**Comment by adg** [comment]
This is done.
