### ISSUE TITLE
store/server: log misaligned

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#320]
```
rpc.Invoke: 400 Bad Request: read tcp 10.0.1.24:443->10.128.0.2:60830: i/o timeout

2017/03/09 04:10:23.808444 rpc/dircache.handleEvent: dir/server/tree.sendEventFromLog: invalid operation: cannot read log at order 1885563: dir/server/tree.LogEntry.unmarshal: I/O error: 1403 bytes left; log misaligned

2017/03/09 04:10:23.808462 rpc/dircache.watcher: upspin-dir@upspin.io: dir/server/tree.sendEventFromLog: invalid operation: cannot read log at order 1885563: dir/server/tree.LogEntry.unmarshal: I/O error: 1403 bytes left; log misaligned

2017/03/09 04:10:43.457701 rpc/dircache.handleEvent: dir/server/tree.sendEventFromLog: invalid operation: cannot read log at order 1892826: dir/server/tree.LogEntry.unmarshal: I/O error: 1142 bytes left; log misaligned

2017/03/09 04:10:43.457715 rpc/dircache.watcher: upspin-dir@upspin.io: dir/server/tree.sendEventFromLog: invalid operation: cannot read log at order 1892826: dir/server/tree.LogEntry.unmarshal: I/O error: 1142 bytes left; log misaligned
```

I interrupted a cacheserver's execution.

**Comment by presotto** [comment]
That message will cause us to start reading the log at offset -1 which will grab the current state.  Given that the offset increased between prints, that implies that the server is fixing the previous error only to encounter a new one.

I'll do a CL to avoid the double printing of the error.

**Comment by edpin** [comment]
I have a few paths I'm investigating. A loadtest did not expose this error unfortunately. So I may need to submit code to instrument this further as it's hard to debug when it doesn't repro consistently for me. Expect a few debugging CLs soon (they will be tracked here so they can be reverted when the issue is exposed).
