### ISSUE TITLE
cmd/upspinserver: web interface allows access to global name space

### ISSUE THREAD

**Issue by kwirk** [upspin/upspin#322]
Currently the web/html interface allows access to the global name space (any "username"). Should the service be limited to approved "Writers"?

**Comment by adg** [comment]
@kwirk Do you mean the returned content can be from anywhere in Upspin? I can see how that's problematic. You don't really want to become a proxy for anyone's content anywhere.

Maybe the `Writers` file would be a sufficient ACL for this. It's probably worth seeing how complicated that code is.

**Comment by kwirk** [comment]
@adg Yes, you can get content from anywhere, acting like a proxy as you say. I've got a working change which fixes this, but I'm not sure I've taken the right approach. I'll push it to gerrit for comments.

**Comment by adg** [comment]
@kwirk thanks!

**Comment by adg** [comment]
@kwirk now that #323 is fixed, you can go ahead with the approach you were taking before, except pass the `*perm.Perm` instead of `*perm.Store`.

**Comment by edpin** [comment]
I don't understand why this was related to #323 (did I miss some offline discussion)?

**Comment by kwirk** [comment]
There was some additional discussion here: https://upspin-review.googlesource.com/8341

The change in #323 made it possible to pass Perm to verify Writers, instead of a wrapped Store, making implementing the fix for this cleaner.

**Comment by edpin** [comment]
Got it. Thanks for the context.
