### ISSUE TITLE
doc: write FAQ

### ISSUE THREAD

**Issue by adg** [upspin/upspin#325]
Need to write a Frequently Asked Questions doc. Among them:

- why create something new rather than work on an existing solution?
- why a central keyserver? 
- why email addresses as primary identifiers?

**Comment by adg** [comment]
An implementor's question:

What does this error mean?

> bind.KeyServer: service with transport "remote" not registered

**Comment by robpike** [comment]
Talk about keys, a few words about how they work, how you must remember them (or the proquint).
