### ISSUE TITLE
doc: better documentation for upspinfs

### ISSUE THREAD

**Issue by adg** [upspin/upspin#328]
The [signup doc](https://upspin.io/doc/signup.md) ends with this:
```
TODO: There should be more about upspinfs.
```
Let's fix that todo.

**Comment by kavirajk** [comment]
I think we should have some kind of example usage of upspinfs. 
It worked for me once, but then from the next time it was showing this error
```
2017/06/06 23:40:06 mount helper error: fusermount: failed to access mountpoint /u: Transport endpoint is not connected
2017/06/06 18:10:06.791103 fuse.Mount failed: fusermount: exit status 1

```

I think I can update the doc with some examples. Any suggestion @adg ?

**Comment by kavirajk** [comment]
I think its happening when I do following

1. start mounting via upspinfs <mountpoint>
2. cancel it via Ctl-C
3. Try to mount again with same <mountpoint>
.
```
root@kaviraj-ThinkPad-Edge-E431:~# upspinfs /upspin/
^C2017/06/06 18:19:22.861453 shutdown: process received signal interrupt
```
```
root@kaviraj-ThinkPad-Edge-E431:~# upspinfs /upspin/
2017/06/06 23:49:25 mount helper error: fusermount: failed to open mountpoint for reading: Transport endpoint is not connected
2017/06/06 18:19:25.743765 fuse.Mount failed: fusermount: exit status 1
````

**Comment by Splizard** [comment]
Something like:

**Browsing Upspin Files**
Upspin includes a tool called upspinfs which creates a virtual filesystem where you can browse files as if they were on disc.
First make a directory for your upspin files:
```$ mkdir upspinfs/```
Then run the upspinfs tool with the directory created above:
```$ upspinfs upspinfs/```
Now you can open upspinfs in a file browser and browse the directory!

If you encounter an error when you run upspinfs the second time such as:
```
mount helper error: fusermount: failed to open mountpoint for reading: Transport endpoint is not connected
fuse.Mount failed: fusermount: exit status 1
```
Simply unmount the directory and try again:
```
$ umount -l upspinfs/ #you may need to be root to do this.
$ upspinfs upspinfs/
```

**Comment by kavirajk** [comment]
thanks @Splizard. Looks perfect.
I would like to add one more thing. Its not obvious that `upspinfs` command will block till it is un-mounted. Unless you check the code, it seems like the command got hang or something.
