### ISSUE TITLE
cmd/upspinserver: follow links on web interface to remote users

### ISSUE THREAD

**Issue by kwirk** [upspin/upspin#329]
Whilst _cmd/upspinserver_'s web interface only allows access to paths belonging to Writers (see resolution to #322), links can still be followed to remote users' files.

Should the web interface: allow access to remote files if a local Writer has created a link (current implementation); be limited to only local files;  or an additional configuration option added to allow a choice between these options?

**Comment by kwirk** [comment]
Just to add my thoughts on this, I think if you're trusting someone to write files to your server, you can probably trust them to link to remote paths sensibly.

**Comment by n2vi** [comment]
I agree.

**Comment by adg** [comment]
I'm inclined to agree as well. It also means that you can make content available through your web interface just by linking to it, as long as it's `r:all`.

I think we should leave this issue open for now, just to see if anyone wants the option to restrict the behavior.
