### ISSUE TITLE
Is augie under a free license?

### ISSUE THREAD

**Issue by stapelberg** [upspin/upspin#330]
In doc/mascot.md, I read that augie is copyright 2017 Renee French. The document goes on to declare some rules to follow. Do these rules constitute an ad-hoc, non-free license (as per https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines), or am I misunderstanding and augie is available under a free license (e.g. creative commons)?

Thanks for clarifying.

**Comment by adg** [comment]
Your reading of the page is correct, it's an Augie is Copyright Renee French, All Rights Reserved. He may only be used in the ways described on [his page](https://upspin.io/doc/mascot.md) unless special permission is granted by Renee.

**Comment by stapelberg** [comment]
For Debian, I’m inclined to remove augie from the upspin sources in that case, so that the upspin package can eventually enter Debian main (as opposed to Debian non-free, which users explicitly need to enable first).

Personally, I think not using a well-known free license is not the best choice. See the [years-long iceweasel/firefox branding issue](http://www.pcworld.com/article/3036509/linux/iceweasel-will-be-renamed-firefox-as-relations-between-debian-and-mozilla-thaw.html) for a prominent example. My suggestion would be to rephrase the wording such that you’re making a strong recommendation about augie’s usage, but ultimately still place it under a free license.

**Comment by adg** [comment]
> For Debian, I’m inclined to remove augie from the upspin sources in that case, so that the upspin package can eventually enter Debian main (as opposed to Debian non-free, which users explicitly need to enable first).

Seems fine to me.

> Personally, I think not using a well-known free license is not the best choice.

The status quo is the explicit will of the artist. If it becomes problematic in the long term (which I doubt) then we can revisit it. I'm going to close this issue now.
