### ISSUE TITLE
cmd/upspin: setupdomain returns "hash is too long to Sign" error

### ISSUE THREAD

**Issue by scottferg** [upspin/upspin#334]
Using latest as of last night 4351b8e960, darwin_amd64

It's possible that I've just followed the setup instructions out of order but every attempt to execute:

`$ upspin setupdomain -domain=example.com`

Results in:

`upspin: setupdomain: invalid operation: hash is too long to Sign`

I traced it down to the call being made here https://github.com/upspin/upspin/blob/master/cmd/upspin/setupdomain.go#L278

While I had gone through a series of steps initially (spinning up the server, signing up, etc) I can reproduce with just the first two steps in the server setup document (https://upspin.io/doc/server_setup.md)

`$ upspin signup -server=upspin.example.com you@gmail.com`
`$ upspin setupdomain -domain=example.com`

**Comment by edpin** [comment]
Oh crap, yeah. The TODO says it all.

This is easy to fix going forward, but we should be careful not to break existing domains. I will take a crack at it.

**Comment by edpin** [comment]
https://upspin-review.googlesource.com/c/8444/ sent for review.
