### ISSUE TITLE
upspin: invalid auth request in header

### ISSUE THREAD

**Issue by awly** [upspin/upspin#338]
I just updated upspin command to master and see this:

```
$ upspin ls
upspin: ls: dir/remote.Lookup("remote,upspin.awly.me:443"): I/O error:
	rpc.Invoke: 401 Unauthorized: rpc.SessionForRequest: invalid operation:
	invalid auth request in header
```

Doing some commit bisection, it looks like this fails consistently after https://github.com/upspin/upspin/commit/cd7492676a5e9813dce1fd87f357550786145006

I have not updated my upspinserver binary for a while, but didn't see announcements about breaking changes either.

After updating upspinserver binary to the same commit (or anything after), `upspin ls` works fine again.
Was this CL expected to break things?

**Comment by adg** [comment]
I dropped the ball on announcing this change. I have just sent an announcement message to upspin-announce. Sorry for the inconvenience.
