### ISSUE TITLE
client: weird error when permission is denied

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#339]
A user has a root and some files, but it's all private.

```
$ upspin -config=test@upspin.io/config ls test@upspin.io/
test@upspin.io/dir1/
test@upspin.io/dir2/
test@upspin.io/get-errors/
```

Another user should not get a `directory not empty` error.

```
$ upspin -config=test-friend@upspin.io/config ls test@upspin.io/
upspin: ls: client.Lookup: directory not empty:
	dir/remote.Lookup("remote,dir.test.upspin.io:443"):
	test@upspin.io/: dir/server.Lookup
```

This is preventing the integration tests from running (discovered when tackling issue #156)

**Comment by edpin** [comment]
Nevermind. This looks like we need a new version deployed since we've added an errors.BrokenLink.

**Comment by edpin** [comment]
Yup, redeploy fixed it. Phew.

**Comment by kwirk** [comment]
Whoops. Didn't realise that adding the new error constant may cause incompatibility between client and server. Maybe BrokenLink const value should be moved to end of the list... but I guess this is spilt milk now?

**Comment by edpin** [comment]
No worries. It didn't occur to me either. We'll keep it in mind for next time.

**Comment by awly** [comment]
Should there be some automated integration testing to check new/old client against old/new server commits?
It seems like there will be many more incompatible changes in these early stages of development that would be nice to announce.
