### ISSUE TITLE
tests: CI failures

### ISSUE THREAD

**Issue by xiang90** [upspin/upspin#343]
While reading though the codebase, I made a few small changes. However, it seems all the PRs I submitted cannot pass the CI. 

So I gave it a quick look. It seems that we indeed have quite a few real test failures, not just
random flaky.

Do we care about these failure at the moment? Should I spend some time to fix them?

**Comment by edpin** [comment]
AFAIK there's only one flaky test at the moment: serverutil/perm. The one failing in CI is passing for me. There's something weird with the setup though. We should be running `go test -short`.

**Comment by edpin** [comment]
Oh, it is running with -short. Yeah, it could be a new race in end-to-end tests with cache. Worth a look.

**Comment by adg** [comment]
There's a bug in serverutil/perm that fails consistently with -race. I sent a fix https://upspin-review.googlesource.com/c/8460/ but it leaves the tests broken. @xiang90 if you want to take a look at that fix and see if you can understand the failure, that would be great.

There's also a race in cacehserver. cc @presotto 

The CI dashboard is this: https://travis-ci.org/upspin/upspin

**Comment by presotto** [comment]
I see no cacheserver failures on the dashboard. Can you supply a reference?

**Comment by presotto** [comment]
Never mind, found the cacheserver race.  Its in inprocess.Watch.  I guess I'm the only one to use it. I'll fix it.
