### ISSUE TITLE
dir/server/tree: read log entry more carefully (do not over allocate)

### ISSUE THREAD

**Issue by xiang90** [upspin/upspin#347]
When user pass in an invalid offset, we might allocate a huge byte array for no good reason:

https://github.com/upspin/upspin/blob/master/dir/server/tree/log.go#L583

This is also a security concern. I can, in theory, write a log entry that includes a large varint somewhere. Then I can trick the dir server to unmarshal on the bad offset to use the varint as the size of the byte array.

**Comment by edpin** [comment]
Yes, agreed. We probably need a magic header to ensure we're at least reading a valid entry that we wrote ourselves. There could also be a limit on the size of the DirEntry. And perhaps even have a sanity check to ensure the size is not longer than the rest of the file (though, if we're reading from the beginning that wouldn't help much).

This problem also exists when doing Dir.Put, given the unmarshal code: 

https://github.com/upspin/upspin/blob/master/upspin/code.go#L250

**Comment by xiang90** [comment]
@edpin I am not sure if it worth the effort. But we can actually walk through the log to remember all valid offsets. We reject all invalid offsets accurately based on our knowledge. It seems that we always need to walk through the log to recover the tree anyway?

**Comment by edpin** [comment]
Looks like this was fixed by https://upspin-review.googlesource.com/c/9360/

**Comment by edpin** [comment]
That solution (cl/9360) is not good for the following reasons:

1) 1MB is an awfully small limit. It's very easy to go over this size, especially with large metadata, which can be accomplished by sharing a small file with lots of users (several wrapped keys) or just saving a large file or a directory entry with lots of files in it (either one will create lots of DirBlocks).

2) Making this a much larger limit, say X>>10MB, would mean a DirEntry of size X+1 can be saved, but not read back. If we're going to have a limit, it must apply to the storing of a DirEntry too.

3) The way this limit is documented is poor. It's buried in a constant in an auxiliary method. Any hard limit like this ought to be more visible and provide a rationale for it.

**Comment by edpin** [comment]
Possible solutions:

The idea of aligning with a magic header (as mentioned above in https://github.com/upspin/upspin/issues/347#issuecomment-289814750) or perhaps a checksum of the bytes read up to that point is probably better than a hard limit.

Another quick-and-dirty approach is to set the limit to some arbitrary number and if the requested size is bigger than that number, check whether the host machine has enough heap space for such a big allocation and soft-fail at that point, instead of crashing during make.

**Comment by adg** [comment]
```
const reasonableEntrySize = 1 << 26 // 64MB
```

We currently restrict to 64MB for a single entry. I think that's okay.
