### ISSUE TITLE
flags: group into sets for client and server

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#349]
The flags package has been helpful but needs some gardening. There is a nice property that with a nil list, flags.Parse sets up all flags. But this often puts more flags in the binary than are needed. I propose keeping that property, because it is easy, but adding two variables to the package, one for the flags that make sense in clients and one for servers. Thus in a server one would type
  flags.Parse(flags.Server)

The lists I propose are:

Client: config log blocksize prudent
Server: config log http https letscache addr project serverconfig serverkind storeserveruser tls

I may not have these exactly right.

I would also remove cachedir and put it as independent flags in cacheserver and upspinfs since they really are specific to those two unique binaries and there is no need for them to match.

**Comment by adg** [comment]
I would suggest this list for server: config log http https letscache addr tls

The project, serverconfig, serverkind, and storeserveruser flags are somewhat specialized. I don't think storeserveruser belongs in the flags package at all, for instance.
