### ISSUE TITLE
dir/server/tree: should logs be written to a light-weight memory-mapped B+ tree?

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#350]
A library that implements a B+ Tree and writes to a single file can help a lot. I've used [BoltDB](https://github.com/boltdb/bolt) and I think it would fit great as our logging solution.

It makes maintenance and backing up easier as we can have several "buckets" of key-value pairs in one single file -- potentially one file per DirServer, perhaps one file per user. The downside is that deletions do not shrink the file, but only reclaim internal space, so fragmentation can make the file grow regardless, so rotations need to be planned carefully.

**Comment by xiang90** [comment]
I use boltdb extensively in my projects. I am not sure if it is good for an append only workload though. In another word, do we care about raw performance or we care about the code simplicity (measured in upspin codebase though)?

**Comment by edpin** [comment]
It's not just append-only, it's read from an arbitrary position, as in ReadAt for Watch. 

The DB would benefit us as follows:
1. **Fine-grained locking**. A new record does not exist until its key is added. There's no reason for a ReadAt to lock anything. Writers can keep going even when there are unlimited readers at the tail.
2. **Fine-grained space reclamation**. With the current log design, we would delete entire files while with a DB we could delete each record separately. It would be very easy to keep the last X records around or at most N bytes. No need for logic like: jump to the next file if it exists, lock it if it's the tail log file, etc.
3. **Better error-handling**. See issue #351. Because a DB already validates records, we can simply skip a bad key. There's no need to read byte-by-byte or look for magic headers when skipping a bad entry. Plus, our checksums would be unnecessary as most DBs already do a better job at checksumming.
4. *(possibly)* **Performance**. That depends on implementation. But any implementation would simplify the whole buffering work we currently do as records are read entirely. Boltdb also does memory mapping, which can be a good thing on lots of sequential reads.

**Comment by edpin** [comment]
BTW: I understand the ask here is to replace 300 lines of code with possibly 10,000 and a new dependency that does more than what we need. That's the downside.

However, I also think the current log implementation was fine when logs were really just append-only and read-once-at-startup, to rebuild the tree from an unclean shutdown. Since then, we've added Watch and now log rotation. It's approaching a threshold that makes sense using a simple DB.

On the other hand, the issue is not black and white and I'm not claiming we must definitely do it. I *think* it will be a win, but I want to hear arguments on both sides. Maybe after Watch and rotation there will be nothing new there and the current plan for rotation is fine, so we could be done this time. I don't know. Worth discussing more.

**Comment by robpike** [comment]
I don't feel a B-tree is warranted. They bring a huge amount of complexity.

**Comment by adg** [comment]
I don't see a strong argument here. A B-tree seems like the wrong data structure for this purpose, and do we really understand the failure modes of BoltDB when it gets corrupted? The data structure of our logs is trivial, and that's great.

Are you proposing to replace the implementation of [dir/server/tree.LogIndex](https://godoc.org/upspin.io/dir/server/tree#LogIndex) with BoltDB? That type has a pretty simple set of methods. It might be simpler to rewrite it with the new requirements in mind.

**Comment by adg** [comment]
Any further thoughts on this?

**Comment by robpike** [comment]
Inactive. Closing.
