### ISSUE TITLE
"Access discrepencies" message unclear to new user

### ISSUE THREAD

**Issue by increpare** [upspin/upspin#352]
Minor suggestion.  

I was having trouble with my permissions (it turns out I didn't understand the permissions file and had removed my own write permissions from the directory), and was trying to update the permissions on a file.

```> upspin share -fix analytic@gmail.com/me.png```

gave me this output:

```Read permissions defined by Access files:

files readable by:
analytic@gmail.com s@aljmz.com:
	analytic@gmail.com/me.png

Access discrepancies:

analytic@gmail.com/me.png:
	Access: analytic@gmail.com s@aljmz.com
	Keys:   analytic@gmail.com
error putting entry back for "analytic@gmail.com/me.png": dir/remote.Put("remote,upspin.increpare.com:443"): permission denied:
	analytic@gmail.com/me.png: dir/server.Put
```

"Access discrepancies" was uninformative for me.  If it said "You don't have write permissions in this folder" or "You need to have write permissions to this folder to perform this operation" that would have been a workable starting point that would have enabled me to solve the problem more quickly.

**Comment by robpike** [comment]
That's not what the message is about, though. The share messages are all about sharing, and the discrepancy is as reported: two people have access, but only one has keys.

The last line is an error message from your attempt to repair the problem, reporting that indeed you do not have permission to write.

So although I agree that messages can always be improved I don't see how to improve this much, and your explicit suggestion is misleading. In fact, the error on the last line is quite informative.

**Comment by increpare** [comment]
Thanks for explaining it to me. I understand better now! :)

Here's a suggestion for an iterative improvement: it wasn't intuitively
obvious  to me that `share -fix` required write permissions. Saying "write
permission denied" instead of just "permission denied" (there are many
permission types after all) would have perhaps given me more to go on and
resulted in me coming to the correct solution earlier.


On 31 Mar 2017, at 20:15, Rob Pike <notifications@github.com> wrote:

That's not what the message is about, though. The share messages are all
about sharing, and the discrepancy is as reported: two people have access,
but only one has keys.

The last line is an error message from your attempt to repair the problem,
reporting that indeed you do not have permission to write.

So although I agree that messages can always be improved I don't see how to
improve this much, and your explicit suggestion is misleading. In fact, the
error on the last line is quite informative.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/upspin/upspin/issues/352#issuecomment-290803751>, or mute
the thread
