### ISSUE TITLE
error with cping arabic filenames in the shell

### ISSUE THREAD

**Issue by increpare** [upspin/upspin#354]
I have a file called `بابا` in my folder.

Within the shell, I type `cp بابا بابابابا`, and no errors are given, but an ls doesn't reveal any new files've been created.   

(For comparison, typing the identical command on osx produces a new file called `بابابابا`.

The command  `upspin cp analytic@gmail.com/بابا analytic@gmail.com/بابابابا` works fine.

> What version of Upspin are you using?

I don't know. I downloaded it a couple of days ago.  I'm not sure how to find out the version number (there's no command-line thing to give a version number that I can see).

>What operating system and processor architecture are you using?

Intel macbook on client (latest MacOS), server is an RPi3 (arm/raspbian).

>What did you do?

Within the shell, I tried to run a command `cp بابا بابابابا` (because it's rtl the order appears messed up for me).

>What did you expect to see?

Either it silently to create a copy of the file `بابا`, called `بابابابا`  (like what happens on osx). Or an error.

>What did you see instead?

nothing. There's no output, and also no extra files appear.

**Comment by robpike** [comment]
I cannot reproduce this failure.  I am running on a Macintosh and the command works fine. However, I am working in a shell that does not support bidi. I then tried it in Terminal and it worked fine there too.

So I am confident the upspin cp command works correctly (honestly, I can't see how it couldn't) and fear that the issue is something in your environment.

**Comment by increpare** [comment]
I appreciate the fast response.   

Okay, it turns out I completely misunderstood how upspin shell works. Perhaps the misunderstanding is worth explaining.

Because the shell prompt is "analytic@gmail.com>", I assumed that it let me type local paths to the upspin repo (so "a.png" instead of "analytic@gmail.com/a.png"), and because I was running it in a working directory that was basically a mirror of the my home directory on upspin I didn't notice things were awry.  So I was copying one file to another, just not on my upspin drive...  

Oops....

(one other thing that led me astray in this regards, which I might as well say here in case it is of interest, is that "upspin ls" lists the contents of your upspin home directory when called with no arguments, which might lead one to infer that all commands are local to your upspin home directory, even if I can't do "upspin ls a" to list the contents of "analytic@gmail.com/a").
