### ISSUE TITLE
autocert now using context package

### ISSUE THREAD

**Issue by transitorykris** [upspin/upspin#357]
autocert has switched from "golang.org/x/net/context" to "context"

https://github.com/golang/crypto/commit/88915ccf7aeb91e9324fe7cf3eddd1531ced61ea

This is breaking installation:

$ go get -u upspin.io/...
# upspin.io/cloud/https
cloud/https/https.go:119: cannot use cache (type autocertCache) as type autocert.Cache in assignment:
	autocertCache does not implement autocert.Cache (wrong type for Delete method)
		have Delete("golang.org/x/net/context".Context, string) error
		want Delete("context".Context, string) error

**Comment by transitorykris** [comment]
I've submitted a patch to Gerritt

[https://upspin-review.googlesource.com/8842](https://upspin-review.googlesource.com/8842 autocert's Cache interface now uses "context")

**Comment by adg** [comment]
Thanks for the fix!
