### ISSUE TITLE
cmd/upspinserver: panic due to redefinition of letscache flag

### ISSUE THREAD

**Issue by transitorykris** [upspin/upspin#358]
What version of Upspin are you using? Master
What operating system and processor architecture are you using? Linux/AMD64
What did you do? Start upspinserver normally
What did you expect to see? upspinserver running
What did you see instead? immediately panics due to a redefinition of the letscache flag

upspinserver panics due to a redefinition of the `lestcache` flag found in upspin.io/flags.

```
$ /home/upspin/upspinserver -https=localhost:8443
/home/upspin/upspinserver flag redefined: letscache
panic: /home/upspin/upspinserver flag redefined: letscache

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420056060, 0xcc8260, 0xd22400, 0xa46138, 0x9, 0xa54041, 0x1f)
	/usr/local/go/src/flag/flag.go:793 +0x420
flag.StringVar(0xd22400, 0xa46138, 0x9, 0x0, 0x0, 0xa54041, 0x1f)
	/usr/local/go/src/flag/flag.go:702 +0x8a
upspin.io/flags.strVar.func1()
	/home/kris/go/src/upspin.io/flags/flags.go:231 +0x60
upspin.io/flags.Register(0xc420101f08, 0x6, 0x6)
	/home/kris/go/src/upspin.io/flags/flags.go:205 +0xa9
upspin.io/flags.Parse(0xc420101f08, 0x6, 0x6)
	/home/kris/go/src/upspin.io/flags/flags.go:181 +0x3f
upspin.io/serverutil/upspinserver.Main()
	/home/kris/go/src/upspin.io/serverutil/upspinserver/main.go:56 +0x77
main.main()
	/home/kris/go/src/upspin.io/cmd/upspinserver/main.go:19 +0x20
```

**Comment by adg** [comment]
Sent

https://upspin-review.googlesource.com/8862

**Comment by fawick** [comment]
Would the issue be better resolved by keeping the call to `flags.Parse` as it was but removing the flag introduced here "https://github.com/upspin/upspin/blob/7597dfc1506004ac80272d0b66b01df9df995eba/serverutil/upspinserver/main.go#L50

**Comment by fawick** [comment]
Okay, I investigated further and found that https://upspin-review.googlesource.com/8920 caused "letscache" to be duplicated again. I am re-opening the issue and will send a CL later that fixes it by not having a local flag but using `flags.LetsEncryptCache` instead.
