### ISSUE TITLE
upspinserver: -insecure not working

### ISSUE THREAD

**Issue by chlunde** [upspin/upspin#359]
The `-insecure` flag is not working for `cmd/upspinserver`.

I applied the following patch locally, but maybe this should be handled a central place, and perhaps by using the `-http` port instead.
```
diff --git a/serverutil/upspinserver/main.go b/serverutil/upspinserver/main.go
index e798585..467dcdc 100644
--- a/serverutil/upspinserver/main.go
+++ b/serverutil/upspinserver/main.go
@@ -66,6 +66,8 @@ func Main() {
 
        // Set up HTTPS server.
        var opt https.Options
+       opt.InsecureHTTP = flags.InsecureHTTP
+
        if flags.TLSCertFile != "" && flags.TLSKeyFile != "" {
                opt.CertFile = flags.TLSCertFile
                opt.KeyFile = flags.TLSKeyFile
```

**Comment by fawick** [comment]
I ran into the same issue and sent https://upspin-review.googlesource.com/c/9040/

**Comment by adg** [comment]
This will be fixed by a pending refactoring that I hope to have submitted in the next 24 hours.

**Comment by adg** [comment]
See: https://upspin-review.googlesource.com/c/9121/

**Comment by fawick** [comment]
@adg should I abandon 9040 then?

**Comment by adg** [comment]
@fawick yes, please. Thanks.
