### ISSUE TITLE
cmd/upspin: provide a shorthand, the equivalent of $HOME for Upspin users

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#361]
The suggestion is to have @ be like ~, that is, @/foo means the file foo in my Upspin user root.

This would be a convenience only in the upspin command, not general Upspin file naming.

**Comment by awly** [comment]
It could be confusing with @: someone might assume that leaving out domain _or_ user parts defaults to current username.

For example: "I'm `bob@gmail.com`. Since `@/foo` means `bob@gmail.com/foo`, surely `alice@/foo` must mean `alice@gmail.com/foo`".

**Comment by adg** [comment]
@awyl in that case the user will get an invalid username error message. That seems acceptable to me. Or we could even make the behavior you describe just work?

**Comment by awly** [comment]
@adg of course, an error is fine, just noting that it may be unexpected for some new users.
Whether or not to implement the describe behavior is up to you, i don't see anything terribly wrong with it.
