### ISSUE TITLE
cmd/upspinserver: not finding default letscache directory

### ISSUE THREAD

**Issue by rwcarlsen** [upspin/upspin#365]
upspin version 1d2a336996a9f248cb9301a760277cc65688a8ce.

With newer builds of upspinserver, it isn't finding my (default located) lets-encrypt cache certs/key.  I have to manually pass it e.g. ``upspinserver -letscache upspin/letsencrypt``.  When I just try to run ``upspinserver`` vanilla, I get:

```
2017/04/14 19:50:41.288274 Store and Directory servers initialized.
2017/04/14 19:50:41.288611 Store server configuration: backend=Disk basePath=/root/upspin/server/storage
2017/04/14 19:50:41.293888 https: not on GCE; serving HTTPS on ":443" using provided certificates
2017/04/14 19:50:41.294358 https: WARNING: using self-signed test certificates.
2017/04/14 19:50:41.294937 https: setting up TLS config: cloud/https.newDefaultTLSConfig: invalid operation: certificate file "/src/upspin.io/rpc/testdata/cert.pem" not readable
```

**Comment by n2vi** [comment]
I'm still confused about the exact history here.   Anyway, if the letscache option is omitted, we're contemplating looking for a letsencrypt subdirectory alongside the config file and using that if it exists.

**Comment by rwcarlsen** [comment]
I've updated/rebuilt and restarted my upspinserver a few times, and I don't recall ever needing to manually specify the letsencrypt cache directory.  The last time I updated, however, I did need to specify it.  It is possible my memory isn't serving me well.  Regardless, it seems odd that starting up a new server for the first time is simply ``upspinserver &``, but on subsequent starts you need to ``upspinserver -letscache upspin/letsencrypt``.

**Comment by adg** [comment]
It was a7f8a342b3d79fb2392cd580cc287dfaaac5bfd2 that broke the default.

**Comment by adg** [comment]
I sent this change, which I think might be a cleaner fix: https://upspin-review.googlesource.com/c/9243/

**Comment by SebastianZaha** [comment]
This had the side effect that now one *must* pass -letscache '' when passing own certificates, otherwise they are just ignored.

**Comment by adg** [comment]
@SebastianZaha yup. No reason for that to be the case. I sent a fix: https://upspin-review.googlesource.com/10660
