### ISSUE TITLE
cmd/upspin: cacheserver not started by upspin command

### ISSUE THREAD

**Issue by rwcarlsen** [upspin/upspin#366]
When I run in the upspin shell or use upspinfs, the cacheserver is automatically started, but when I just try to run any other upspin subcommand without cacheserver started, I get:

```
upspin: ls: client.Lookup: I/O error:
	dir/remote.Lookup("remote,upspin.example.com:443"):
	rpc.Invoke: Post http://localhost:9999/api/Dir/Lookup: dial tcp [::1]:9999: getsockopt: connection refused
```

Something like this to fix it maybe:

```diff
diff --git a/cmd/upspin/main.go b/cmd/upspin/main.go
index e9d4dc1..263d779 100644
--- a/cmd/upspin/main.go
+++ b/cmd/upspin/main.go
@@ -131,6 +131,7 @@ func main() {
        }
        cmd := state.getCommand(state.Name)
        state.init()
+       cacheutil.Start(state.Config)
        cmd(state, args...)
        state.ExitNow()
```

**Comment by presotto** [comment]
I agree.  I think things got rearranged for some setup subcommand to the detriment of the cache server starts. I'll have at it.

**Comment by robpike** [comment]
I believe this was fixed recently. Please reopen if you disagree.
