### ISSUE TITLE
dir/server: reject invalid Access files?

### ISSUE THREAD

**Issue by adsouza** [upspin/upspin#372]
Steps to reproduce:
1) upspin mkdir ann@example.com/test
2) echo "r: *" > /tmp/Access
3) upspin cp /tmp/Access ann@example.com/test/

Expected result:
step 3 fails because * should not be used by itself on the right hand side of a line in an Access file, since it will then be treated as a group name instead of a wildcard, which is almost certainly not what the user wants.

Actual result:
step 3 succeeds but rerunning the same command line will subsequently fail with this error message:

upspin: cp: ann@example.com/test/Access: client.Put: item does not exist:
	ann@example.com/Group/*: client.Get:
	client.Get:
	dir/remote.Lookup("remote,dir.upspin.io:443"):
	dir/server/tree.Lookup:
	ann@example.com/Group

**Comment by adg** [comment]
I guess the main question is whether it should be legal to upload invalid Access files. It's server-dependent, but perhaps the common `dir/server` should not allow this.

**Comment by robpike** [comment]
It _is_ a valid Access file, and that is what's really wrong. Closed in favor of https://github.com/upspin/upspin/issues/381
