### ISSUE TITLE
upspin-deploy-gcp: cannot find package "golang.org/x/sync/semaphore"

### ISSUE THREAD

**Issue by transitorykris** [upspin/upspin#375]
What version of Upspin are you using? Master
What operating system and processor architecture are you using? macOS/x86_64
What did you do? `upspin-deploy-gcp -create -domain=jngl.io -project=jngl-io`
What did you expect to see? successfully creating a cluster
What did you see instead?

```
2017/05/09 14:52:06 Fetching kubectl credentials
Fetching cluster endpoint and auth data.
kubeconfig entry generated for cluster.
2017/05/09 14:52:07 Building "storeserver"
2017/05/09 14:52:07 Building "dirserver"
can't load package: go/src/google.golang.org/api/support/bundler/bundler.go:31:2: cannot find package "golang.org/x/sync/semaphore" in any of:
	/usr/local/go/src/golang.org/x/sync/semaphore (from $GOROOT)
	/Users/jnglio/go/src/golang.org/x/sync/semaphore (from $GOPATH)
can't load package: go/src/google.golang.org/api/support/bundler/bundler.go:31:2: cannot find package "golang.org/x/sync/semaphore" in any of:
	/usr/local/go/src/golang.org/x/sync/semaphore (from $GOROOT)
	/Users/jnglio/go/src/golang.org/x/sync/semaphore (from $GOPATH)
2017/05/09 14:52:08 deploy: storeserver: exit status 1
```

This was on a fresh account starting with an empty GOPATH. Running `go get -u golang.org/x/sync/semaphore` then re-running `upspin-deploy-gcp` was successful.

**Comment by adg** [comment]
Currently `upspin-deploy-gcp` assumes that you can build those packages using what's in your local workspace (`GOPATH`). Maybe it should check? Although I guess that's what it's doing here. Maybe the error message should be more explicit.

**Comment by adg** [comment]
We'll resolve this by resolving #214
