### ISSUE TITLE
upspin: why does Put return Refdata and not Reference?

### ISSUE THREAD

**Issue by adg** [upspin/upspin#376]
Looking at this, in package upspin:

```
type StoreServer interface {
        Dialer
        Service
        Get(ref Reference) ([]byte, *Refdata, []Location, error)
        Put(data []byte) (*Refdata, error)
        Delete(ref Reference) error
}

type Refdata struct {
        Reference Reference
        Volatile  bool
        Duration  time.Duration
}
```

Why should the `Put` method return a `Refdata` and not just a `Reference`?

It seems to me that the `Volatile` and `Duration` fields of `Refdata` are not relevant or useful to the callers of `Put`.

Thoughts?

cc @robpike @presotto

**Comment by robpike** [comment]
Volatile is a property of the file on the server, and is needed for the cacheserver.
