### ISSUE TITLE
dir/server/tree: user.Parse fails after upgrading to latest upspinserver-gcp

### ISSUE THREAD

**Issue by transitorykris** [upspin/upspin#377]
What version of Upspin are you using? latest upspinserver-gcp
What operating system and processor architecture are you using? Linux instance-1 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
What did you do? upgraded from an old version of upspinserver (~April 3rd)
What did you expect to see? properly behaving upspinserver
What did you see instead?

```
$ upspin get kris@jn.gl/test.txt
upspin: get: kris@jn.gl/test.txt: client.Get: invalid operation:
	client.Get:
	dir/remote.Lookup("remote,upspin.jn.gl:443"):
	dir/server.Lookup:
	dir/server/tree.New:
	dir/server/tree.recoverFromLog:
	user.Parse: user name must contain one @ symbol
```

Rolling back to the previous binary was successful.

**Comment by adg** [comment]
I'm not able to reproduce this. What is the repo hash you're at?

I built upspinserver-gcp at commits 6559bb0fce722473d9fefe9756907054d78fcafd and upspin/gcp@5b036ac260329fd4ce9bedb21fc8aa82be8c5cc5 and it seems to work okay for me.

**Comment by adg** [comment]
Maybe you could try adding a test case to the `upspin.io/user` package for that user name?

**Comment by robpike** [comment]
This seems not to be an issue at tip. If you can construct a reproducible case, please provide it and reopen the issue.

**Comment by transitorykris** [comment]
I've not been able to isolate the broken username. All of them appear well formatted. I've capped that server, and moving users over to tip.

**Comment by adg** [comment]
Thanks. Please let us know if you see the issue surface again.
