### ISSUE TITLE
Support casbin as the authorization backend

### ISSUE THREAD

**Issue by hsluoyz** [upspin/upspin#380]
[Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I think it's more powerful than the current ACL way, what do you think? Thanks.

**Comment by robpike** [comment]
Casbin looks interesting but provides a much richer set of access control primitives. Upspin deliberately chose a very simple set, to make it easier for non-experts to understand its properties. Casbin would introduce new ideas that were avoided in the design of Upspin, such as superuser and role accounts.

I don't feel Casbin is the right fit for the project, but thanks very much for your suggestion.
