### ISSUE TITLE
access: define syntax of valid group file name

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#381]
When writing Access files, if the name doesn't work as anything else, it's taken to be a group file. However, there should be constraints defined on what a valid group file is, and that should probably go into the upspin.io/valid package. For instance unprintable characters and metacharacters such as "*" should be avoided.

**Comment by robpike** [comment]
This is likely just a subissue of #49, but we can keep it open.

**Comment by robpike** [comment]
Groups cannot be called Access.

**Comment by robpike** [comment]
Proposal: Use the rools defined for the user part of a user name (that is, the part before the domain name), but exclude the special case of "*". Thus the rule becomes:

// Names are validated and canonicalized by the UsernameCasePreserved profile
// of the RFC 7613, "Preparation, Enforcement, and Comparison of Internationalized Strings",
// also known as PRECIS.
//
// Further restrictions are added here. The only ASCII punctuation characters
// that are legal are "!#$%&'*+-/=?^_{|}~", and a name that is only ASCII punctuation
// is rejected.
//
// Case is significant and spaces are not allowed.

I believe this would fix all the possibilities of ambiguous parsing of Access files.

**Comment by adg** [comment]
I think those rools sound fine to me.

**Comment by adsouza** [comment]
LGTM.
