### ISSUE TITLE
doc: bad quotes in "Setting up upspinserver"

### ISSUE THREAD

**Issue by rsc** [upspin/upspin#382]
The doc says:

    local$ gsutil -m rm gs://example-com-upspin/`**`

Those backquotes should be forward quotes, and it would be less confusing to forward-quote the whole gs://... path instead of just the final two stars.

**Comment by rsc** [comment]
Sorry, link to doc I mean: https://upspin.io/doc/server_setup.md

**Comment by adg** [comment]
Thanks for the report. Sent [CL 9800](https://upspin-review.googlesource.com/9800).
