### ISSUE TITLE
upspinfs is very slow when navigating in a git repo

### ISSUE THREAD

**Issue by derekchiang** [upspin/upspin#385]
I just tried cloning this repo into upspinfs, which took a while but it was mostly acceptable.  However, for some reason it's taking 10+ seconds to simply `cd` into the repo, and a couple seconds to `ls` in the repo.  Editing the code in Vim is also extremely laggy.  The most puzzling part is that even moving around a file in Vim seems laggy, let long writing to the file.

I guess I'm mostly curious if it's a known issue that upspinfs has trouble with directories that contain a large number of files (since there are a lot of files in `.git`), or if there's just something wrong with my particular setup.

I'm running upspinfs on a Linux machine.  The dir/store servers are running on GCE.

**Comment by adg** [comment]
Are you also running a cacheserver?
Upspinfs performs pretty badly without one.

**Comment by derekchiang** [comment]
Ah, that did it.  Running a cacheserver makes everything a lot faster.  Thanks!
