### ISSUE TITLE
cmd/upspin: keygen should use "secrets:" from config

### ISSUE THREAD

**Issue by n2vi** [upspin/upspin#387]
If the active config file specifies "secrets:" then "keygen" and especially "keygen -rotate" should use that rather than the default Flag value for where.

Also, the non-empty default Flag value means that the warning message "-where must not be empty" is useless.

**Comment by n2vi** [comment]
Probably need to fix the code and comment in cmd/upspin/main.go (State)init() about keygen at the same time.

**Comment by robpike** [comment]
Pretty much fixed by https://upspin-review.googlesource.com/11340, a different way. No more -where flag in any case.
