### ISSUE TITLE
test: flaky snapshot test 

### ISSUE THREAD

**Issue by adg** [upspin/upspin#389]
On TravisCI we have seen several [test](https://travis-ci.org/AugieBot/upspin/builds/239333172?utm_source=github_status&utm_medium=notification) [failures](https://travis-ci.org/AugieBot/upspin/builds/237040455) surrounding snapshots. These failures only happen sometimes, so there is either a race condition in the test or the dir/server code.

This is the error message, running tests for `upspin.io/test`:

```
--- FAIL: TestIntegration (75.19s)
    --- FAIL: TestIntegration/kind=server (25.64s)
        --- FAIL: TestIntegration/kind=server/packing=plain (8.53s)
            --- FAIL: TestIntegration/kind=server/packing=plain/Snapshot (0.04s)
            	snapshot_test.go:87: snapshot_test.go:85: test+snapshot@upspin.io/2017/05/29/04:23/snapshot-test/dir/file: client.Get: item does not exist:
            			client.Get:
            			dir/server/tree.Lookup:
            			test+snapshot@upspin.io/2017/05/29/04:23/snapshot-test
        --- FAIL: TestIntegration/kind=server/packing=eeintegrity (8.54s)
            --- FAIL: TestIntegration/kind=server/packing=eeintegrity/Snapshot (0.04s)
            	snapshot_test.go:87: snapshot_test.go:85: test+snapshot@upspin.io/2017/05/29/04:23/snapshot-test/dir/file: client.Get: item does not exist:
            			client.Get:
            			dir/server/tree.Lookup:
            			test+snapshot@upspin.io/2017/05/29/04:23/snapshot-test
```

**Comment by adg** [comment]
Another failure: https://travis-ci.org/upspin/upspin/builds/239791441

**Comment by adg** [comment]
Another failure: https://travis-ci.org/upspin/upspin/builds/240159469

**Comment by adg** [comment]
Another failure: https://travis-ci.org/AugieBot/upspin/builds/240648304

**Comment by edpin** [comment]
I ran this standalone hundreds of time and I haven't managed to reproduce it. I ran the integration tests as they are now and also removed all other tests and ran just the snapshot test (commenting out everything else).

That's not to say there's no bug, just that it's hard to get a repro so I can debug.

However, I recalled a comment when I submitted the test and I was worried about this possibility. Then I convinced myself it wasn't a problem. Here's the exact code-review exchange:

https://upspin-review.googlesource.com/c/7971/2/test/snapshot_test.go#86

Now I have to remember why I was concerned about this possibility and whether the original code was correct.

More work to be done for sure...

**Comment by adg** [comment]
Are you running with -race ?

**Comment by adg** [comment]
When I was diagnosing the other test flakes, I would run something like this

```
$ go test -c -race && while ./test.test -test.run=TestIntegration/kind=server/packing=ee/Snapshot; do clear; done
```

which tries the test over and over until it fails, without rebuilding the test binary each time.

**Comment by adg** [comment]
I think you probably already are, but make sure you're doing this on a Linux machine (the continuous builders are).

**Comment by edpin** [comment]
Yes, I ran with -race on Linux. Also used -test.count=20.

The failures you sent out are all slightly different: they happen with plain, eeintegrity and ee packings. So, one theory I had that the cleanups are not happening correctly is false since plain is the first one to run. 

The timings on my machine and the CI machine don't seem terribly off, so it's surprising I can't reproduce it.

I think a single retry would fix the test, but it wouldn't cure the real underlying issue, so I don't want to do that just yet. But it's a quick short-term plug while we investigate, if the problem can't be solved soon.

**Comment by adg** [comment]
Another thing I was explored was always doing the cleanup *before* the
tests, instead of afterward.
That way we don't have to rely on tests cleaning up after themselves.
I got partway through doing that before getting distracted.

**Comment by edpin** [comment]
I've run this on two linux machines and a mac and Dave ran it on two linuxes and a mac with no failures either. In every case, I tried scripting, running with and without -race and -count=X. 

All my machines have go 1.8. I noticed the CI runs 1.8.1. I doubt that could be the reason, but I'll now upgrade and re-try a few more thousand times...

**Comment by edpin** [comment]
With 1.8.3 I run into other problems:

```
--- FAIL: TestIntegration (45.92s)
    --- FAIL: TestIntegration/kind=server (18.86s)
        --- FAIL: TestIntegration/kind=server/packing=eeintegrity (6.31s)
        	integration_test.go:376: remove /dev/shm/test/testenv-dirserver893672844: directory not empty
```

I've noticed that these testenv-dirserver directories are not getting cleaned up. But these failures are not supposed to happen. I'll open a new issue.

**Comment by adg** [comment]
[Another failure](https://travis-ci.org/AugieBot/upspin/builds/244780176?utm_source=github_status&utm_medium=notification), this time with some debugging info:

```
--- FAIL: TestIntegration (78.34s)
    --- FAIL: TestIntegration/kind=server (27.19s)
        --- FAIL: TestIntegration/kind=server/packing=plain (8.56s)
        	integration_test.go:376: remove /tmp/testenv-dirserver170897217: directory not empty
        --- FAIL: TestIntegration/kind=server/packing=ee (9.81s)
            --- FAIL: TestIntegration/kind=server/packing=ee/Snapshot (0.08s)
            	snapshot_test.go:88: Failed to Get "test+snapshot@upspin.io/2017/06/20/03:33/snapshot-test/dir/file". Attempting to Glob "test+snapshot@upspin.io/2017/06/20/03:33"
            	snapshot_test.go:146: Error in lookup of "test+snapshot@upspin.io/2017/06/20/03:33/snapshot-test/dir/file": client.Lookup: item does not exist:
            			dir/server/tree.Lookup:
            			test+snapshot@upspin.io/2017/06/20/03:33/snapshot-test
FAIL
```

**Comment by adg** [comment]
Another [failure](https://travis-ci.org/AugieBot/upspin/builds/245188344?utm_source=github_status&utm_medium=notification): 

```
--- FAIL: TestIntegration (82.49s)
    --- FAIL: TestIntegration/kind=server (29.11s)
        --- FAIL: TestIntegration/kind=server/packing=ee (10.19s)
            --- FAIL: TestIntegration/kind=server/packing=ee/Snapshot (0.05s)
            	snapshot_test.go:88: Failed to Get "test+snapshot@upspin.io/2017/06/21/01:54/snapshot-test/dir/file". Attempting to Glob "test+snapshot@upspin.io/2017/06/21/01:54"
            	snapshot_test.go:146: Error in lookup of "test+snapshot@upspin.io/2017/06/21/01:54/snapshot-test/dir/file": client.Lookup: item does not exist:
            			dir/server/tree.Lookup:
            			test+snapshot@upspin.io/2017/06/21/01:54/snapshot-test
FAIL
```

**Comment by adg** [comment]
Another failure: https://travis-ci.org/upspin/upspin/builds/245209349

**Comment by adg** [comment]
Another one: https://travis-ci.org/upspin/upspin/builds/245215500

**Comment by shurcooL** [comment]
Another one: https://travis-ci.org/AugieBot/upspin/builds/245587250.

**Comment by adg** [comment]
Here's one with more diagnostic information: https://travis-ci.org/upspin/upspin/builds/245642454

```
--- FAIL: TestIntegration (80.58s)
    --- FAIL: TestIntegration/kind=server (29.99s)
        --- FAIL: TestIntegration/kind=server/packing=plain (10.18s)
            --- FAIL: TestIntegration/kind=server/packing=plain/Snapshot (1.12s)
            	snapshot_test.go:88: Failed to Get "test+snapshot@upspin.io/2017/06/22/05:13/snapshot-test/dir/file". Attempting to Glob "test+snapshot@upspin.io/2017/06/22/05:13"
            	snapshot_test.go:148: Entry: &{SignedName:test@upspin.io/snapshot-test/dir/file Link: Attr:0 Packing:eeintegrity Time:2017-06-22T05:13:23 UTC Blocks:[{Location:{Endpoint:inprocess Reference:92B43532F482ADECC8E9436978E759D420E52C8183F988996B376CDD5F6CBD65} Offset:0 Size:32 Packdata:[146 180 53 50 244 130 173 236 200 233 67 105 120 231 89 212 32 229 44 129 131 249 136 153 107 55 108 221 95 108 189 101]}] Packdata:[64 240 11 47 99 228 159 59 56 66 65 28 241 159 144 114 136 184 111 25 74 219 192 83 40 84 150 100 6 54 145 4 246 64 189 216 207 2 42 226 93 138 161 200 197 174 10 211 170 221 32 228 218 110 169 82 95 65 181 114 112 242 247 13 140 40 0 0 64 237 124 110 91 130 133 198 222 205 139 109 214 118 93 51 147 81 180 55 241 96 223 129 52 250 189 128 151 155 251 18 133] Writer:test@upspin.io Name:test+snapshot@upspin.io/2017/06/22/05:13/snapshot-test/dir/file Sequence:4383568732480339969}
            	snapshot_test.go:79: snapshot_test.go:78: no response on event channel after one second
        --- FAIL: TestIntegration/kind=server/packing=eeintegrity (9.72s)
            --- FAIL: TestIntegration/kind=server/packing=eeintegrity/Snapshot (0.08s)
            	snapshot_test.go:88: Failed to Get "test+snapshot@upspin.io/2017/06/22/05:13/snapshot-test/dir/file". Attempting to Glob "test+snapshot@upspin.io/2017/06/22/05:13"
            	snapshot_test.go:146: Error in lookup of "test+snapshot@upspin.io/2017/06/22/05:13/snapshot-test/dir/file": client.Lookup: item does not exist:
            			dir/server/tree.Lookup:
            			test+snapshot@upspin.io/2017/06/22/05:13/snapshot-test
FAIL
```

**Comment by adg** [comment]
Another one https://travis-ci.org/AugieBot/upspin/builds/246991328

**Comment by adg** [comment]
This flaky test continues to be a thorn in my side.
I get failures on almost every build report, which renders the continuous
integration kind of useless.
I would really like to know if my code is what is broken, rather than see
more of these failures.

**Comment by shurcooL** [comment]
I've looked into this a bit, and wanted to share some small findings.

I tried to reproduce locally, with very little luck on macOS and Linux. The tests kept passing pretty much every time (one exception, see below).

I forked upspin repo on github, enabled Travis on my fork. I was able to reproduce in Travis **very easily**. It failed on the very [first build](https://travis-ci.org/shurcooL/upspin/builds/247363683) with the common `TestIntegration/kind=server/packing=ee/Snapshot` failure.

I iterated towards the following Travis script:

```YML
sudo: false
language: go
go:
  - 1.8.x
#  - master
#matrix:
#  allow_failures:
#    - go: master
#  fast_finish: true
go_import_path: upspin.io
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -v -short -race -count=10 -run=TestIntegration/kind=server ./test
```

With `go test -v -short -race -count=10 -run=TestIntegration/kind=server ./test`, I'm able to reproduce a failure 5 times out of 5 in Travis CI.

At first, I was thinking that there might be something wrong with Travis CI itself. Perhaps the Linux version it uses, or something else weird about its setup.

However, I did run into **one** relevant-looking failure in a **local** Linux VM:

![image](https://user-images.githubusercontent.com/1924134/27576895-a574dfe4-5aec-11e7-9c70-f850b36919fa.png)

(Out of hundreds of test runs, that was absolutely the only one.)

I ran also into the following interesting rare failure in [Travis CI](https://travis-ci.org/shurcooL/upspin/builds/247372793):

```
...
=== RUN   TestIntegration/kind=server/packing=eeintegrity/GlobLinkErrors
=== RUN   TestIntegration/kind=server/packing=eeintegrity/SequenceNumbers
=== RUN   TestIntegration/kind=server/packing=eeintegrity/RootDeletion
2017/06/27 04:58:07.331883 Created root: test-friend@upspin.io/
2017/06/27 04:58:07.341433 Deleting root "test-friend@upspin.io/"
2017/06/27 04:58:07.350663 Created root: test-friend@upspin.io/
2017/06/27 04:58:07.357500 Deleting root "test-friend@upspin.io/"
=== RUN   TestIntegration/kind=server/packing=eeintegrity/ReadAccess
=== RUN   TestIntegration/kind=server/packing=eeintegrity/GroupAccess
2017/06/27 04:58:07.847258 Created root: test-friend@upspin.io/
2017/06/27 04:58:07.968425 Deleting root "test-friend@upspin.io/"
2017/06/27 04:58:07.994841 dir/server.Delete: Error removing group file: access.RemoveGroup: item does not exist: group does not exist
=== RUN   TestIntegration/kind=server/packing=eeintegrity/WriteReadAllAccessFile
=== RUN   TestIntegration/kind=server/packing=eeintegrity/Watch
2017/06/27 04:58:08.922649 dir/server.Watch: timeout sending event for test@upspin.io
2017/06/27 04:58:08.924043 dir/server.Watch: timeout sending event for test@upspin.io
2017/06/27 04:58:08.924793 dir/server.Watch: timeout sending event for test@upspin.io
=== RUN   TestIntegration/kind=server/packing=eeintegrity/WatchErrors
panic: runtime error: slice bounds out of range

goroutine 800 [running]:
upspin.io/upspin.getBytes(0xc4223bfca0, 0x15, 0x15, 0x4, 0x15, 0xc4223bfc88, 0xc4223bfc90, 0x0, 0x0)
    /home/travis/gopath/src/upspin.io/upspin/code.go:330 +0x1c5
upspin.io/upspin.(*DirEntry).Unmarshal(0xc420e75cf8, 0xc4223bfca0, 0x15, 0x15, 0x15, 0x15, 0x0, 0x0, 0x4159b0)
    /home/travis/gopath/src/upspin.io/upspin/code.go:223 +0x6e
upspin.io/dir/server/tree.(*LogEntry).unmarshal(0xc420e75cf0, 0xc4223bfc80, 0xc4223bfc80, 0x309)
    /home/travis/gopath/src/upspin.io/dir/server/tree/log.go:877 +0xf96
upspin.io/dir/server/tree.(*Reader).ReadAt(0xc42266ab80, 0x309, 0x40f19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/travis/gopath/src/upspin.io/dir/server/tree/log.go:407 +0x948
upspin.io/dir/server/tree.(*watcher).sendEventFromLog(0xc42266ad40, 0x309, 0xc42266ad40, 0xc421402160, 0xb24165)
    /home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:284 +0x100
upspin.io/dir/server/tree.(*watcher).watch(0xc42266ad40, 0x309)
    /home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:312 +0x8b
created by upspin.io/dir/server/tree.(*Tree).Watch
    /home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:146 +0x892
exit status 2
FAIL    upspin.io/test  128.482s


The command "go test -v -short -race -count=10 -run=TestIntegration/kind=server ./test" exited with 1.

Done. Your build exited with 1.
```

Which was a real issue in code. I filed #403 for that.

That makes me suspect there may be something wrong with the code, and the Travis CI setup for some reason can reproduce it much more easily. Once we resolve #403, there might be some positive effect. Only one way to find out.

**Comment by shurcooL** [comment]
Another local failure I saw. It looks like it happened due to being out of memory.

https://gist.github.com/anonymous/e7db6b8c1205f594af9bc73adac69270

This was on a Linux VM with 2 GB.

Travis also has limited memory, so it'll be worthwhile to ensure that it's not running out of it. I've seen that happen in https://github.com/go-gl/gl/pull/73, where certain large Go packages kept dying to `signal: killed` during compilation in Travis.

**Comment by adg** [comment]
Thanks for the hunting @shurcooL, but after careful reading of the code I think I found the root cause. I sent https://upspin-review.googlesource.com/10540 for review.

**Comment by shurcooL** [comment]
> I think I found the root cause.

Awesome! Since it's very easy for me to verify, let me give it a shot.

**Comment by adg** [comment]
Interesting, it's still failing but for a different reason. Investigating:

```
--- FAIL: TestIntegration (78.04s)
    --- FAIL: TestIntegration/kind=server (29.45s)
        --- FAIL: TestIntegration/kind=server/packing=plain (9.08s)
            --- FAIL: TestIntegration/kind=server/packing=plain/Snapshot (1.04s)
            	snapshot_test.go:79: snapshot_test.go:78: no response on event channel after one second
        --- FAIL: TestIntegration/kind=server/packing=eeintegrity (9.11s)
            --- FAIL: TestIntegration/kind=server/packing=eeintegrity/Snapshot (1.04s)
            	snapshot_test.go:79: snapshot_test.go:78: no response on event channel after one second
        --- FAIL: TestIntegration/kind=server/packing=ee (11.25s)
            --- FAIL: TestIntegration/kind=server/packing=ee/Snapshot (1.04s)
            	snapshot_test.go:79: snapshot_test.go:78: no response on event channel after one second
```

**Comment by adg** [comment]
Okay, I think the fix is ready for review now. A tricky one.
