### ISSUE TITLE
dir/server: store a log of roots or otherwise backup the root?

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#393]
In a recent conversation with @n2vi he pointed out that the current root is an easy thing to lose due to data corruption or accidental or malicious deletion. Once a root is lost, recovering the entire tree is only possible by playing back the whole log. But logs will start being trimmed at some point since local space on the server is typically limited. If that happens and the root is gone, all data is lost.

Backing up roots seems necessary. A history of roots might be useful just like the log is useful in recovering from errors. We should consider a log of roots or perhaps storing the current root somewhere outside of the DirServer -- perhaps into a public blockchain or as a special entry in the keyserver.

To be discussed...

**Comment by adg** [comment]
A simple approach: give the DirServer a storage.Storage configuration and have it store the roots in a file there. It could be the same GCP bucket that the StoreServer uses, for most users. Easy to integrate with upspinserver.

**Comment by jancona** [comment]
I have been looking at creating a serverless Upspin implementation using AWS Lambda and API Gateway. That's not feasible as long as DirServer needs a persistent filesystem. Since Lambdas may shutdown or restart at any time and multiple Lambdas may run concurrently, a solution like @adg's suggestion would probably work better than a conventional backup/restore.

**Comment by adg** [comment]
@jancona I'm [working on](https://upspin-review.googlesource.com/c/upspin/+/13840) the "just back up the root" version of this at the moment. This involves plumbing a storage backend through to the dir/server. Once that work is done, it should be easier to break dir/server's dependency on local disk.

However, for the log to serve its purpose we need an efficient and reliable log storage service. Does AWS provide such a thing? S3 isn't really sufficient, I don't think.

**Comment by jancona** [comment]
I'm just getting familiar with the Upspin code. Is there anything (besides code) I should be reading to get up to speed on the implementation? In the meantime, please forgive my newbie questions.

I assume the main obstacle to using S3 for log storage is the lack of append semantics. [Kinesis Streams](https://aws.amazon.com/kinesis/streams/details/) (similar to Kafka) has a maximum data retention time of a week, so can't be used by itself for long-term persistence.

Am I correct that the current DirServer implementation is single server? Lambda functions are inherently concurrent, so something would have to replace all the synchronization that's done now with mutexs.

**Comment by adg** [comment]
@jancona correct. The current DirServer implementation is single server and not sharded at all. It'd probably be easiest to write an entirely new DirServer.

**Comment by jancona** [comment]
I was afraid that would be the answer. I'll take a look at that option. Thanks for your help!
