### ISSUE TITLE
config/initconfig: Homedir() fails when run in an iOS simulator

### ISSUE THREAD

**Issue by transitorykris** [upspin/upspin#395]
iOS simulators do not return a username when osuser.Current() is called. There appears to be no way to configure the simulator to do so. upspin/flags calls config.Home() in its init(), which panics when no username is found.

**Comment by adg** [comment]
What are you using `upspin/flags` for on iOS? Is it necessary?

**Comment by n2vi** [comment]
I recommend -prudent in clients, so hope we can make flags possible.

**Comment by adg** [comment]
@n2vi command-line flags don't really have much meaning on iOS, though. There's no command-line.

**Comment by transitorykris** [comment]
I'm not interested in upspin/flags here, and really doesn't make sense in iOS, since upspin is used as an xcode framework (built by gomobile). However, upspin/flags is imported by upspin/client, which is a handy package.

**Comment by adg** [comment]
`client` uses `flags` for `Prudent` and `BlockSize`, so it doesn't care about the user's home directory. Maybe we could somehow defer evaluation of those defaults until flag registration time, and so if those flags are never registered then `Homedir` would not be called.

I'll look into it.

**Comment by adg** [comment]
Fixed by 93b5835f7c532f414f78b6f2ec7031a2095bcd83

**Comment by transitorykris** [comment]
Amazing! You rock. 💯
