### ISSUE TITLE
project: email address to privately report conduct issues

### ISSUE THREAD

**Issue by moshez** [upspin/upspin#396]
The e-mail address given for reporting CoC violations in `CONDUCT.md` is upspin@googlegroups.com. From the fact that security issues need to be reported to a separate mailing list (-security), it seems like this mailing list is not private. CoC violations are often sensitive, and confidentiality is important. Please set a separate alias for CoC violations (and ideally have specific people that can be reached, in case someone wants to know exactly who would see the report).

**Comment by adg** [comment]
Thanks, I'll probably just put my email address there.
