### ISSUE TITLE
all: some things will fail for users/developers whose len(GOPATH) != 1

### ISSUE THREAD

**Issue by shurcooL** [upspin/upspin#397]
`cmd/go` documentation defines the `GOPATH` environment variable as:

	The GOPATH environment variable lists places to look for Go code.
	On Unix, the value is a colon-separated string. On Windows, the
	value is a semicolon-separated string. On Plan 9, the value is
	a list.

_(Source: https://golang.org/cmd/go/#hdr-GOPATH_environment_variable.)_

If one wants to use `GOPATH` environment variable, it needs to be parsed with [`filepath.SplitList`](https://godoc.org/path/filepath#SplitList) function, or alternatively `build.Import` can be used with [`build.FindOnly`](https://godoc.org/go/build#FindOnly) flag to find a Go package by import path, as seen [here](https://github.com/upspin/upspin/blob/9a1c34f678566d3f62638c4c2b46b219aac1573c/serverutil/frontend/frontend.go#L78).

Yet there are some places in the upspin project codebase that assume the GOPATH list length is exactly 1, and work only under that assumption. If the assumption is violated, a user will face strange errors in the best case, or things may fail in silent ways in the worst case.

For example:

- https://github.com/upspin/upspin/blob/9a1c34f678566d3f62638c4c2b46b219aac1573c/cloud/https/https.go#L57-L58

There may be more, this is not an exhaustive list. I spotted this one when looking over [CL 10263](https://upspin-review.googlesource.com/c/10263/).

I've previously sent change c69ccf62e33da8c60b65fe93140691d88c2b22c0, that helps this issue and demonstrates a good way of resolving it. However, I only addressed some problematic cases that had clean resolutions because the context allowed for handling errors. I left the rest untouched, because the context did not allow for handling errors, and I [wasn't comfortable](https://upspin-review.googlesource.com/c/9441/#message-7341a7164d5fd9e01c907ffcd5b998796dafa2bf) making more significant changes that would be needed there.

There are also some other places that make this assumption, but they're for developers of upspin, not users, so it may be more acceptable (but still bad for prospective contributors that may have 2+ GOPATH workspaces):

- https://github.com/upspin/upspin/blob/3f224d6c4c2b6b3f2877237720726034c894723f/rpc/testdata/proto.go#L6
- https://github.com/upspin/upspin/blob/b7dea2bfbd2580b2e5e545bb3c48bb2759c65d6e/key/testdata/remote/README#L4-L6

I don't know the exact severity of the problem. I just wanted to raise the issue to attention to upspin project authors, I trust they'll triage it appropriately.

**Comment by adg** [comment]
Thank you for the thoughtful and thorough issue report.

>  I left the rest untouched, because the context did not allow for handling errors, and I wasn't comfortable making more significant changes that would be needed there.

I think in [that case](https://github.com/upspin/upspin/blob/9a1c34f678566d3f62638c4c2b46b219aac1573c/cloud/https/https.go#L57-L58) an attempt to use `build.Import` to find package `"upspin.io/rpc"`, with the fallback of just using ".", would be sufficient. It's at least more correct than it is now.

I'm happy to do this, unless you would like to. Let me know.

> There are also some other places that make this assumption, but they're for developers of upspin, not users, so it may be more acceptable

I think these cases are fine. They're seldom-executed commands, and developers with more than one `GOPATH` should know what to do here.

**Comment by shurcooL** [comment]
> I think in [that case](https://github.com/upspin/upspin/blob/9a1c34f678566d3f62638c4c2b46b219aac1573c/cloud/https/https.go#L57-L58) an attempt to use `build.Import` to find package `"upspin.io/rpc"`, with the fallback of just using ".", would be sufficient. It's at least more correct than it is now.

I take it you mean to find the directory of `"upspin.io/rpc"`, and then join it with "testdata/{cert,key}.pem", right?

In case you don't already know, when using `build.FindOnly` flag, the import path doesn't need to point to a valid Go package, it just has to be a directory that exists:

> If FindOnly is set, Import stops after locating _**the directory that should contain**_ the sources for a package. It does not read any files in the directory.

So you could also use `build.Import` to find the directory corresponding to "upspin.io/rpc/testdata" import path, and join that with the filename. Either way would work.

(See https://github.com/bradfitz/go-issue-mirror/pull/14 for more details and an example of this property being used to simplify code.)

> I'm happy to do this, unless you would like to. Let me know.

Go for it, thanks! I'm happy to review.

**Comment by adg** [comment]
> So you could also use build.Import to find the directory corresponding to "upspin.io/rpc/testdata" import path, and join that with the filename.

Ah, I forgot that detail about `FindOnly`. This seems the right move. CL incoming.
