### ISSUE TITLE
errors.E: unqualified path and user overwrite already given ones

### ISSUE THREAD

**Issue by opennota** [upspin/upspin#398]
https://github.com/upspin/upspin/blob/5fdd1f6537f1306a9c832077a3dc5d9b8343c7d1/errors/errors.go#L162

https://github.com/upspin/upspin/blob/5fdd1f6537f1306a9c832077a3dc5d9b8343c7d1/errors/errors.go#L166

I think the ifs should check for equality, not inequality.

**Comment by kavirajk** [comment]
Looks like valid points. Can someone clarify this?

/cc @adg @presotto
