### ISSUE TITLE
upspin signup and keygen should specify curve used when describing recreation

### ISSUE THREAD

**Issue by jekriske-lilly** [upspin/upspin#399]
The upspin signup and keygen should specify the curve used when describing how to re-create the keys. Currently the message reads:

> If you lose the keys you can re-create them by running this command:
	`upspin keygen -secretseed <seed>`

However, this will not generate the same key if the non-default curve was used. 

If the non-default curve was used, I would expect it to read:
> If you lose the keys you can re-create them by running this command:
	`upspin keygen -curve <curve> -secretseed <seed>`

https://github.com/upspin/upspin/blob/master/cmd/upspin/keygen.go#L90

**Comment by n2vi** [comment]
Good point;  I'll fix that.
