### ISSUE TITLE
re-do server

### ISSUE THREAD

**Issue by kristofer** [upspin/upspin#402]
am trying to redo the server after a successful deploy of the linux all-in-one to the filesystem. I decided on on a aws store.
I redid the setdomain=
I did the setupstore-aws

but when I try to redo the setupserver (after having made the upspinserver bin the aws one)
i get

upspin setupserver -domain=mydomain.com -host=upspin.mydomain.com

User "upspin@mydomain.com" already exists on key server.

(of course, mydomain is NOT what I'm using)

any ideas?

**Comment by adg** [comment]
> User "upspin@mydomain.com" already exists on key server.

That's not an error, just a notification. Does it succeed otherwise?

**Comment by kristofer** [comment]
so yes, after doing a 

setupdomain

I start upspinserver (well, upspinserver-aws that has been copied to upspinserver)

when I start the server I get 

2017/06/28 19:53:40.027440 store/server.New: invalid operation:
	cloud/storage.Dial: unknown storage backend type "Disk"
and if I try to do setupserver, I get 
upspin: setupserver: Post https://u.mydomain.com:443/setupserver: dial tcp xx.xx.xx.xxx:443: getsockopt: connection refused

**Comment by adg** [comment]
If you're starting from scratch, you should delete the $HOME/upspin directory and restart upspinserver.

**Comment by kristofer** [comment]
yes. so on replacing a FS based server with AWS S3-backed server...

I had to remove the $HOME/upspin dir, 
also had to then recreate the $HOME/upspin/config file, 

I was able to recreate my key files in ~/.ssh using the line in the email it spent me the first time, after deleting them, since I was unwilling to try to figure out the incantation around how to rotate keys when I generated new ones that were exactly the same as the old ones,

then I had to REMOVE the IAM role "upspinstorage" from the AWS console IAM Role listings (!), since setupstorage-aws was complaining

then I could 
```
$ upspin setupdomain -domain=foo.com
# do the magic with DNS and the TXT record
$ sudo setcap cap_net_bind_service=+ep /usr/local/bin/upspinserver
# which is REALLY upspinserver-aws
$ upspin setupstorage-aws -domain=foo.com foo-upspin1
$ upspinserver&
[1] 21405
2017/06/29 12:50:46.341169 Configuration file not found. Running in setup mode.
2017/06/29 12:50:46.341355 https: serving HTTPS on ":443" using Let's Encrypt certificates

$ upspin setupserver -domain=foo.com -host=upspin.foo.com
2017/06/29 12:50:53.129810 Store and Directory servers initialized.
2017/06/29 12:50:53.129989 Store server configuration: backend=S3 defaultACL=public-read s3BucketName=foo-upspin1 s3Region=us-east-1
Configured upspinserver at "upspin.foo.com:443".
...and some more msgs...
```
which were all "good dog, you get a biscuit" messages and left the server running...

**Comment by adg** [comment]
@kristofer any suggestions as to how we could make our docs clearer?
