### ISSUE TITLE
cmd/upspinfs: Delete from file store.

### ISSUE THREAD

**Issue by Splizard** [upspin/upspin#404]
When I delete a file being served by upspinfs, I expect the file to be deleted from the upspin file store.
I had a look at the code and there is a comment.
```
// Delete from the directory (but not the store).
_, err = dir.Delete(uname)
```
This seems rather counter intuitive. Why would I want to delete the reference and not the data?

The upspin StoreServer interface has a delete method.
```
type StoreServer interface {
        // Delete permanently removes all storage space associated
	// with the reference. After a successful Delete, calls to Get with the
	// same reference will fail. If the reference is not found, an error is
	// returned. Implementations may disable this method except for
	// privileged users.
	Delete(ref Reference) error
}
```
I am a privileged user so I would expect my files can be deleted when I delete the reference.

**Comment by Splizard** [comment]
Here is a patch which enables deletion of files from the StoreServer.
```go
--- cmd/upspinfs/fs.go
+++ cmd/upspinfs/fs.go
@@ -445,6 +445,34 @@
 	} else {
 		if de.IsDir() {
 			return e2e(errors.E(op, errors.IsDir, uname))
+		}
+	}
+	
+	//Delete data from the store.
+	direntry, err := n.f.client.Lookup(uname, true)
+	if err != nil {
+		return e2e(errors.E(op, uname, err))
+	}
+	
+	var storeserver upspin.StoreServer
+	var endpoint upspin.Endpoint
+	
+	for _, block := range direntry.Blocks {
+		//It may be possible for the blocks to be at different endpoints.
+		if block.Location.Endpoint != endpoint {
+			endpoint = block.Location.Endpoint
+			storeserver, err = bind.StoreServer(n.f.config, endpoint)
+			if err != nil {
+				return e2e(errors.E(op, uname, err))
+			}
+		}
+
+		err := storeserver.Delete(block.Location.Reference)
+		if err != nil {
+			return e2e(errors.E(op, uname, err))
 		}
 	}
```

**Comment by robpike** [comment]
We expect to garbage-collect storage. The problem with doing it when the DirEntry is deleted is that if the reference is a hash of the data, that is, if the store is content-addressed, you may easily delete a block that is part of an existing file. (It may happen in other circumstances, but this is one common scenario.)

The separation of Store and Dir servers means that there is no simple 1:1 correspondence. What you propose will often be safe, but not provably so. We have chosen instead to be much more circumspect about deleting blocks from the StoreServer.

**Comment by adg** [comment]
There is the 'upspin deletestorage' command for deleting the underlying
references of a directory entry.
