### ISSUE TITLE
upspin: should use int32 counts, not int

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#405]
The marshaling code in upspin/code.go uses int, but that means that overflow can occur when a valid message is sent from a 64-bit machine to a 32-bit one. If the code used int32, this would not happen. It's OK to do so, but care must be taken elsewhere to be sure we never create a 2GB+ block.

**Comment by kavirajk** [comment]
which means, have to convert the return value of `binary.PutVarint()` to `int32` everywhere in the marshaling code of both `DirEntry` and `DirBlock`?

Can I work on this?

**Comment by robpike** [comment]
I think it's deeper than that because you also need to make sure some values themselves never exceed 2**31. The likely way to make an error like this is well before marshaling time.

I was planning to handle this one myself. It's subtler than it looks.

**Comment by kavirajk** [comment]
Thanks for the clarification :+1:
