### ISSUE TITLE
exp: move upspin.io/exp to separate repository

### ISSUE THREAD

**Issue by adg** [upspin/upspin#407]
I propose that we create a new exp.upspin.io repository and move the packages under upspin.io/exp to it. The packages under exp/ introduce several new dependencies:

```
github.com/dgryski/go-linebreak
github.com/golang/protobuf/ptypes
github.com/golang/protobuf/ptypes/any
github.com/golang/protobuf/ptypes/duration
github.com/golang/protobuf/ptypes/timestamp
github.com/google/go-github/github
github.com/google/go-querystring/query
github.com/gregjones/httpcache
go4.org/types
golang.org/x/build/cmd/pubsubhelper/pubsubtypes
golang.org/x/build/maintner
golang.org/x/build/maintner/maintpb
golang.org/x/build/maintner/reclog
golang.org/x/oauth2
golang.org/x/oauth2/internal
golang.org/x/sync/errgroup
net/http/httputil
```

I intend to resolve #214 by vendoring the dependencies in repository upspin.io. We can avoid vendoring the packages above by first removing upspin.io/exp.

To that end, I have sent: https://upspin-review.googlesource.com/10462

It is out for review, but won't be submitted until after we have we decided to go ahead and created the new repository.

**Comment by robpike** [comment]
Sounds good to me.

**Comment by adg** [comment]
I created https://github.com/upspin/exp and populated it. I'll wait for consensus before removing exp from the upspin repo.

**Comment by n2vi** [comment]
ok by me
