### ISSUE TITLE
release: the darwin_amd64 upspinfs binary is broken

### ISSUE THREAD

**Issue by adg** [upspin/upspin#413]
I suspect this is something to do with it being built inside a Linux Docker container. Will investigate.

**Comment by adg** [comment]
Strange behavior here.

After starting up the `upspinfs` binary from the release tree, the first HTTPS request fails trying to look up my user root: 

```
2017/07/07 01:07:21.403325 dir/remote.Dial("unassigned")("nf@wh3rd.net", "remote,upspin.adg.tech:443")
2017/07/07 01:07:21.403419 dir/remote.Lookup("remote,upspin.adg.tech:443")("nf@wh3rd.net/")
2017/07/07 01:07:31.888598 dir/remote.Lookup("remote,upspin.adg.tech:443")("nf@wh3rd.net/") error: I/O error:
	rpc.Invoke: Post https://upspin.adg.tech:443/api/Dir/Lookup: net/http: TLS handshake timeout
2017/07/07 01:07:31.888647 nf@wh3rd.net/: upspinfs/fs.Lookup: I/O error:
	dir/remote.Lookup("remote,upspin.adg.tech:443"):
	rpc.Invoke: Post https://upspin.adg.tech:443/api/Dir/Lookup: net/http: TLS handshake timeout
	dir/remote.Lookup("remote,upspin.adg.tech:443"):
	rpc.Invoke: Post https://upspin.adg.tech:443/api/Dir/Lookup: net/http: TLS handshake timeout
```

As a result, I can't cd into my tree. However, subsequent HTTPS requests succeed and I am able to browse other trees (such as `augie@upspin.io`).

**Comment by adg** [comment]
I may have found the source of the problem.

The release build process builds the binaries without [cgo](https://golang.org/cmd/cgo/). The `crypto/x509` package is responsible for reading the system root certificates, and there are two darwin implementations: one that uses cgo to call the macOS Security framework directly, and one that invokes `/usr/bin/security` to obtain the information (without using cgo).

On our workstations we typically build with cgo enabled. I tried building upspinfs without cgo and found that on the first TLS request the x509 package invokes this command:
```
/usr/bin/security trust-settings-export
```
which stalls for 20 seconds, during which time any pending TLS connections will time out. Once that command returns, TLS starts working properly.

I'm now going to try to understand why that command takes so long, and whether it's specific to our use of TLS or if it's an issue in Go's standard library.

**Comment by adg** [comment]
Based on golang/go#19561, it looks like it's not Upspin, but rather it's crypto/x509 on darwin without cgo. The underlying issue there looks to be in Apple's court, and based on past experience I wouldn't expect it to be resolved any time soon. That's my analysis, though. It'd be great to hear from somewhere else.

In the absence of fixing the root issue, we could try to build our darwin releases with cgo enabled. I found [xgo](https://github.com/karalabe/xgo) which looks like it would provide the environment we need to do this. I'll take a look at using this in our release process.

**Comment by amygdala** [comment]
@adg 
hi Andrew, do you think this is fixed?  I've hit something that sounds very much like it even when not running upspinfs:
```
$upspin ls <my_email>/  
upspin: ls: client.Lookup: I/O error:
	dir/remote: "remote,<server>.upspin.services:443": dir.Lookup:
	rpc.Invoke: Post https://<server>.upspin.services:443/api/Dir/Lookup: net/http: TLS handshake timeout
```
I got the same error in the web ui, unsurprisingly.

but then this works fine:
```
$ upspin ls augie@upspin.io
augie@upspin.io/Access
augie@upspin.io/Group/
augie@upspin.io/Images/
augie@upspin.io/Security/
augie@upspin.io/Team/
```
The context:
I had *just* installed upspin & set up a server, then started `upspinfs`.  All worked fine initially, then started acting up about 30 mins later.  It's possible that in the interim my machine went to sleep with the fuse dir mounted.
A reboot didn't help, even though I did not restart upspinfs after the reboot (and removed `cache: yes` from the config file)
 I saw this with both the downloaded binaries and those built from source.
(haha, my destructo superpowers strike again).

I'm running: macOS 10.13.1, and the latest fuse from: https://github.com/osxfuse/osxfuse/releases

(My 'fix': I deleted my server vm (which didn't have much on it) and created another one, which is behaving well using the `upspin` CLI.  I'm holding off on starting `upspinfs` with the new server for now though.)

**Comment by adg** [comment]
What happens if you just visit https://<server>.upspin.services in your web browser? Do you see "not found" (what we want to see) or something else?

**Comment by adg** [comment]
Oh, I see you've fixed it. I'm not sure why that would have happened. If the upspin CLI is working then I wouldn't hesitate to try upspinfs. I don't see how the error could have been related.

**Comment by amygdala** [comment]
I don't see either, but I was suspecting it was might be osxfuse-triggered b/c I am pretty sure something related was causing trouble (my Finder app became completely hosed as well, which I have seen previously when using osxfuse, albeit with diff OS and fuse versions).  

To be clear, things were working fine with just the CLI prior to this.
That doesn't explain why a reboot didn't clear things up though.  
Okay, I will try upspinfs again.

**Comment by adg** [comment]
@amygdala huh, that is interesting. Did you see anything incriminating in the server logs?

**Comment by amygdala** [comment]
No, not to my eyes-- just more of the same, e.g.:
```
2017/11/25 14:26:39 startup: request: {}
2017/11/25 14:26:49 startup: error: error communicating with "<server_name>.upspin.services:443":
dir/remote: "remote,<server_name>.upspin.services:443": dir.Lookup: I/O error:
        rpc.Invoke: Post https://<server_name>.upspin.services:443/api/Dir/Lookup: net/http: TLS handshake timeout
2017/11/25 22:27:45.090177 shutdown: process received signal interrupt
```
Well, everything's behaving with my new server so far... if it happens again I'll try to do more useful diagnosis.
