### ISSUE TITLE
cmd/upspin: signup fails to write keys if ~/.ssh directory doesn't exist

### ISSUE THREAD

**Issue by JackMordaunt** [upspin/upspin#418]
On both Windows and OSX I attempted the following:
`upspin signup -dir=dir.upspin.io -store=store.upspin.io jackmordaunt@gmail.com`.

The result was an error:
`upspin: signup: writing keys: open <user>/.ssh/secret.upspinkey: no such file or directory`

Once I manually created the `.ssh` folder in my home directory, everything works as expected.
Would it be more usable for upspin to create the `.ssh` folder, rather than returning an error?
Upspin seems to be making the assumption that the user has used `.ssh` before and thus the directory must already exist, which is not always the case, unless I'm missing something.

###### Side Note: The contribution guidelines recommend providing the upspin version when filing issues. I had a look but couldn't find any obvious version information. Perhaps `upspin version` command would be useful.

**Comment by adg** [comment]
I'm not 100% happy with `$HOME/.ssh` being the location for the keys, but that decision predates me.

I think the fix is to just make the directory if it doesn't exist.

**Comment by n2vi** [comment]
I'm not 100% happy with  $HOME/.ssh either, and I'm the one to blame for not being able to think of something better yet.   If os or crypto had an interface to the various native key managers on different systems, I'd prefer that.   On Windows, this would probably talk to a "cryptographic provider" and certainly not create .ssh/.

My hope from the beginning has been that SecurityKey would provide a mechanism replacing the upspinkey files, but no progress on that yet.

In the meantime, I'm happy with adg's fix.
