### ISSUE TITLE
config: drop support for config by environment variable?

### ISSUE THREAD

**Issue by adg** [upspin/upspin#423]
The [config package](http://godoc.org/upspin.io/config#InitConfig) says:

> Environment variables named "upspinkey", where "key" is a recognized configuration key, may override configuration values in the config file.

Does anyone actually use this? It seems like a great way to get confused, when your config file says one thing but you forgot (or never knew) that environment variables were set.

I propose removing this feature, unless someone is actually using it.

**Comment by robpike** [comment]
I used it once. I think you're right that it's more confusing than it's worth.

**Comment by n2vi** [comment]
+1
