### ISSUE TITLE
upspin: 'directory not empty' failure on directories named with square brackets

### ISSUE THREAD

**Issue by jekriske-lilly** [upspin/upspin#424]
I first mentioned this error in #412

This is with upspin servers and even the latest build. I do a mount via osxfuse, I drag over a certain folder containing 195 MB of videos and python scripts. It takes a few seconds to complete. Once complete, the directory is empty according to fuse and doing a straight `upspin ls` from the terminal shows the directory empty as well. At this point, the directory cannot be deleted via a delete in OSX because it claims it's in use or via `upspin rm -R -f` because it claims `upspin: rm: client.Delete: directory not empty` The contents of the directory do not matter and this occurs even when the directory contains a single text file.

I believe it has to do with the directory name `Machine Learning with TensorFlow [Video]` I've tried another directory and it worked just fine. As a matter of fact, if I add a word with square brackets to the directory name it experiences the same behavior (at least for me).
For example, a directory with contents named `house pics` works fine while `house pics [test]` does not.

Starting and stopping the upspin server has no effect and it will not cause the children of this directory to appear.

The only method I have for removing the directory is by restoring the upspin server directory, on the server itself, to a previous state.

**Comment by adg** [comment]
One thing that strikes me is that `[]` are glob metacharacters as defined by [path.Match](https://golang.org/pkg/path/#Match). Curious.

cc @presotto

**Comment by robpike** [comment]
That's almost certainly the key detail. The question is, where is it applied erroneously. Perhaps glob is being called somewhere with a literal path.

**Comment by adg** [comment]
To list a directory we usually do Glob(path+"/*"), so maybe that's the culprit.

**Comment by robpike** [comment]
That would be it. Need to use QuoteGlob.

**Comment by robpike** [comment]
upspin.AllFilesGlob does the right thing. We need to use it more. Still haven't identified the location of the trouble, though.

**Comment by robpike** [comment]
I can reproduce the problem. Looking into it.

**Comment by presotto** [comment]
At least I can remove files in such a directory by cd'ing to it and and rm'ing each.  Have to know the names ahead of time though.  Pretty obvious mistake...  I'll change upspinfs to use AllFilesGlob...

**Comment by presotto** [comment]
Well, AllFiles didn't fix upspinfs.  Looking...

**Comment by adg** [comment]
It's not just Upspinfs. There was a bug in serverutil/glob too, which should now be fixed by cc2f312388ce3cf6dcbacb283acd942272da302e.

**Comment by robpike** [comment]
Testing shows it looks fixed. Please reopen if you can reproduce it past cc2f312.

**Comment by adg** [comment]
(Note that both a client and server upgrade are required to observe the fix.)
