### ISSUE TITLE
cmd/upbox: mysterious failure setting up 

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#426]
% cd upspin.io/cmd/upspin
% go test
storeserver:	2017/07/14 03:32:33.344154 serverutil/perm.WrapStore: dir/Server.Lookup: invalid operation: request to unassigned service
storeserver:	2017/07/14 03:32:33.344193 serverutil/perm.WrapStore: watch: not supported
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x143af7e]

goroutine 141 [running]:
testing.tRunner.func1(0xc4202b4780)
	/Users/r/go/src/testing/testing.go:712 +0x2dc
panic(0x14b4bc0, 0x17e1d00)
	/Users/r/go/src/runtime/panic.go:491 +0x283
upspin.io/subcmd.(*State).SetIO(...)
	/Users/r/src/upspin.io/cmd/upspin/cmd_test.go:145
upspin.io/cmd/upspin.(*runner).run.func1(0xc4202b4780)
	/Users/r/src/upspin.io/cmd/upspin/cmd_test.go:145 +0x9e
testing.tRunner(0xc4202b4780, 0xc4206d9d80)
	/Users/r/go/src/testing/testing.go:747 +0xd0
created by testing.(*T).Run
	/Users/r/go/src/testing/testing.go:790 +0x2de
exit status 2
FAIL	upspin.io/cmd/upspin	2.784s

Here I believe that the upbox has failed to set up properly, or perhaps there is a race.

**Comment by adg** [comment]
The string upbox is not in that stack trace at all. I don't think this is related to upbox.

**Comment by robpike** [comment]
Closing but if I see it again I'll create a new issue better characterized.
