### ISSUE TITLE
dir/server: snapshot creation should block until snapshot is created

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#428]
The magic MakeDirectory("TakeSnapshot") that creates a snapshot directory for a user returns immediately. It spins off the creation and returns successfully. This makes it impossible to know when the backup exists (if it ever does!).

I propose it blocks until the snapshot is actually created, for some definition of created.

**Comment by adg** [comment]
> This makes it impossible to know when the backup exists (if it ever does!).

It's not impossible to know; if you watch the snapshot tree you will see it created. That's how the snapshot tests in package `upspin.io/test` work.

But I agree that this is how it *should* work.

**Comment by edpin** [comment]
The goroutine was used because it's a "deamon" that periodically takes snapshots. There is no technical reason it can't block when asked directly by the magic.

**Comment by robpike** [comment]
I think watch is overkill. MakeDirectory blocks until the directory is made, and snapshot should too, as it's just a fancier MakeDirectory.
