### ISSUE TITLE
keyserver: document clearly that you must not lose your keys after signup

### ISSUE THREAD

**Issue by adg** [upspin/upspin#429]
A user recently posted [a message](https://groups.google.com/d/msg/upspin/KPoXgbVlPIU/pKLCtYJ4AQAJ) about how they registered a user with the key server and then subsequently lost the keys. I think this is likely a common situation for people experimenting with Upspin. The way things work right now, the user is out of luck. The user name they registered is lost forever, along with the keys.

Should we have some kind of protocol/mechanism for resetting the keys for a particular user? It must require admin intervention and some kind of reliable proof-of-ownership of the name. Perhaps also a requirement that the name has not been used for anything? (Although there's no easy way for us to know that, right now.)

@n2vi what do you think?

**Comment by n2vi** [comment]
That is fraught with difficulty.  Account recovery is usually the weakest
link in cryptographic identity systems.

Specifically, the threat scenario is Mallory convinces keyserver
administrator Andrew that Bob has lost his keys and wants to use a new
set.  Later, Alice shares a secret file that only she and Bob should see.
Bob can't read it, but Mallory can.   Bob may not even know any of this is
going on.

So we say pretty loudly during signup that you really really need to save
that recovery code.  The naive first-time user has no recourse except to
sign up with a new email address, which is bad but not catastrophic.  If a
long-time user lost their keys, they're never going to get their old file
contents back, which could indeed be catastrophic.   If people are ignoring
our initial warning, maybe we need to shout even louder?

**Comment by n2vi** [comment]
There is a related question of changing domain ownership, even if no user keys were lost.

This is almost as dangerous and I would prefer not to introduce additional mechanism.  Simplicity is your friend when you're worried about security.  Still, I'm willing to listen to domain proposals, as I think this mainly puts at risk domain expenses, not user data, and would be reversible.  But definitely no administrative reset of user keys.

**Comment by robpike** [comment]
Fixed by https://upspin-review.googlesource.com/11281
