### ISSUE TITLE
dir,store: inprocess is redundant

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#431]
@presotto  asked why we need to update two `DirServer` and two `StoreServer` implementations instead of them both sharing common code.

We started digging and turns out both inprocess servers are completely redundant since `dir/server` and `store/server` can both write to memory with minor modifications.

`store/server` can already make use of a `storage.Storage` implementation that writes to memory and that makes `store/inprocess` obsolete once we implement that option.

`dir/server` can use a `store/server` configured to store in-memory (as per above) and the only additional change needed would be to make the logs write to a memory location. This can be trivially accomplished on Linux by pointing the config option `logDir` to a `/dev/shm` location. Other operating systems will likewise have RAM disks too.

This cuts the duplication of code down somewhat if we can delete `{dir,store}/inprocess`.

**Comment by adg** [comment]
IIUC the purpose of multiple implementations is not for functional purposes, but so that one particular implementation does not become the spec. Having two implementations has caught many assumptions and inconsistencies in the Upspin interfaces, and bugs. I don't see a significant cost in keeping the inprocess versions around.

**Comment by adg** [comment]
cc @robpike

**Comment by edpin** [comment]
We already have a few dynamic dirserver implementations and the dircache. So the "not-a-spec" argument does not apply.

inprocess adds nothing but having to type mostly-similar code twice. The time it was useful was in the early days, when the dir/server was being built and ironed out. Now, it has become a hindrance of sorts.

I think we should get rid of it.

**Comment by adg** [comment]
> We already have a few dynamic dirserver implementations and the dircache. So the "not-a-spec" argument does not apply.

None of the dynamic DirServer implementations are at all similar in scope to an actual read/write DirServer, with all the access control restrictions etc.

**Comment by robpike** [comment]
The argument is indeed as @adg states. Two independent implementations requires more upkeep, yes, but also helps guarantee consistent, spec-matching behavior. There have already been multiple occasions where discrepant behavior between the two has indicated a lapse of understanding.

I am in favor of keeping the inprocess ones around. They are simple (at least, key and store are) and easy to maintain.
