### ISSUE TITLE
key/server: disentangle from GCP storage backend

### ISSUE THREAD

**Issue by adg** [upspin/upspin#434]
The key/server implementation currently sets up its own storage backend and it's hard coded to use GCS. We should instead take a storage.Storage in the constructor, so that in-memory storage can be used in tests.

cc @robpike

**Comment by robpike** [comment]
Yes. It would make it much easier to use the real keyserver code in end-to-end tests.

**Comment by robpike** [comment]
If this leads to deleting the inprocess implementation of keyserver, it would be nice to keep the ability to say
key: inprocess
with no other mess in the config file. It might require a stub version somewhere that builds the relatively complex argument list for the (only) available implementation to keep it memory-only.

I remain a little nervous of tests corrupting or even touching the public keyserver.

**Comment by adg** [comment]
> I remain a little nervous of tests corrupting or even touching the public keyserver.

If our tests can corrupt the production key server then something is seriously wrong.

**Comment by robpike** [comment]
My point exactly.
