### ISSUE TITLE
serverutil/keyserver: add ability to stub out mail sending

### ISSUE THREAD

**Issue by adg** [upspin/upspin#435]
To test the signup process we need to stub out the part that sends mail and instead capture that mail. It's currently hardwired to use SendGrid. The constructor of the signup part should take a mail.Mail implementation, and we can pass a test implementation when testing.

**Comment by kavirajk** [comment]
@adg the intention is to test `keyserver.Main()`? 
I'm bit confused about what you mean by "constructor of signup part". the `signup.NewHandler` already take `signup.MailConfig`(that include `mail.Mail`) as argument.

If i'm not wrong, we could make `keyserver.Main()` to have extra argument of type `mail.Mail` which can be used as `mail.Mail`(if not `nil`) in `signup.MailConfig` before calling `singup.NewHandler`?

**Comment by adg** [comment]
I think this work is already done, actually. If you don't supply the `-mail_config` flag then you don't set up a mailer. Will reopen if you disagree.

**Comment by kavirajk** [comment]
@adg thanks for the explanation. I see we don't setup the mailer if no flag. But then still we couldn't capture in the tests. My point is still we cannot pass our own mailer to capture the mail similar to the one we use here https://github.com/upspin/upspin/blob/master/serverutil/signup/signup_test.go#L133-L140

I thought the intention is to do that correct me if I'm wrong.

**Comment by adg** [comment]
I think the intention was to test serverutil/signup, which we can do now.
