### ISSUE TITLE
cmd/upspinfs: `ln -s` fails when the first argument is a relative path

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#439]
```
$ cd /u/$ME
$ ln -s ../release@upspin.io UpspinRelease
$ readlink UpspinRelease
release@upspin.io
$
```

The bug is that `upspinfs` has seemingly stripped the `../` prefix.

**Comment by presotto** [comment]
Symlinks in general work from within your dir server.  However, it looks like I screw up the path when the symlink ..'s out the top of your dirserver.  I'll try to figure it out.

**Comment by presotto** [comment]
fixed by https://upspin-review.googlesource.com/c/11500/
