### ISSUE TITLE
cmd/upspinfs: touch fails to update the mtime 

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#440]
```
$ cd /u/$ME
$ ls test
ls: test: No such file or directory
$ touch test
$ ls -l test
-rwx------  1 jacekm  staff  0 Jul 22 13:39 test*
$ sleep 10
$ touch test
$ ls -l test
-rwx------  1 jacekm  staff  0 Jul 22 13:39 test*
$ 
```

The bug is that mtime has remained unchanged despite a follow-up touch.

This prevents synchronization commands such as `rsync -a` from applying the optimization that skips transfers of files if both places already have a file with matching path, mtime and size.

**Comment by n2vi** [comment]
See TODO question at line 616 of cmd/upspinfs/fs.go.  I've argued the
answer is yes, and not just temporarily like upspinfs mode bits but
actually change the upspin.DirEntry.Time field and update the signature in
Packdata.

It is on my personal todo list, but ranked below some other things.

On Sat, Jul 22, 2017 at 1:49 PM, Jacek Masiulaniec <notifications@github.com

**Comment by presotto** [comment]
I just started on it.  Basically have to change the time and repack the DirEntry.  I think I have to introduce a SetTime func in the packers to make it possible.
