### ISSUE TITLE
rpc/cache.go: cacheserver launched via upspinfs is unreachable

### ISSUE THREAD

**Issue by bkono** [upspin/upspin#443]
It is entirely possible I'm missing something in my setup, but since the refactoring of config, specifically affecting the CacheEndpoint in commit: https://github.com/upspin/upspin/commit/fa5dd3098e50b192a5b26a6495f12768f38137c0#diff-34af8096fcb1fee8ec7f214de49004e8 utilizing the automatically launched cacheserver no longer works. 

After a brief investigation, it appears that during the move to `rpc/cache.go` the endpoint's local NetAddr was not preserved. Previously it would pass through the `inticonfig.go` parseEndpoint, which would prefix it with "remote," and suffix it with a default port of ":443". I attempted to mimic this on my fork, https://github.com/bkono/upspin/commit/ea57fe3d01b35c51d18d560043f8767287763637. It appears to fix the issue, allowing the cacheserver kicked off by upspinfs to be pinged and proceed normally. Given the ability to pass through a specific addr was also nixed due to the switch statement only supporting yes or default, this seems like a direct way to address the bug. If I'm off, or just missing something in my setup, please let me know.

**Comment by presotto** [comment]
We're moving away from the old 'you supply the address' to just yes/no and use unix domain sockets.  Unless you have a strong reason not to, just use:

cache: yes

in your config and everything should work.  I left a way to still specify it as a tcp port, i.e., what you guessed but, in general, its faster to just let it use unix domains.

As I understand your message, my change was not backward compatible if one elided the remote, and :443.  I guess I should fix this so it doesn't trip anyone else up but its not high on my list so it might be a while.

**Comment by bkono** [comment]
Actually, it wasn't functional at all using `cache: yes`, which is what was and currently is in my config (and working) prior to that commit. It didn't appear to use IPC for the ping process, before or after the refactor.

Environments where I'm experiencing it are macOS 10.12.5, and Ubuntu 16.04 LTS, with commit hash as recent as 55d26033. Which is why I thought it might somehow be related to my personal configuration, but on reviewing the code, I didn't quite see where a local dialer was used that would have triggered IPC on the `cacheutil/start` ping, and from what I could tell with a little investigation on the previously working commit, after passing through inticonfig.go's CacheEndpoint/SetCacheEndpoint, `cache: yes` always resulted in a NetAddr of `remote,foo.example.com.localhost:443` which it no longer does.

Without the change to setup the NetAddr to match in rpc.CacheEndpoint, the cacheutil/start will launch a cacheserver process, but never succeed at pinging it (IPC or otherwise). Is there anything additional that would be necessary to ensure that ping is happening over domain sockets?

**Comment by bkono** [comment]
Sorry, should have included logs. Off previously mentioned commit hash, `upspinfs -log debug /up`

```
2017/07/27 22:09:01.817649 dir/remote.Dial("unassigned")("bryan@REDACTED", "remote,upspin.REDACTED:443")
2017/07/27 22:09:01.817665 dir/remote.Dial("unassigned")("bryan@REDACTED", "remote,upspin.REDACTED:443") error: invalid operation:
        rpc.CacheEndpoint: internal error: unknown transport type in endpoint "bryan.REDACTED.cacheserver.localhost."
2017/07/27 22:09:01.817681 dir/remote.Lookup("remote,upspin.REDACTED:443")("bryan@kREDACTED/")
2017/07/27 22:09:02.088048 Attr bryan@REDACTED/ 0x2
```

**Comment by presotto** [comment]
We're all using cache: yes so I'm kind of confused.  Could you send my your
config?

**Comment by HeavyHorst** [comment]
I have the same issue after updating to the newest release:

```
2017/08/15 10:35:19.167224 dir/remote.Dial("unassigned")("rene@REDACTED", "remote,upspin.REDACTED:443")
2017/08/15 10:35:19.167250 dir/remote.Dial("unassigned")("rene@REDACTED", "remote,upspin.REDACTED:443") error: invalid operation:
        rpc.CacheEndpoint: internal error: unknown transport type in endpoint "rene.REDACTED.com.cacheserver.localhost."
2017/08/15 10:35:19.167274 dir/remote.Lookup("remote,upspin.REDACTED:443")("rene@REDACTED/")
```

Config:
```
username: rene@REDACTED
secrets: /home/rkaufmann/.ssh
storeserver: remote,REDACTED:443
dirserver: remote,REDACTED:443
packing: ee
cache: yes
```

**Comment by HeavyHorst** [comment]
upspinfs --version                                                                                                                                           
Build time: Aug  9 06:23:27 UTC
Git hash:   54a9e56ae89ad97cff88e6655ecd84f25dc53266

**Comment by adg** [comment]
Looking into this. I think I broke it with fa5dd3098e50b192a5b26a6495f12768f38137c0.

**Comment by adg** [comment]
Sorry to everyone that was affected by this. I believe it is fixed now. Please update to the latest Upspin version and try again.
