### ISSUE TITLE
upspin: sequence number inconsistency on Put through dircache

### ISSUE THREAD

**Issue by presotto** [upspin/upspin#445]
When we do a Put to a directory server we know the contents of the DirCache entry put except for the resulting sequence number. This means that until a concurrent Watch returns the newly Put DirEntry complete with seqno, any cached DirEntry is incorrect.

A possible solution is to always return an attribute==Incomplete DIrEntry to the put that does contain the sequence number.  That way we can immediately cache the correct result.

**Comment by robpike** [comment]
This will be fixed along with the work on #444.
