### ISSUE TITLE
cmd/cacheserver: cache exceeding limits

### ISSUE THREAD

**Issue by foolusion** [upspin/upspin#452]
I did an `upspin cp -R . foolusion@gmail.com/photos`while using the cacheserver and I noticed upspin is making copies of all my files currently around 20GB in my `$HOME/upspin/storecache`. Should there be a way to limit this or am I missing some config? It looks like the cachesize for the upspin command should be defaulting to 5GB max according to `upspin -help`.

**Comment by adg** [comment]
Sound like a bug to me.
