### ISSUE TITLE
cmd/browser: "Beta testers requested" email confirmation failure

### ISSUE THREAD

**Issue by fgergo** [upspin/upspin#464]
32bit windows 7
latest chrome

1. doc should maybe start with: "If you don't have upspin yet, please install: go get upspin.io/cmd/..." then "go get exp.upspin.io/cmd/browser"
2. "Upspin signup confirmation" email link results in browser:
could not create user: key/server.Put: invalid operation:
	valid.User:
	valid.Endpoint: "remote,": missing network address
[browser.log](https://github.com/upspin/upspin/files/1339688/browser.log)

**Comment by yansal** [comment]
I got the same message at the "Verify your email address" step:

```
could not create user: key/server.Put: invalid operation:
	valid.User:
	valid.Endpoint: "remote,": missing network address
```

[browser.log](https://github.com/upspin/upspin/files/1339760/browser.log)

**Comment by adg** [comment]
Could one of you please supply a screenshot?

It's strange that the error message is not present in either of the log files you supplied. Hm.

**Comment by fgergo** [comment]
Not sure, which screenshot you need, I attached 2 from browser.
+the command line looks like this:
C:\Users\fgergo>browser
Serving at http://localhost:8000/#key=6977f39be43c64b9f83d80482da58da338b386676c4475d042202ac1a60ceab2



![browser_htmlsource_screenshot](https://user-images.githubusercontent.com/5156576/30954999-6e3c8c9a-a432-11e7-9c88-19113e26bb78.png)
![browser_screenshot](https://user-images.githubusercontent.com/5156576/30954990-6853f43a-a432-11e7-99c1-407a02b498e7.png)

**Comment by adg** [comment]
@fgergo @yansal thank you both for your feedback. I believe I have fixed this now. Would you care to try again?

**Comment by fgergo** [comment]
for me it's working fine, thanks!

**Comment by yansal** [comment]
working fine too 👍
