### ISSUE TITLE
cmd/browser: initial GCP setup rateLimitExceeded

### ISSUE THREAD

**Issue by joerocklin** [upspin/upspin#466]
I'm setting up clean environment on GCP, and after getting the sign-up process, getting the project created, and the JSON credentials in place, I get the following error:
```
googleapi: Error 429: Insufficient tokens for quota 'DefaultGroup' and limit 'CLIENT_PROJECT-100s' of service 'servicemanagement.googleapis.com' for consumer 'project_number:425422204877'., rateLimitExceeded
```
I can provide the log if desired, but the only message after the `specifyGCP` action is the above message with a timestamp.

**Comment by joerocklin** [comment]
Waiting a while and then trying again and it worked the second time.

**Comment by adg** [comment]
Would you mind attaching your $HOME/upspin/log/browser.log file? Thanks.

**Comment by joerocklin** [comment]
At the time of this error, the log was:

```
2017/09/28 08:42:55 startup: request: {
	"key": ["97dc34fef5f2947722780b6cd86f0167cd3df30f243b784e3658a8191b0ff5a1"],
	"action": ["signup"],
	"username": ["joe.rocklin@gmail.com"]
}
2017/09/28 08:42:56 startup: response: {
	"Step": "secretSeed",
	"KeyDir": "/home/joe/.ssh/joe.rocklin@gmail.com",
	"SecretSeed": "REDACTED",
	"UserName": "joe.rocklin@gmail.com"
}
2017/09/28 08:43:45 startup: request: {
	"key": ["97dc34fef5f2947722780b6cd86f0167cd3df30f243b784e3658a8191b0ff5a1"]
}
2017/09/28 08:43:46 startup: response: {
	"Step": "verify",
	"UserName": "joe.rocklin@gmail.com"
}
2017/09/28 08:44:22 startup: request: {
	"key": ["97dc34fef5f2947722780b6cd86f0167cd3df30f243b784e3658a8191b0ff5a1"]
}
2017/09/28 08:44:22 startup: response: {
	"Step": "serverSelect"
}
2017/09/28 08:48:47 startup: request: {
	"privateKeyData": ["REDACTED"],
	"key": ["97dc34fef5f2947722780b6cd86f0167cd3df30f243b784e3658a8191b0ff5a1"],
	"action": ["specifyGCP"]
}
2017/09/28 08:49:25 startup: error: googleapi: Error 429: Insufficient tokens for quota 'DefaultGroup' and limit 'CLIENT_PROJECT-100s' of service 'servicemanagement.googleapis.com' for consumer 'project_number:425422204877'., rateLimitExceeded
```

**Comment by adg** [comment]
How long was the interval between your [setting up billing for the project] and [uploading the JSON credentials and clicking Proceed]?

**Comment by joerocklin** [comment]
I don't remember precisely, but when I created the project it already had billing connected. So there was some time between creating the project and verifying billing, then downloading the json keys and uploading them to the browser.

**Comment by adg** [comment]
I think I have [a fix](https://upspin-review.googlesource.com/#/c/exp/+/13500).  Thanks for the feedback!
