### ISSUE TITLE
cloud/storage: implement Dropbox storage backend

### ISSUE THREAD

**Issue by mazebuhu** [upspin/upspin#468]
It would be nice if Dropbox could be used as storage backend. This would allow users which have and maybe already pay for Dropbox to use it as backend for Upspin without the need to pay an other cloud storage provider. 

The implementation, I think, should only focus to use Dropbox as "plain" storage backend and not try to make already present data available in Upspin.

I would be happy in contributing this part to the project.

**Comment by adg** [comment]
Great! The approach is the same as #225 and #273 (which is done, and I now need to create the repo).

First step is to develop a version of the gcp.upspin.io or aws.upspin.io repos for dropbox, test it to make sure it all works, and then we can create an "official" dropbox.upspin.io repository.

**Comment by mazebuhu** [comment]
I have already a working implementation which I personally use. I used gcp.upspin.io and aws.upspin.io as boilerplate.

The implementation currently focuses only on the Dropbox User Endpoints, not Business Endpoints. (Do not if that makes sense to support anyway). I'm relatively new to Go, so I would appreciate to get feedback on the implementation and to further improve it.

**Comment by adg** [comment]
Happy to look at the implementation. Where is it?

**Comment by mazebuhu** [comment]
I have created an repo here: https://github.com/mazebuhu/upspin-dropbox

Some notes on the implementation:

- It does not use any third library for make the API request, since there is no official Go SDK from Dropbox (currently) and the Upspin StoreServer interface is quite simple so in the end we need only ~3 API requests.
- It uses oAuth2 for API authentication, therefore I registered an app "Upspin" on the [Dropbox Developer Portal][portal], currently in a _Development status_ which will allow up to 500 total Dropbox users.
- All Upspin data will be stored in a specific _"upspin"_ App folder in the user Dropbox. (/App/upspin)
- For testing I registered an "Upspin-test" app so the test does not touch anything in the "production" app folder of an user. 
- Currently, there is a limit on the upload file size (150 MB). I'm working on it.
 
[portal]: https://www.dropbox.com/developers/

**Comment by adg** [comment]
This looks great. Would you like to [send some changes](https://github.com/upspin/upspin/blob/master/CONTRIBUTING.md#contributing-code) to add it to the dropbox.upspin.io repo?

I think it would make sense to split it into two commits:

- `cloud/storage/dropbox` and `cmd/upspinserver-dropbox`
- `cmd/upspin-setupstorage`

What do you think?

**Comment by mazebuhu** [comment]
Sure, splitting the commit into two makes perfect sense. Should I do it on my repository or then on the new one at dropbox.upspin.io? 

For the [S3][s3] or [B2cs][b2cs] backends the review took place in the main Upspin repository and was then abandoned to move all to the specific repositories. Is this the preferred workflow?

I already registered with Gerrit and signed a Google CLA once for Go. Do I need to sign the CLA an other time for Upspin? 

[s3]: https://upspin-review.googlesource.com/c/upspin/+/8029
[b2cs]: https://upspin-review.googlesource.com/c/upspin/+/7986

**Comment by adg** [comment]
I've just created a dropbox repo. I think it might be easiest to just make the changes in the new repo. 

> For the S3 or B2cs backends the review took place in the main Upspin repository and was then abandoned to move all to the specific repositories. Is this the preferred workflow?

No that was just because we didn't have separate repos earlier. 

> I already registered with Gerrit and signed a Google CLA once for Go. Do I need to sign the CLA an other time for Upspin?

No I think you should be good to go. If Gerrit lets you upload a change then you have signed the CLA.

**Comment by mazebuhu** [comment]
I submitted the two commits to Gerrit for code review: 

- https://upspin-review.googlesource.com/c/dropbox/+/13740
- https://upspin-review.googlesource.com/c/dropbox/+/13741

**Comment by mazebuhu** [comment]
Dropbox storage backend was merged. Thanks @adg & @robpike for your time in reviewing my code. I will work on the documentation on the setup process for it, like for https://upspin.io/doc/server_setup_gcp.md or https://upspin.io/doc/server_setup_aws.md. Ok?

**Comment by adg** [comment]
@mazebuhu thank you! And yes, the documentation plan sounds good. (`server_setup_dropbox.md`)
