### ISSUE TITLE
cmd/cacheserver: risk of data loss after rm -r storecache

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#476]
A naive user might think that `rm -r ~/upspin/storecache` is a safe operation. In actual fact, that directory also contains the write-back queue (as `*_wbf` files) that contains blocks that are yet to be persisted to the storeserver. Perhaps these blocks should be kept under a separate directory with a less benign-sounding name?

**Comment by robpike** [comment]
I think you forfeit the right to be surprised by data loss if you do rm -r's behind the back of a service. Still, for this and other reasons it might make sense to keep the wbf files separate from the others.

**Comment by presotto** [comment]
The question is how far is far enough?  Would it be good enough if I put it in a directory at the same level as storecache?  What name would mean hands off?  Perhaps call it writebackstore and add a file called .DO_NOT_ERASE with mode 000?

**Comment by presotto** [comment]
Oh well, that doesn't stop rm -r's of the directory.

**Comment by buchanae** [comment]
I could see myself cleaning a directory with `cache` in the name, but I wouldn't remove one called `data` or `database` or `storage`. 

I agree, I probably shouldn't go around removing files I don't understand, but sometimes the computer deserves it :)

**Comment by masiulaniec** [comment]
> Would it be good enough if I put it in a directory at the same level as storecache

I think so. Perhaps take cue from storecache and call it storefoo where foo is some noun such as wbq, sendq, queue, data, stage, ...
