### ISSUE TITLE
store/storecache: cache ordering is lost after restart

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#478]
This issue is about cache ordering (for LRU) being lost after a restart. More specifically, a `TODO` is present in the codebase to mark this as a debt:
https://github.com/upspin/upspin/blob/f1fd88bd5c0f35c6e9c6e94a1f11ae1cabbc1358/store/storecache/cache.go#L81-L83

I am (selfishly) opening the issue because I am interested in tracking the progress of this, and more specifically seeing how it will be addressed. Perhaps it'll also deem helpful as a log for whoever will work on it.

**Comment by adg** [comment]
cc @presotto

**Comment by gbbr** [comment]
I was wondering if using the [`Atim`](https://golang.org/pkg/syscall/#Stat_t) (atime) value would be a good approach in restoring the cache ordering based on the most recent access times of the files. I'd be happy to commit to this work if this approach sounds viable. I think most operating systems should support the property.

**Comment by n2vi** [comment]
I believe we continue to want to use sequence numbers.   My hope with file
times is that we support traditional Unix semantics, including the ability
of tools like tar to set times.   In other words, I think of mtime
especially as a useful hint for humans, not a dependable signal for file
system implementations.

**Comment by presotto** [comment]
The store doesn't have sequence numbers.

Access time would be nice but it is system specific.  I have a CL just
keeping a log on the side to record accesses.  Not as nice as stat_t.atime
but at least not system specific.

**Comment by presotto** [comment]
I may back out of my CL.  keeping a separate log for

**Comment by presotto** [comment]
Crap, mis-clicked.

What I meant to say was, I have a CL using a log that works.   We can kill it off if someone can build a universal atime that works on all known systems.  Right now Windows has one as long as we use the right file system.  That may be good enough.

**Comment by gbbr** [comment]
I can give it a shot.

**Comment by gbbr** [comment]
@presotto I've opened a purely demonstrational CL (https://upspin-review.googlesource.com/c/upspin/+/14440) illustrating how this would look like. It's based on the commit prior to the one you've just pushed to make it more readable.
