### ISSUE TITLE
cloud/storage: implement Google Drive backend

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#479]
Is this something that would be desired for upspin? I could potentially commit to this work and get inspired by the guidance given in https://github.com/upspin/upspin/issues/468 (dropbox storage).

This would be great because I'm using Google Drive myself and could make use of it. I've already started digging into how this could be implemented and there is the [official client](https://godoc.org/google.golang.org/api/drive/v3) implementation by Google which should make it easy.

The way I see it, files stored by Upspin on Google Drive should go into the [Application Data](https://developers.google.com/drive/v3/web/appdata) folder which is especially allocated for 3rd party apps. Then these blobs will become separate from the general files that the user has and he will see "Upspin" in his "Manage Apps" section of the Google Drive settings, like this:

<img width="796" alt="screen shot 2017-10-10 at 18 02 29" src="https://user-images.githubusercontent.com/6686356/31397047-39b14120-ade5-11e7-956a-b6da329d4016.png">

**Comment by adg** [comment]
Sounds great to me! 😄

**Comment by gbbr** [comment]
Awesome! I will start working on this and link to an initial version here soon. It will be hosted on my account.

**Comment by gbbr** [comment]
Here it is: https://github.com/gbbr/drive.upspin.io

Some differences from the other implementations:
- Google Drive allows multiple files to share the same name, under different IDs (see the `name` property in the [docs](https://developers.google.com/drive/v3/reference/files#properties)). For this reason, when doing operations by name (such as Download, Put or Delete), one must first look-up the ID of that file. For this reason, I have added a server-side LRU cache to store IDs and avoid subsequent HTTP API calls.
- For the same reason as above, when you Put a file, a check runs first verifying that file doesn't already exist. If it does, it gets deleted first to avoid duplicates.
- When deleting a ref that doesn't exist, no error is returned.

The above choices I've made based on my own common sense and am happy to change them.

**Comment by adg** [comment]
Thanks! It generally looks very good and I think your design choices are sound. Please give me some time to create the new repo.

**Comment by gbbr** [comment]
Thank _you_ for taking the time to look (super lazy reply).

**Comment by idrarig** [comment]
Hey, while it's great to have many options for storage backends, I was wondering if it would be possible to have an implementation of dirserver and storeserver whose purpose is to mount one's Drive into the Upspin tree, as, say, user+drive@domain? So that I can store part of my data under user+drive@domain/something and then share it via Gmail as a Drive attachment? That would be very convenient as we can't share Upspin links at the moment... Of course Access files would not work or should be limited to Gmail addresses. Just thinking through the keyboard here...

**Comment by adg** [comment]
@idrarig that might be an DirServer/StoreServer that serves an Upspin root from Google Drive. If you want to hack on this, take a look at the [demoserver](https://github.com/upspin/exp/blob/master/cmd/demoserver/main.go#L5) for an example of a simple Upspin server.

**Comment by idrarig** [comment]
Thanks for that @adg

**Comment by gbbr** [comment]
Is this still of interest? Apologies for potentially pestering.

**Comment by adg** [comment]
@gbbr yeah it is, I'm just slow on creating the repo. I'll do it tomorrow.

**Comment by adg** [comment]
@gbbr on second thoughts, I think we could add this to the gcp repo. It is built on the same stack and will likely include many of the same libraries. What do you think?

**Comment by gbbr** [comment]
I would feel this is more like Dropbox looking at the [file structure](https://github.com/gbbr/drive.upspin.io), [imports](https://github.com/gbbr/drive.upspin.io/blob/master/cloud/storage/drive/drive.go#L13-L14) and overall code layout. I'm not aware of any libraries that may be common with GCP.

**Comment by gbbr** [comment]
Thanks for creating the repo @adg. I have created CLs for it. Do note that I will be offline from tomorrow until the 5th of December and will not be able to address comments during this time.

**Comment by srenatus** [comment]
@gbbr I think this Drive backend is a great idea. 🎈Thank you 🎉

**Comment by gbbr** [comment]
Thanks @srenatus, I have been using it myself for a couple weeks now. Suggestions, ideas are welcome.

**Comment by gbbr** [comment]
This is now available at [github.com/upspin/drive](https://github.com/upspin/drive). Will close the issue once I add the documentation to the server setup [cloud services](https://upspin.io/doc/server_setup.md#cloud) section.
