### ISSUE TITLE
cmd/upspinfs: can't set mount point in config

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#480]
The mount point argument to upspinfs is a plain argument, not a flag. The cmdflags mechanism in the config file has no provision for providing non-flag arguments.

If the mount point were instead a standard format flag, like `-mount /u`, it would be possible in the config to set the mount point and start upspinfs from the config.

As it stands, we have to start upspinfs manually, or at least separately from the config.

**Comment by presotto** [comment]
Personally, I think that should just be in a script.  There is such a thing
as too much crap to stick in the config.

**Comment by robpike** [comment]
What is wrong with making it a mandatory flag instead of an argument?

**Comment by presotto** [comment]
Sure.

**Comment by robpike** [comment]
Reopening as more cases for this being useful have arrived.

We could allow either and satisfy everyone except purists.
