### ISSUE TITLE
cmd/cacheserver: writeback queue blocked by 400 Bad Request

### ISSUE THREAD

**Issue by foolusion** [upspin/upspin#483]
I used upspinfs with the cacheserver enabled to copy around 5.5 GB of files. The majority of the blocks are still in the writeback queue. I turned on the debug logging and I'm seeing this log message.

```bash
2017/10/15 10:44:54.992842 store/remote.Put("remote,upspin.aponeill.com:443")(1048576 bytes) error: I/O error:
        rpc.Invoke: 400 Bad Request: read tcp 10.128.0.2:443->80.67.239.147:33656: i/o timeout
2017/10/15 10:44:54.992914 store/storecache.failure: down 3
2017/10/15 10:44:54.992945 store/storecache.scheduler: timeout: goodput 0 ops/s, output 3495.253333333333 ops/s
```
It seems to fail quickly and never retry.

**Comment by presotto** [comment]
Looking...

**Comment by adg** [comment]
@presotto any findings?

**Comment by presotto** [comment]
I did fix a bug that probably caused it.  Unfortunately I fixed it after experiencing it myself and forgot to look for an issue.  I'm closing.
