### ISSUE TITLE
access/access.go: expandGroups can miss group entries

### ISSUE THREAD

**Issue by FrankReh** [upspin/upspin#484]
In the logic for expandGroups(), when it is iterating through a slice of nested groups, the jump out of the iteration is premature when it finds a nested group is already accounted for in the overall list of groups to be expanded.  The intent is clearly to jump out of two levels of iteration so potentially other nested elements can be inspected, but the label being continued to is three levels out.

This would not have been caught through normal package usage because this is an internal function to the access package and the higher level access package function (Users()) that calls it indirectly has the unusual behavior of rebuilding everything when even a single missing group is found, so the potentially dropped users or further missing groups get found in the subsequent go around of calling expandGroups again.

So this is not a bug that causes undesirable effects to the callers of the access package.  It just makes the code slightly less efficient and definitely consumes unnecessary time for anyone looking through the code and wondering how this works.

There are countless ways to fix this.  I am happy to provide my take (I've got a local fix and additions to access_test.go that exercise it).  Have signed the relevant CLA.

**Comment by FrankReh** [comment]
Actually it is a bug that can cause undesirable effects to the callers of the access.Users() package.  (Still surprises me how writing down one's thoughts makes things more clear.)

It is possible to construct a test with two groups that need to be expanded where both groups are known to the package but where the second group contains the first group as an entry.  

When the logic iterates through the second group and finds an entry that is in its top level list of entries to look at, it abandons the remainder of the second group.  Thus expandGroups() can return an empty missingGroups result while not having looked at all of the second group's entries.  So some users might not get added to the users list being returned.  So this should be fixed.

I can provide an access_test.go test case that demonstrates this problem in this space if it would help clarify, if a few lines of test code is allowed in these bug reports.

**Comment by adg** [comment]
Please do [send the fix](https://github.com/upspin/upspin/tree/master/CONTRIBUTING.md). Thank you!
