### ISSUE TITLE
openstack: add storage implementation

### ISSUE THREAD

**Issue by adg** [upspin/upspin#485]
~~Rene Kaufmann~~ Nicola Girardi has [sent](https://upspin-review.googlesource.com/c/upspin/+/13900) a change that provides a storage.Storage implementation that uses [OpenStack](https://www.openstack.org/). We should create a repo for this, as we have with the other implementations.

**Comment by adg** [comment]
cc @HeavyHorst

**Comment by HeavyHorst** [comment]
Nicola Girardi has sent the change. :D

https://upspin-review.googlesource.com/c/upspin/+/13900

**Comment by adg** [comment]
With all these new contributors I'm confusing myself. 😊  (What a delightful problem to have!)

**Comment by PierreZ** [comment]
Hi!
From what I see, the change is declared "Abandoned". Does Nicola Girardi still working on it? I can give a hand on this, it will be a good first contribution to Upspin :+1:

**Comment by idrarig** [comment]
Hi, I abandoned the change because it was in the wrong project. I'm just waiting for the project to be created and then I'll resubmit. I've been using the implementation for myself ever since that first CR and I've had no problems so far. I can share publicly somewhere else if you're interested :)

**Comment by PierreZ** [comment]
Awesome! Looking forward to use it :smile:

**Comment by idrarig** [comment]
@PierreZ Shared here https://github.com/idrarig/openstack.upspin.io after ripping out some non-standard parts from the server. Things that I haven't done yet (it should go without saying, feel free to do this yourself):
* The setup server part (I setup my server sort of manually)
* Testing with OpenStack-based services other than OVH
My idea was to work on those when and if these snippets become part of the project. :)
I hope this helps!

**Comment by PierreZ** [comment]
I'll look into it, and see what I can contribute :+1: Thanks.

**Comment by adg** [comment]
I've now created an openstack repo. https://github.com/upspin/openstack

go get -d openstack.upspin.io

**Comment by PierreZ** [comment]
Cool, @idrarig and I are working on [a dedicated repo](https://github.com/idrarig/openstack.upspin.io/pull/1), we will sync it and push it.
