### ISSUE TITLE
cmd/cacheserver: upspin path names are created for incomplete files

### ISSUE THREAD

**Issue by foolusion** [upspin/upspin#487]
I use upspinfs and cacheserver to archive photos. If the cacheserver is shutdown before everything has uploaded, I can see references are created for files that are not uploaded. If I run "upspin get file" without the cacheserver I'll get an error (403 Forbidden on gcs) due to missing blocks. This leads me to believe either cacheserver should be always on, or the upspin references or directory entries should not be created until after the blocks are all uploaded. Below are the steps that produced this result.

upspin/config with "cache: yes"

    > upspinfs $HOME/up
    > cp ~/photos/new/* ~/up/foolusion@gmail.com/photos/2017/10

turn off computer or kill cacheserver before upload finishes or upspin config with "cache: no"

    > upspin ls @/photos/2017/10
    ...
    foolusion@gmail.com/photos/2017/10/DSC_4682.NEF
    > upspin get @/photos/2017/10/DSC_4682.NEF

error message (using GCS it's 403 FORBIDDEN)

    upspin: get: foolusion@gmail.com/photos/2017/10/DSC_4682.NEF: client.Get:
        client/clientutil.ReadAll:
        client/clientutil.ReadLocation:
        store/remote.Get("remote,upspin.mydomain.com:443"): fetching https://storage.googleapis.com/mydomain-com-upspin/469E5DFBDCDA1C3FCAAFA0E801DA8F0367D2F1E459F4EEEE29C349754B042AF1: 403 Forbidden

**Comment by adg** [comment]
This is issue #285 I believe. Let me know if I'm mistaken.

**Comment by presotto** [comment]
Right you are.  I'm working on it.
