### ISSUE TITLE
test: flaky test when cacheserver enabled

### ISSUE THREAD

**Issue by adg** [upspin/upspin#488]
I suspect there's a race in the tests when the cacheserver is enabled. The build that introduced the change passed on Linux but failed on macOS: https://travis-ci.org/upspin/upspin/builds/288985607

```
--- FAIL: TestIntegration (96.73s)
    --- FAIL: TestIntegration/kind=inprocess/packing=ee/cache=true (25.32s)
        --- FAIL: TestIntegration/kind=inprocess/packing=ee/cache=true/AllowReadAccess (0.06s)
        	integration_test.go:124: integration_test.go:122: test@upspin.io/dir1/file1.txt: client.Get: item does not exist:
        			client/clientutil.ReadAll:
        			client/clientutil.ReadLocation:
        			store/inprocess.Get: no such blob: 8E5E788BE98FBB98C2B8B84C1410933236A0412C56FBE7CEEE2EA4CAF41774CC
    --- FAIL: TestIntegration/kind=server/packing=ee/cache=true (22.63s)
        --- FAIL: TestIntegration/kind=server/packing=ee/cache=true/GetLinkErrors (0.12s)
        	error_test.go:163: error_test.go:161: test@upspin.io/get-link-errors/dst/file: client.Get: item does not exist:
        			client/clientutil.ReadAll:
        			client/clientutil.ReadLocation:
        			store/inprocess.Get: no such blob: 876267948FE2BE43586376AB0E1B733DC0EC70353CD41BE58090F320320463CC
FAIL
FAIL	upspin.io/test	97.863s
```

**Comment by adg** [comment]
The second failure there is here:

```
        r.As(ownerName)
        r.Put(dstAccess, "*:"+ownerName+"\n*:"+readerName)
        r.Put(file, content) // Put the file again to wrap the keys.
        r.As(readerName)
        r.Get(file)                 <-----
        if r.Failed() {
                t.Fatal(r.Diag())
        }
 ```

The owner puts the file through the cache. The reader reads the file with no cache. The cacheserver is racing against the reader; it must write the blocks before the reader reads them. On our workstations this tends to work most of the time, but on heavily loaded machines (like the continuous integration cluster) these tests will often fail.

We need to remove the races from these tests. If we could tell the cacheserver to flush as we switch between users, that would do it.

cc @presotto

**Comment by presotto** [comment]
Or I could do the tough thing and just make sure I flush the relevent blocks before a DirEntry Put. This has shown up as another issue.  The current semantics was to make Australia faster for you upside down guys but I it is starting to bother others.

**Comment by presotto** [comment]
By the way, if you want a quick fix, I do flush if you put an Access file since that affects semantics in a big way.

**Comment by adg** [comment]
> Or I could do the tough thing and just make sure I flush the relevent blocks before a DirEntry Put.

I'm not sure that this would actually fix the problem in the tests, though. Would it? The cacheserver would still return immediately from the Put, right?

**Comment by presotto** [comment]
You are right.  It wouldn't help because the DirEntry just wouldn't be
there.  Puting and access file in the tree would fix it though.

**Comment by adg** [comment]
I think @presotto fixed this with a cache flush on change user.
