### ISSUE TITLE
cmd/upspin: directory tree inconsistency

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#490]
```
$ readlink /u/release@upspin.io/latest/darwin_amd64
../all/darwin_amd64/79295026b462f9bde96936ca3a37def2d51f1aec
$ alias upspin=/u/release@upspin.io/latest/darwin_amd64/upspin
$ upspin ls @
upspin: ls: client.Lookup: item does not exist:
	dir/remote.Lookup("remote,example.com:443"):
	joe@example.com/ does not exist
$ upspin mkdir @
upspin: mkdir: client.MakeDirectory: item already exists:
	dir/remote.Put("remote,example.com:443"):
	dir/remote.Put("remote,example.com:443"):
	joe@example.com/: dir/server.Put
$
```

**Comment by n2vi** [comment]
I'm seeing this as well this morning after rebuilding client and server,
and am guessing it is from a recent change in the client.   Old clients
talking to the new server still see my tree.  (Whew!)

**Comment by masiulaniec** [comment]
I updated both client & server to HEAD and that seems to have resolved it.

**Comment by n2vi** [comment]
I updated client and server using "git sync" in src/upspin.io and src/
gcp.upspin.io and "go install ./..." and "go build".  That worked fine.

Then I updated again with "go get -u -d  gcp.upspin.io/cmd/upspinserver-gcp"
and rebuilt.  (The server binary was indeed different.)  Now I'm getting
lots of warning messages about
    grosse@gmail.com/: unknown sequence 270


On Wed, Oct 18, 2017 at 8:43 PM, Jacek Masiulaniec <notifications@github.com

**Comment by masiulaniec** [comment]
Maybe related: I wiped my `upspin/dircache` after noticing the anomaly described in #492.

**Comment by n2vi** [comment]
Works for me now, with Dave's latest CL.   Close?

**Comment by robpike** [comment]
I think it's all better now. Closing.
