### ISSUE TITLE
cmd/upspin: bogus Sequence numbers after devseq merge

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#492]
Having upgraded my client and server in response to the devseq merge announcement (https://groups.google.com/forum/#!search/upspin/upspin/l8itmmnbPP8/B0eSPT7TBQAJ), I attempted to verify that DirServer is now assigning the sequence numbers. That test failed:

```
$ upspin mkdir @/testdir
$ upspin ls -l @ | grep testdir
d ?                        0       0 Wed Dec 31 16:00:00 []     joe@example.com/testdir/
$
```

In the above, Sequence of the new directory equals 0 but according to the docs it should equal at least 1 (=SeqBase).

Redoing the test after setting `cache: no` in the config shows a more sensible Sequence value of 1.

**Comment by robpike** [comment]
It was a clumsy transition but I believe if you wipe the cache and restart things should be healthy. I don't know why a wipe would be necessary but it seems to be.

**Comment by adg** [comment]
Closing this unless we hear back that the wipe+restart didn't work.
