### ISSUE TITLE
client: MakeDirectory returns an incomplete DirEntry

### ISSUE THREAD

**Issue by SebastianZaha** [upspin/upspin#499]
It appears that the recent seq number change has caused MakeDirectory to also return an incomplete DirEntry, with only the sequence set.

**Comment by robpike** [comment]
What's wrong with that? Is it not documented or is it that you found this surprising?

**Comment by SebastianZaha** [comment]
I was using the returned DirEntry in my program before this change, and it stopped working, which prompted me to look what happened, then made the connection with your announcement email about Put.

I am thinking now that perhaps I should refactor my code to not care about  the returned DirEntries, only check for an error. If this is the intended usage, perhaps it should be documented so that it is clearer what the point of the returned DirEntry is, and when it would be useful for clients, and when they should simply ignore it.

**Comment by adg** [comment]
Agree that current behavior should be the documented behavior.
