### ISSUE TITLE
serverutil/signup: mail is sent to upspin-sendgrid@google.com from all keyservers

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#501]
When running a `keyserver` instance locally (or anywhere else for that matter), notifications continue to be sent to _upspin-sendgrid@google.com_. I assume this behaviour is unwanted. I myself have probably signed up at least 6-10 times locally (as ga@stripetree.co.uk) which might make whoever watches that inbox wonder what's going on.

I am happy to tackle this change if desired. I suggest two options:
1. Add a `-notify` string flag which takes an e-mail address as a value, sending all signup notifications there. It would be disabled by default (meaning you guys would have to start the central keyserver with this flag set to the email address above). Alternatively, the file taken by `mail_config` could be enhanced (YAML?) to specify this address too, reducing the need for extra flags.
2. Specifically check the `flags.NetAddr` value, and only send email if it's `key.upspin.io`.

What do you think? In my opinion point 1/YAML makes most sense. I'm happy to commit to this.

**Comment by gbbr** [comment]
On this occasion, I'd also like to bring into discussion the possibility of allowing users to signup to a local keyserver without requiring email verification or the `mail_config` flag. Not sure if this is something that's wanted but it seems related to the above and it seems like a good place to bring it up.

If we want both of these changes it would make sense for them to go into the same CL.

**Comment by adg** [comment]
> Alternatively, the file taken by mail_config could be enhanced (YAML?) to specify this address too, reducing the need for extra flags.

I think this is the right path forward. The first line of the config can remain the sendgrid token, and the second line could be the notification address.

> On this occasion, I'd also like to bring into discussion the possibility of allowing users to signup to a local (only) keyserver without requiring email verification or the mail_config flag. Not sure if this is something that's wanted but it seems related to the above and it seems like a good place to bring it up. If we want both of these changes it would make sense for them to go into the same CL.

Maybe when `-mail_config` is not supplied we should just print the validation address to the console? (instead of disabling the /signup handler altogether)

**Comment by gbbr** [comment]
I will look into this. Printing to the console sounds good to me.

**Comment by gbbr** [comment]
I would re-open this because the issue was only partially addressed.

> The first line of the config can remain the sendgrid token, and the second line could be the notification address.

This hasn't been yet done. I am starting work on this within the hour.
