### ISSUE TITLE
access: unable to create/view snapshots (inprocess)

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#502]
When trying to create (or list) a snapshot for a user, using the `inprocess` servers, the following error occurs:
```
gbbr@iMac:upspin.io (local-servers)$ upspin -config=/Users/gbbr/cfg -insecure snapshot
upspin: snapshot: client.Lookup: information withheld:
	dir/remote.Lookup("remote,localhost:8081"):
	ga+snapshot@stripetree.co.uk: dir/inprocess.Lookup
```
I believe (and I might be wrong) that the reason is because the `list` field in the access file for this path is set to `user+snapshot@domain.com` for all rights (when created by `access.New`), making it impossible for `user@domain.com` to access it and create the root directory.

Should the owner not be included in that list? Happy to commit. And apologies in advance if I'm misunderstanding the way snapshot users are supposed to work.

**Comment by adg** [comment]
Snapshots are a feature of `dir/server` so I'm not surprised they don't work for inprocess. I'm not sure that there is anything to do here.

> Should the owner not be included in that list?

That's not how it works, and I'm not sure that's how it should work. dir/server internally allows the snapshot owner to read their snapshots, but I don't think we should extend the rule to all suffix accounts.

**Comment by gbbr** [comment]
> That's not how it works, and I'm not sure that's how it should work. dir/server internally allows the snapshot owner to read their snapshots, but I don't think we should extend the rule to all suffix accounts.

I suspected that is the case. I need to spend more time studying how this work. Until then, closing.
