### ISSUE TITLE
{key,dir,store}server: kind flag is redundant

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#503]
The documentation for the `-kind` flag says:
```
-kind kind
    	server implementation kind (inprocess, gcp) (default "inprocess")
```
But `gcp` is not a valid value for it. The only other valid value is `server`, which is meaningless without the `-serverconfig` flag. I suggest removing the `-kind` flag and having the servers run automatically `inprocess` when `-serverconfig` is not provided. When it is, use the specified configuration.

I can do the work if the suggestion sounds good.

**Comment by adg** [comment]
I think I'd prefer to just leave it as-is. Explicit is better than implicit, etcetera. These servers are rarely invoked manually, anyway.

**Comment by gbbr** [comment]
Alright. I will submit a CL to update the description of the flag and replace the “gcp” bit with “server”. Then I will close this. Sound good?

**Comment by adg** [comment]
Ah yes, please.
