### ISSUE TITLE
cmd/upspin cp from public directory to own results in unreadable files

### ISSUE THREAD

**Issue by pbx0** [upspin/upspin#504]
When I tried copying the augie@upspin.io/Images directory to my own I received an error getting the files from my own tree. I can reproduce this via these steps:
```
$ upspin rm -R @/Images
$ upspin cp -R augie@upspin.io/Images @/
$ upspin ls @/Images/Augie
me@example.com/Images/Augie/favicon-32x32.png
me@example.com/Images/Augie/large.jpg
me@example.com/Images/Augie/small.jpg
me@example.com/Images/Augie/smaller.jpg
me@example.com/Images/Augie/transparent.png
$ upspin get @/Images/Augie/large.jpg > augie.jpg
upspin: get: me@example.com/Images/Augie/large.jpg: client.Get:
	client/clientutil.ReadAll:
	user augie@upspin.io: pack/eeintegrity.Unpack: does not verify
```
I am running my own upspinserver re-compiled with go 1.9.2 from master yesterday on FreeBSD. My cmd/upspin was also recompiled from master yesterday on linux with 1.9.2. Retrieving the image directly from augie@upspin.io works fine.

**Comment by adg** [comment]
Looks like a problem in client.PutDuplicate.

**Comment by adg** [comment]
Once [this change](https://upspin-review.googlesource.com/#/c/augie/+/14921) is submitted a new `upspin-ui` binary will be pushed out to https://upspin.io/dl/ and you should find this works (I've tested it).

Thanks for the issue report!

**Comment by adg** [comment]
The new builds are out. Please let me know if this fixes the issue for you.

**Comment by pbx0** [comment]
Just tested it, works for me. Thanks for the quick turnaround.
