### ISSUE TITLE
cmd/upspin/serversetup: does not allow empty -host flag

### ISSUE THREAD

**Issue by mazebuhu** [upspin/upspin#505]
I tried to setup Upspin with different hosts for store and dir servers. The help of `upspin setupserver` says: 

```
...
 -host name
    	host name of upspinserver (empty implies the cluster dir.domain and store.domain)
...
```

But the `upspin setupserver` does not allow an empty `-host` flag:

```
$ upspin setupserver -domain=example.com
upspin: setupserver: the -domain and -host flags must be provided
Usage: upspin setupserver -domain=<domain> -host=<host> [-where=$HOME/upspin/deploy] [-writers=user,...]
```

Looking at the code of `cmd/upspin/serversetup.go` it's clear why this happens and I can provide a fix for it if desired.

**Comment by adg** [comment]
I'm not sure what you're trying to do. You must tell the setupserver command where the server is. If you're running separate dir and store servers (dirserver and storeserver) then you shouldn't use setupserver. If you're running a combined store/dir server (an upspinserver) then there's no need to use different host names for store and dir servers (although you can; you just need to provide one of them as the -host argument).

**Comment by mazebuhu** [comment]
I was trying to use seperate dir and store servers and wrongly used the `serversetup` command.
