### ISSUE TITLE
How do I delete my account from upspin system?

### ISSUE THREAD

**Issue by m-abdalrahman** [upspin/upspin#514]
I hope there is a way for the user to delete himself from upspin key server.

**Comment by n2vi** [comment]
Deletion is not necessary or possible.  The transaction log at https://key.upspin.io/log is cryptographically protected by a hash chain, so deletions are impossible.  This protects you from an adversary removing your public key and re-registering the account with their own key.  If you decide to stop using Upspin someday, no cleanup steps are necessary.
