### ISSUE TITLE
keyserver: add support for non-GCS storage

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#515]
This issue is about allowing a user to configure the storage medium of a key server. Currently it's hard-coded to use GCS. Some people seem to have interest in running their own key server (see #276). I am happy to do the work if it's ok with everybody.

If this is something unwanted and we want to try hard and enforce one and only central key server, please feel free to close the issue.

**Comment by adg** [comment]
I think it would be fine to add a backend= configuration option to the keyserver serverconfig to make it possible to select other storage backends.

**Comment by gbbr** [comment]
Cool, thanks Andrew! I'll take it.
