### ISSUE TITLE
cloud/storage/dropbox: return proper Upspin errors

### ISSUE THREAD

**Issue by mazebuhu** [upspin/upspin#516]
Currently the plugin after a request to the Dropbox API only checks if the status code is different then `200`. If so the operations `cloud/storage/dropbox.Download`, `cloud/storage/dropbox.Put` and `cloud/storage/dropbox.Delete` always return an Upspin IO error.

This is bad, since it will break other Upspin code which expects a proper Upspin error, like for example if in a `cloud/storage/dropbox.Download` operation the block is not found a `errors.NotExit`should be returned rather than a `errors.IO`.

I'm working on this issue to handle Dropbox specific status codes and return a proper Upspin error for it.

**Comment by adg** [comment]
Great catch, thanks.
