### ISSUE TITLE
upspinserver: no root for user

### ISSUE THREAD

**Issue by PierreZ** [upspin/upspin#521]
### What version of Upspin are you using?

Devel version (7eaef666863d2f405807a595318f1243db086fd0), compiled on archlinux, running on debian9 (both 64bits)

### What did you do?

I followed the guide to install my upspinserver using local disk as a first installation. I then followed the instructions to Purge my storage in order to test [openstack.upspin.io](https://github.com/PierreZ/openstack.upspin.io).

### What did you expect to see?

No errors on the logs

### What did you see instead?

```
Nov 01 23:19:57 upspin upspinserver[18240]: 2017/11/01 23:19:57.904804 serverutil/perm.NewFromDir: item does not exist:
Nov 01 23:19:57 upspin upspinserver[18240]:         dir/server.Watch:
Nov 01 23:19:57 upspin upspinserver[18240]:         user upspin@upspin.pierrezemb.org:
Nov 01 23:19:57 upspin upspinserver[18240]:         no root for user
Nov 01 23:20:27 upspin upspinserver[18240]: 2017/11/01 23:20:27.905160 serverutil/perm.NewFromDir: item does not exist:
Nov 01 23:20:27 upspin upspinserver[18240]:         dir/server.Watch:
Nov 01 23:20:27 upspin upspinserver[18240]:         user upspin@upspin.pierrezemb.org:
Nov 01 23:20:27 upspin upspinserver[18240]:         no root for user
Nov 01 23:20:57 upspin upspinserver[18240]: 2017/11/01 23:20:57.905896 serverutil/perm.NewFromDir: item does not exist:
Nov 01 23:20:57 upspin upspinserver[18240]:         dir/server.Watch:
Nov 01 23:20:57 upspin upspinserver[18240]:         user upspin@upspin.pierrezemb.org:
Nov 01 23:20:57 upspin upspinserver[18240]:         no root for user
```

I have no problem using my modified upspinserver, I can put files and see them back using my account. I'm wondering what is that user :smiley: 

I must admit that my knowledge about upspin is pretty limited for the moment, I prefer to create an issue even if the issue can be from my modified version of upspinserver for OpenStack.

**Comment by gbbr** [comment]
Normally the `setupserver` subcommand creates the root for you, but it might be that because you've wiped your storage you have no root now. Perhaps trying running `upspin mkdir @/` and see if that fixes the problem.

**Comment by PierreZ** [comment]
I'm curious about that user, because it's not the one I created. Is it some kind of "admin" user? Do I have write access on it?

**Comment by gbbr** [comment]
The [Configure upspinserver](https://upspin.io/doc/server_setup.md#configure) part of the documentation might clarify that. Also the "How do I add a family member to my Upspin installation?" section in the [FAQ](https://upspin.io/doc/faq.md) is insightful. Hope that helps.

**Comment by PierreZ** [comment]
Problem solved, thanks for your help @gbbr
