### ISSUE TITLE
bind: Server calls could be cleaner

### ISSUE THREAD

**Issue by FrankReh** [upspin/upspin#524]
Each of the three Server calls in the bind package, KeyServer, DirServer and StoreServer, lock a common mutex, then do a hash lookup to get a Dialer, release the mutex, then relock the mutex to do a hash lookup for a cached service that may have already been successfully dialed, and if the lookup was successful, the original Dialer that was found goes unused.

The map of cached services could be queried first. Most of the time the lookup will be successful.

The lookup for a Dial could be done while the same mutex was being held for the initial common case when a service hasn't been dialed yet.

The three kinds of service could be using distinct mutexes.

**Comment by adg** [comment]
I'm definitely interested in seeing the change, if you have one prepared.
This code has been hacked on a few times so I would not be surprised to see
that it's got some unnecessary complexity.
