### ISSUE TITLE
signature does not match user already exists on key server

### ISSUE THREAD

**Issue by hagna** [upspin/upspin#525]
I made a mistake (or several) during setup and then switched from freebsd to ubuntu 16.04 because you have docs for that.

Now setupserver fails with this (on ubuntu 16.04 and upspin a422af13d1219e86cf697e5a5f0da12ba46fc7ea):

~~~
$ upspin setupserver -domain=oxcart.co -host=upspin.oxcart.coUser "upspin@oxcart.co" already exists on key server.
Configured upspinserver at "upspin.oxcart.co:443".
upspin: setupserver: client.MakeDirectory: I/O error:
	dir/remote.Put("remote,upspin.oxcart.co:443"):
	rpc.Invoke: 401 Unauthorized: rpc.SessionForRequest: permission denied:
	user upspin@oxcart.co: invalid signature: invalid operation: signature does not match
~~~

**Comment by adg** [comment]
Do you have your old keys from your freebsd machine? They should be in $HOME/upspin/deploy.

**Comment by hagna** [comment]
No, but this error came from mistaking you@gmail.com for user@example.com in this guide https://upspin.io/doc/server_setup.md.  It works now that the server has the admin's keys and I used the admin's email as the username.
