### ISSUE TITLE
upbox: ability to persist previous sessions

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#527]
It would be nice if users of `upbox` could restart a previously stopped session, containing the same users and the same storage contents (considering that something like `backend=Disk` was used).

I would start simple by making the `dir` property of the schema an exported field, allowing users to set it in yaml.
https://github.com/upspin/upspin/blob/2577ed2a663b0f010ded618cc90b6d89f8bc9006/upbox/schema.go#L148-L150
If this property is set, the directory will not be removed when the server stops. When upbox starts again, it will check for the existence of this directory and if it exists it will assume (without sanity checking) that it contains a valid config and attempt to load it. If the directory doesn't exist, a new config will be created at that location.

When this value is not set in the schema behaviour will continue as it is now, creating a temporary directory and wiping it at the end.

Depends on #515 for the ability to persist users.

If the plan sounds good, I would like to work on this.

**Comment by adg** [comment]
Sounds reasonable.

So Start without a populated Dir would create a temporary directory. Should Stop still remove it? Or should there be a separate Cleanup method?

**Comment by gbbr** [comment]
My reasoning was that if Dir is not set and Start creates a temporary directory, it should always clean it up. Otherwise it would remain up to the user to do so because we couldn't find the same randomly generated temporary directory again programmatically.

If Dir is set, Stop doesn't clean up, allowing another restart.

**Comment by gbbr** [comment]
[CL 15720](https://upspin-review.googlesource.com/c/upspin/+/15720) illustrates my idea. I've set it to WIP but if my idea is good it might as well be good to review.

**Comment by gbbr** [comment]
Adding the `dir` entry to the schema is useless without setting the `port` property for each server, if your intention is restoring a previously stopped session (ports are randomly generated without it).

In hindsight, this can be confusing and not very intuitive. I'd like to remove `port` and instead write a `session` file to disk into `dir` which maps servers to their ports:
```
keyserver: 4389
dirserver: 9801
storeserver: 1289
```
This could then be used to restart these servers using the same ports, matching already written user configs. WDYT @adg ?

**Comment by adg** [comment]
@gbbr sounds good, but please use JSON instead of YAML for the session file that will be read/written only by machine.
