### ISSUE TITLE
cmd/cacheserver: Unexpected "odd writeback file" errors

### ISSUE THREAD

**Issue by idrarig** [upspin/upspin#528]
I think this was introduced in https://upspin-review.googlesource.com/c/upspin/+/15260.

To reproduce, start a transfer to ensure some blocks are queued, then kill the cacheserver.

Upon restart, one gets those errors, and indeed writeback files are never retried.

**Comment by idrarig** [comment]
@presotto Restoring this line seems to fix it... at least, I see the files being consumed from storewritebackqueue. `filepath.SplitList()` splits at `:` (separator for list of paths) not at the path separator `/`.

```
diff --git a/store/storecache/wbq.go b/store/storecache/wbq.go
index 9bde68f1..82d78662 100644
--- a/store/storecache/wbq.go
+++ b/store/storecache/wbq.go
@@ -136,7 +136,7 @@ func (wbq *writebackQueue) enqueueWritebackFile(relPath string) {
                log.Error.Printf("%s: writeback file %s but running as writethrough", op, relPath)
                return
        }
-       elems := filepath.SplitList(relPath)
+       elems := strings.Split(relPath, "/")
        if len(elems) != 3 {
                log.Error.Printf("%s: odd writeback file %s", op, relPath)
                return
```

**Comment by presotto** [comment]
Just submitted a CL.  It should have been strings.Split using filepath.Separator.  I misunderstood the meaning of SplitList and worse didn't retest after adding it.

I'll also add a real test to make sure blocks are being written back (better than my testing by hand) and close this item after the test has been submitted.

**Comment by idrarig** [comment]
Thanks! I'm pulling the change and cleaning up my tree. Thanks for planning to add the test (that's what kept me from submitting a CL myself, couldn't find time for understanding how to properly write a test!)

**Comment by presotto** [comment]
Thank you.  I feel like an ass for having submitted that.
