### ISSUE TITLE
store: multiple storage backends not supported

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#534]
One of the challenges I personally see with upspin right now is accessibility. Making it easily accessible to everybody. This is most likely already one of the long terms goals. Something that I think would help with moving closer towards this reality is having the possibility to offer an alternative to people that do not have the knowledge of (or perhaps are not open to) setting up their own box and running their own directory and store servers.

### Scenario

I myself have investigated and tried to set up such a service: a host that provides a directory and store server to which people can connect to and share, given access. My vision was for it to work in this way:

- Everybody may share the same directory server (and its logs), as it is now.
- Everybody may share the same store server, but _doesn't necessarily share the same storage_.

The second point here is important. In order for such a system to stay cheap, efficient and to scale, there should be an option to allow different accounts on the same store server to set up and use different storage backends.

You may picture the same scenario in a family setting or within a group of friends. Bob may share his technical knowledge and want to provide his friends with access to a directory and store server, but would kindly like to ask Alice and others to use the storage space on their own Google Drive (or Dropbox, etc.). All that Alice would have to do is sign up to upspin and give access to her account in Bob's store to use her Drive space. This would dramatically increase the speed at which one could get up and running with upspin.

### Proposal

There may already be ideas to accomplishing the above, but some of the ones mentioned in #138 are already more or less in line with what I was thinking. Perhaps the (store) server could store per-user metadata containing the configuration of the storage backend used by that user. The store/server `Dial` method already receives the config parameter which contains information about the requesting user but does not make any use of it. We could use this to guide users to their storages. The metadata could be similar to the `StoreConfig` part of what is currently `serverconfig.json`. With reference to #138, this would easily allow querying the disk usage for any user.

I think this would make sense and give a more appropriate and useful role to the store server. It would allow to distribute space usage throughout various locations. As it is now, given the above scenario, each user would need to have his own store running, which is not very practical.

This could potentially set the foundation for both user administration and storage distribution. It seems like a natural next step and it seems more in line with how Upspin is supposed to work. What are your thoughts on this?

If any of it sounds good, I'd be happy to do the work.

**Comment by adg** [comment]
@gbbr this seems useful and maybe something that we will want to do, but I think maybe it's too soon for this.

One of the big hurdles we've had with this project is making it comprehensible from the server administrator's perspective. Over the past year we've made a lot of progress in simplifying the setup process. I'm a bit hesitant to add more questions/options/variables to the process, at least at this early stage.

Is this a feature that you want personally? Or just something that you think would be a nice idea? I'd like to drive future feature work based on things our current users need, rather than speculative features.

What do you think?

**Comment by gbbr** [comment]
> One of the big hurdles we've had with this project is making it comprehensible from the server administrator's perspective. Over the past year we've made a lot of progress in simplifying the setup process. I'm a bit hesitant to add more questions/options/variables to the process, at least at this early stage.

The setup process is my main point of thought here too. The best suggestion I've come up with so far would have been to augment the `setupstorage` command with an additional flag, allowing to link a user's store to a remote storage (Dropbox, Drive, GCP, Remote disk, etc.). The `setupstorage` command would remain optional and default to the store's storage. This would not change the normal setup process, considering it is realisable. There are however other implications which I can bring forward based on how this idea moves along.

I also feel, judging by how Upspin is evolving, that there still might remain lower-level setup commands for more advanced users but also move towards towards higher-level ones (such as upspin-ui) for easier and more straightforward user experiences.

> Is this a feature that you want personally? Or just something that you think would be a nice idea? I'd like to drive future feature work based on things our current users need, rather than speculative features.

This is more like a mixture of both, a personal speculation if you will. I don't want it per-se. My plan was to experiment setting up a public service [here](https://birdnest.io/), running a directory and store server which would be open for everybody to use. Such a service, if it is meant to stay free and low cost (at least while small), would have to allow users to use their own storage, providing only the directory and store server. It seems tedious to have a dedicated store for each storage provider (and user for that matter).

> What do you think?

I not fully in line with the roadmap and the priorities, nor do I have all the context, but if you also have thought about a service similar to the above then it could be a good idea to start thinking about how to move in that direction. If we were to add such a feature without an actual need for it (based solely on speculation) then that would make no sense. But if a system like this was being built in parallel, I think it could serve a good source of truth for upspin. Perhaps it would reveal uses or corner-cases needed, but no considered.

You, however, know best the plan for upspin. So if this needs to be put aside for now, let's do that. We can either close it and open it again when the time comes in the mailing list, or just leave it for later. I do feel it is strongly related to the motivation behind #138 (user administration).

**Comment by gbbr** [comment]
To put it in a shortly, my motivation is to simplify the setup process for non-technical users. Accommodating a service like the one described here would allow people to get into upspin by simply creating an account with the key server. The server owner could handle the rest (either manually, or automated through a simple program).

**Comment by adg** [comment]
I think the best way forward is to implement a StoreServer that does this, separate to the core Upspin code base. The StoreServer implementation is pretty trivial. That should suffice for birdnest.io, no?

**Comment by gbbr** [comment]
You're right, that can definitely be done easily. I'm closing this then. Perhaps we can reconsider it later if the time or the need comes for such a thing.

I personally still find it somewhat odd that if you want your storage to be with a cloud provider (Dropbox, Drive, GCP, etc) you need to run your own server and that server can only serve you and no one else.

**Comment by n2vi** [comment]
Not re-opening the issue, just noting for the record that we do already share servers among multiple people.  jn.gl is one example for multiple unaffiliated people.  There is a service for Googlers.  I have upspin.n2vi.org for my family.  As you say, these shared services may make it easier for a newcomer to get into Upspin.
