### ISSUE TITLE
doc: potentially confusing text in security document

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#537]
In the below text:

> Then, we encrypt K again, repeatedly using the public key of each potential reader of the file. We store those encrypted keys in the DirEntry for the item along with a digital signature of the data. To read the data, the reader looks in the DirEntry for the reader’s encryption of K, decrypts K, and uses that to decrypt the data.

As a crypto newbie "_we encrypt K again, repeatedly_" sounds to me like K is encrypted using the public key of the first reader, then the result encrypted with the public key of the next reader, etc. This of course makes no sense, but having looked into the code I saw that my initial understanding was (as suspected) a misunderstanding.

I'd like to suggest changing this to something like:

> Then, we encrypt K again for each potential reader of the file using their public key. We store the list of encrypted keys in the DirEntry of the item along with a digital signature of the data. To read the data, the reader looks in the DirEntry for his encryption of K, decrypts K, and uses it to decrypt the data.

In my opinion this is much clearer, but I will trust your judgement since I am new to this domain. I'm happy to make this change if you like it.

**Comment by adg** [comment]
I agree that the wording is confusing as-is. If I can further tweak your rewrite:

> Then, for each potential reader of the file, we encrypt K again using their public key. We store the set of encrypted keys in the DirEntry of the item along with a digital signature of the data. To read the data, the reader looks in the DirEntry for the K encrypted with their public key, decrypts K, and uses K to decrypt the data.

What do you think @n2vi? @robpike?

**Comment by n2vi** [comment]
Fine by me.  Maybe better to leave out "again" to follow Gabriel good
suggestion here.  Thanks for keeping it gender-neutral.

**Comment by robpike** [comment]
1s/their/that user's/
3/K encrypted/appearance of K that was encrypted/

**Comment by gbbr** [comment]
Thanks guys 🙏 Then it'll be:
>Then, for each potential reader of the file, we encrypt K again using their public key. We store the set of encrypted keys in the DirEntry of the item along with a digital signature of the data. To read the data, the reader looks in the DirEntry for the K encrypted with their public key, decrypts K, and uses K to decrypt the data.

**Comment by gbbr** [comment]
Edited comment. Had an older clipboard content.
