### ISSUE TITLE
doc: Consolidate two Users sections in faq.md

### ISSUE THREAD

**Issue by YaguraStation** [upspin/upspin#546]
_Not sure whether this is worthy of an issue, but I wanted to stick to the Contribution Guide._ 

Currently [faq.md ](https://github.com/upspin/upspin/blob/0072562b019d33f0195318a789f4ed7fe81afbe5/doc/faq.md) has two second-tier headings named Users in line 111 and 466.

**Comment by adg** [comment]
Certainly is worth an issue! I sent a fix. Thanks for the report.
