### ISSUE TITLE
upspinfs: Concurrent map read and map write

### ISSUE THREAD

**Issue by Merovius** [upspin/upspin#550]
**What version of Upspin are you using?**

devel, built from b6cbee6f6dfe62ee7474db0dc25e0ed106cd4969

**What operating system and processor architecture are you using?**

Linux hix 4.13.12-200.fc26.x86_64 #1 SMP Wed Nov 8 16:47:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**

Have upspinfs mounted on `~/up` and did `cp -r $GOPATH/src ~/up/mero@merovius.de/`. After a while, upspinfs crashed due to a datarace. [Stacktraces attached](https://github.com/upspin/upspin/files/1524381/log.txt).

**Comment by Merovius** [comment]
So, first, I intended my report to be humorous, but I think I missed the mark and it read douchy - I edited it, apologies if anyone has already seen it in the meantime :)

Second, I was just trying to debug the failure and I'm not sure, that the version running was actually the commit I mentioned - the line-numbers from the stacktrace don't seem to agree with line numbers in that commit. Unfortunately, I don't think I can reproduce which version was actually running :-/

**Comment by Merovius** [comment]
Okay, on second thought, I believe this is what was fixed in e26daf29bfc1b7cb10507d429c69320d2519fe6c, so closing. Sorry for the noise :)

**Comment by adg** [comment]
@Merovius FWIW I didn't read your original message as inappropriate. Let us know if the problem resurfaces. 😄
