### ISSUE TITLE
cmd/upspinfs: out-of-memory in rpc.decodeStream

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#551]
On my raspberry pi's upspinfs running bcbe577d:

```
runtime: out of memory: cannot allocate 1146093568-byte block (27754496 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x373d1e, 0xd)
        /home/pi/go/src/runtime/panic.go:605 +0x70
runtime.largeAlloc(0x444f4354, 0x12240101, 0x2)
        /home/pi/go/src/runtime/malloc.go:829 +0xe4
runtime.mallocgc.func1()
        /home/pi/go/src/runtime/malloc.go:722 +0x38
runtime.systemstack(0x11cee63c)
        /home/pi/go/src/runtime/asm_arm.s:264 +0x80
runtime.mstart()
        /home/pi/go/src/runtime/proc.go:1135

goroutine 26751 [running]:
runtime.systemstack_switch()
        /home/pi/go/src/runtime/asm_arm.s:209 +0x4 fp=0x1224b6f4 sp=0x1224b6f0 pc=0x64e08
runtime.mallocgc(0x444f4354, 0x31aa78, 0x10001, 0x1)
        /home/pi/go/src/runtime/malloc.go:721 +0x6a8 fp=0x1224b750 sp=0x1224b6f4 pc=0x21dd8
runtime.makeslice(0x31aa78, 0x444f4354, 0x444f4354, 0x4, 0x4, 0x1244cdc0)
        /home/pi/go/src/runtime/slice.go:54 +0x68 fp=0x1224b764 sp=0x1224b750 pc=0x52cf4
upspin.io/rpc.decodeStream(0x503798, 0x1244ce00, 0x502658, 0x11d4c010, 0x1244cdc0)
        /home/pi/src/upspin.io/rpc/client.go:324 +0x640 fp=0x1224b7d4 sp=0x1224b764 pc=0x296120
runtime.goexit()
        /home/pi/go/src/runtime/asm_arm.s:971 +0x4 fp=0x1224b7d4 sp=0x1224b7d4 pc=0x66e68
created by upspin.io/rpc.(*httpClient).Invoke
        /home/pi/src/upspin.io/rpc/client.go:271 +0x580

(...)
```

**Comment by adg** [comment]
What server were you talking to? It looks like that server emitted a bad watch message that caused the client to try to allocate >1gb. [The client](https://github.com/upspin/upspin/blob/master/rpc/client.go#L329) should check that the message length is sane (the `dir/server/serverlog` package assumes a directory entry should be no larger than 64MB, which seems like a reasonable assumption for watch messages also.

**Comment by masiulaniec** [comment]
I've recently put a tls-termination proxy in front of my upspinserver and made my upspinserver listen on localhost serving plain http (-insecure). Maybe the proxy served a "502 Bad Gateway" error and the upspin.io/rpc failed to test for 200? A quick look at the code reveals a potential missing 200 test in httpClient.InvokeUnauthenticated but that's probably an unrelated issue.

**Comment by adg** [comment]
@masiulaniec I think the 502 is probably what triggered it. I'll take a look at the success code checking in that code.
