### ISSUE TITLE
dir/server/serverlog: root backup reference changes across restarts

### ISSUE THREAD

**Issue by adg** [upspin/upspin#555]
Turns out the signature suffix of the root backup reference, even when given the same inputs, is not stable.

It is generated like so, where `base` is the path to the local root file:
```
                sig, err := fac.Sign(hashRoot(base))
                if err != nil {
                        return nil, err
                }
                rootRef = fmt.Sprintf("%s.%s-%s", base, sig.R, sig.S)
```

```
func hashRoot(base string) []byte {
        h := sha256.New()
        h.Write([]byte("@@hashRoot!!")) // Don't sign raw user string.
        h.Write([]byte(base))
        return h.Sum(nil)
}
```

@grosse do you know why?

**Comment by n2vi** [comment]
That is correct.  ecdsa.Sign mixes in some entropy.  https://golang.org/src/crypto/ecdsa/ecdsa.go

I'll read some more context about the underlying problem you're solving and get back to you.
