### ISSUE TITLE
cmd/upspinfs: fscache grows without bound

### ISSUE THREAD

**Issue by adg** [upspin/upspin#558]
In writing a lot of data through upspinfs on a small VM, I noticed that `upspinfs` does not provide any mechanism to restrict the size of its cache.

I am copying many thousands of ~20mb files into upspinfs. The usage pattern is "open file, write contents, close file, repeat".  Watching the behavior of upspinfs and cacheserver, cacheserver so far seems to be obeying its `-cachesize` flag, keeping its storecache to around 1gb (what I specified). By contrast, upspinfs's fscache just keeps growing, even though I know I'm not going to read those files again.

Also, confusingly, upspinfs provides a `-cachesize` flag but this seems to be for the cachserver, if the cacheserver is started by the cacheutil package. The docs don't mention this anywhere. It took me a while to figure it out.

cc @presotto

**Comment by adg** [comment]
At the moment I am preventing my disk from filling up by running this in a loop:

```
find fscache -type f -amin +2 -delete
```

**Comment by presotto** [comment]
This should have ben fixed CL 17940: cmd/upspinfs: fix error in cache size limiting and add a test for it
