### ISSUE TITLE
Snapshot user isn't correctly created

### ISSUE THREAD

**Issue by josselin-c** [upspin/upspin#566]
Back in November I signed up my upspin account 'josselin@costanzi.fr', for this, I used the web interface (don't remember its name).
Today I tried to use the `upspin snapshot` command for the first time but this failed:
```
$ upspin snapshot
upspin: snapshot: client.Lookup:
	Client.DirServer:
	user josselin+snapshot@costanzi.fr: bind.DirServerFor: no directory endpoints found
```

I then found this thread: https://groups.google.com/forum/#!topic/upspin/FAf-KRn45Mk
And indeed my "snapshot" user is missing some configuration:
```
$ upspin user josselin+snapshot@costanzi.fr
name: josselin+snapshot@costanzi.fr
dirs: []
stores: []
publickey: |
  p256
  92229615266873650792479991073686175959024517638047321576722448020506602584145
  46711810420647929628610534602081397089453633523085557411115341961694229014519
```

I think the snapshot user should be correctly created during the sign-up process.

**Comment by josselin-c** [comment]
```
$ upspin -version
Build time: Nov 23 22:33:14 2017 UTC
Git hash:   b6cbee6f6dfe62ee7474db0dc25e0ed106cd4969
```

**Comment by adg** [comment]
@josselin-c the user was actually created, but its record in the key server was not updated with the endpoints you specified. This is issue #540.

To resolve this, run `upspin user`, edit the output to put a +snasphot after the user name, and then run `upspin user -put`, providing the edited output as the input. Let me know if you have any trouble.
