### ISSUE TITLE
Incorrect case for upspinserver-drive "backend" config value

### ISSUE THREAD

**Issue by dougEfresh** [upspin/upspin#569]
Hi, 
   There is a case difference for the backend config value. upspinserver-drive expects **"Drive"** but upspin-setupstorage-drive writes **"drive"**
See:
https://github.com/upspin/drive/compare/master...dougEfresh:master
and 
https://github.com/upspin/drive/blob/master/cloud/storage/drive/drive.go#L28

I saw this in my logs: 
```
Jan 17 17:09:06 bubba upspinserver-drive[4117]: 2018/01/17 17:09:06.422176 store/server.New: invalid operation:
Jan 17 17:09:06 bubba upspinserver-drive[4117]: #011cloud/storage.Dial: unknown storage backend type "drive"
```

**Comment by dougEfresh** [comment]
I created a review: https://upspin-review.googlesource.com/c/drive/+/18220

**Comment by gbbr** [comment]
Nice catch. You are right. Reviewed your CL.
