### ISSUE TITLE
cmd/upspinserver: surprising -http/-https flag behavior

### ISSUE THREAD

**Issue by smcquay** [upspin/upspin#577]
> What version of Upspin are you using?

recent master: d1b10cd

> What operating system and processor architecture are you using?

```bash
$ go env GOOS GOARCH                                                                                                                             
linux
amd64
```

> What did you do?

I host `upspinserver` behind Nginx (I have multiple SNI hostnames on my server).

It worked with the following before e7d8526:

```bash
$ /home/sm/bin/upspinserver -insecure -http :8833
```

> What did you expect to see?

When I launch post e7d8526 upspinserver I get proxying errors:

```bash
upspin@impa:~$ /home/sm/bin/upspinserver -insecure -http :8833 
2018/03/25 04:22:12.459751 Store and Directory servers initialized.
2018/03/25 04:22:12.459787 Store server configuration: backend=Disk basePath=/home/upspin/upspin/server/storage
2018/03/25 04:22:12.459880 https: serving insecure HTTP on ":443"
2018/03/25 04:22:12.459894 https: WARNING: serving insecure HTTP on non-loopback address ":443"
2018/03/25 04:22:12.460013 https: listen tcp :443: bind: permission denied
```

I read the help for `-https`:

```
  -https address
        address for incoming secure network connections (default ":443")
```

and figured I should launch it on some bogus, non-proxied port:

```bash
$ /home/sm/bin/upspinserver -insecure -http :8833 -https :8843
```

but then I get the following error:

```
2018/03/25 04:23:22.242822 serverutil/perm.NewFromDir: watch event error: dir/server.Watch: I/O error:
        store/remote("us.clstr.co:443").Get:
        rpc.Invoke: 502 Bad Gateway: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

> What did you see instead?

When I change the way I launch it to the counter-intuitive (matching ports):

```bash
$ /home/sm/bin/upspinserver -insecure -http :8833 -https :8833
```

The system behaves correctly.

There is a good chance that my interpretation of the help message is wrong, but perhaps the help message should be updated? Should `-insecure` negate the need for `-https`?

I'm happy to help with either approach, just not sure which is desired.

**Comment by idrarig** [comment]
I've run into the same, and what is even more surprising is that you can drop the `-http` flag also. Very confusing since we're run in plain http. Looking forward to the answer :).

**Comment by n2vi** [comment]
I'll let Andrew give the official answer.

Personally, I wish we didn't have -insecure.  If you need proof of why http behind a reverse proxy is bad, google "ssl added and removed here".

Eric  ˙ ͜ʟ˙

**Comment by adg** [comment]
I just sent [a fix](https://upspin-review.googlesource.com/18800). Looks like I broke it with 40ea17e58.

**Comment by smcquay** [comment]
Works for me, thanks!

**Comment by adg** [comment]
Great, thanks for letting us know.
