### ISSUE TITLE
cmd/upspinfs: symlink size seems to be handled incorrectly

### ISSUE THREAD

**Issue by filmil** [upspin/upspin#603]
There are at least a few places where symlink sizes are handled incorrectly in upspinfs, it would seem.

- Spec says that a link `DirEntry` has zero `DirBlocks`: https://upspin.googlesource.com/upspin/+/master/upspin/upspin.go#612
- `DirEntry.Size()` bases its report on the `DirBlocks` content, which per spec is an empty slice: https://github.com/upspin/upspin/blob/master/upspin/code.go#L268 So I would expect that `DirEntry.Size() == 0` for a symlink
- `man 2 {,l,f}stat` says for `st_size`: "The size of a symbolic link is the length of the pathname it contains, without a terminating null byte."  Seems reasonable to expect that `upspinfs` maintains this promise as well.
- However, in a few places, `upspinfs` reports the size of the symlink as `DirEntry.Size()`, which is defined as zero by upspin spec.  Given the previous point, this seems incorrect for `upspinfs` since `DirEntry.Size()` is not subject to `st_size` spec, but a FUSE filesystem probably is.
   - One of such places: https://github.com/upspin/upspin/blob/master/cmd/upspinfs/watch.go#L206
   - Another: https://github.com/upspin/upspin/blob/master/cmd/upspinfs/watch.go#L396
   - Another: https://github.com/upspin/upspin/blob/master/cmd/upspinfs/fs.go#L619

**Comment by adg** [comment]
Agree upspinfs should honor the posix behavior here.

**Comment by filmil** [comment]
This is a duplicate of issue #619, it seems.
