### ISSUE TITLE
doc: broken image links in arch.md and index.md

### ISSUE THREAD

**Issue by smasher164** [upspin/upspin#607]
The img tags in these files refer to an images directory in the root of the repo, which doesn't exist. The path should instead be /doc/images.

**Comment by n2vi** [comment]
On github, "images" is under "doc".  But on the web server "https://upspin.io/" the directory "images" is at top level, so auth.md works correctly as is.

Assigning to Andrew to give a more complete explanation.

**Comment by adg** [comment]
Correct; the files are supposed to be viewed from upspin.io, not in the repo itself.
