### ISSUE TITLE
Add the option -allow_other to upspinfs

### ISSUE THREAD

**Issue by filmil** [upspin/upspin#615]
This allows the user to specify the flag -allow_other when mounting
an upspinfs endpoint so that the upspin filesystem becomes visible
to other users of the same system.

**Comment by filmil** [comment]
Proposed a fix at https://upspin-review.googlesource.com/c/upspin/+/19260

**Comment by filmil** [comment]
Ping?

**Comment by adg** [comment]
I left some comments on your change.
