### ISSUE TITLE
deleting $HOME/upspin and re-running upspin-ui

### ISSUE THREAD

**Issue by johnpryan** [upspin/upspin#616]
As a new Upspin user, I was able to get `upspinserver` running on GCP using `upspin-ui`. I accidentally removed the `$HOME/upspin` directory containing the config file. It's not clear to me how to re-configure things so that upspin-ui has access to my server on GCP. This is not necessarily a usability issue, but I'm trying to understand how to debug this situation. Thanks!

**Comment by n2vi** [comment]
I'm no expert on upspin-ui;  I set my server up manually.  But maybe the following is worth a try until the real experts in the Oz timezone are awake.  I'm assuming only the upspin/ directory was wiped out, not .ssh/.

```
cd
mkdir upspin
cat > upspin/config <<!EOF
username: john.p.ryan4@gmail.com
dirserver: remote,c99b0617dcdfd17b2963afcb6f28fdbe.upspin.services:443
storeserver: remote,c99b0617dcdfd17b2963afcb6f28fdbe.upspin.services:443
!EOF
```

**Comment by adg** [comment]
@n2vi is correct; you just need to restore your `$HOME/upspin/config` file. There were other files in there, used to configure your upspinserver instance, but they're no longer necessary for you to use Upspin.

If you've lost your keys in `$HOME/.ssh/john.p.ryan4@gmail.com` directory then you'll need to start again from scratch with a different email address.

**Comment by johnpryan** [comment]
@n2vi that worked like a charm, thanks! I didn't realize the config file required the `remote,` prefix and the `443` port. Thankfully I still had the SSH keys.
