### ISSUE TITLE
Broken link in the docs: the upspin's download page link in signup.md

### ISSUE THREAD

**Issue by BlueSolei** [upspin/upspin#617]
In file signup.md the link to download the upspin tools is broken.
If you follow it you will get a 404 response.
The broken link is [https://github.com/upspin/upspin/blob/master/dl](https://github.com/upspin/upspin/blob/master/dl)
It should be: [https://upspin.io/dl](https://upspin.io/dl)

**Comment by adg** [comment]
Thanks for the report and PR, but there's been a confusion here.

That doc is meant to be viewed from https://upspin.io/signup.md

We didn't intend for it to be viewed through the GitHub UI.
