### ISSUE TITLE
cloud/storage/dropbox: adding go.mod

### ISSUE THREAD

**Issue by palmamartin** [upspin/upspin#627]
Since upspin is switching to go modules a `go.mod` file should be added to the dropbox storage backend. If ok I will send a CL later this week for this.

**Comment by n2vi** [comment]
Sounds like a good plan to me. I'll work on upspin/exp in parallel.

**Comment by palmamartin** [comment]
Find the CL here: https://upspin-review.googlesource.com/c/dropbox/+/19500 
Could someone review it? @n2vi  @adg

**Comment by adg** [comment]
Wow, apologies for missing this for so long.

**Comment by palmamartin** [comment]
CL was merged, thx.
