### ISSUE TITLE
Account creation on ACMEv1 is disabled

### ISSUE THREAD

**Issue by lgouger** [upspin/upspin#632]
While setting up an AWS upspinserver, I get the following error when trying to test connectivity.
```
403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

This comes after starting an `upspinserver` on an AWS Lightsail box runing Ubuntu 16.04LTS.

The upspinserver's log...
```
-- Logs begin at Wed 2020-01-01 21:22:53 UTC. --
Jan 01 21:34:02 ip-172-26-10-255 systemd[1]: Started Upspin server.
Jan 01 21:34:03 ip-172-26-10-255 upspinserver[1779]: 2020/01/01 21:34:02.999912 unable to read configuration: open /home/upspin/upspin/server/serverconfig.json: no such file or directory
Jan 01 21:34:03 ip-172-26-10-255 upspinserver[1779]: 2020/01/01 21:34:03.002755 Configuration file not found. Running in setup mode.
Jan 01 21:34:03 ip-172-26-10-255 upspinserver[1779]: 2020/01/01 21:34:03.002969 https: serving HTTPS on ":443" using Let's Encrypt certificates
Jan 01 21:34:03 ip-172-26-10-255 upspinserver[1779]: 2020/01/01 21:34:03.003154 https: caching Let's Encrypt certificates in /home/upspin/upspin/letsencrypt
Jan 01 21:36:44 ip-172-26-10-255 upspinserver[1779]: 2020/01/01 21:36:44.654798 http: TLS handshake error from ###.###.###.###:61224: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```
` ###.###.###.###` appears in place of my local, home, public ip.

**Comment by filmil** [comment]
Tried to set up a server based on GCP and seeing the same issue.

**Comment by rmhrisk** [comment]
The ACME implementation on Let’s Encrypt only supports the v2 or RFC compliant version of ACME. Someone will have to do an update to upspin to get it working again.

**Comment by filmil** [comment]
Thinking aloud, as I have not tried this yet: is it possible to run upspin behind an up-to-date https proxy and remove the need for upspinserver to manage https certs?

**Comment by n2vi** [comment]
We'll definitely fix upspin sources to run acme v2 more comprehensively.
Just a question of coordinating folks here coming back from holidays.

**Comment by rmhrisk** [comment]
> Thinking aloud, as I have not tried this yet: is it possible to run upspin behind an up-to-date https proxy and remove the need for upspinserver to manage https certs?

You should be able to do that or use a client like acme.sh but it’s better for v1 to be replaced in source.

**Comment by n2vi** [comment]
Also, to perhaps save me a couple rounds of creating new GCP servers...
Were you using pre-built binaries from somewhere or rebuilding from source
yourself?

**Comment by filmil** [comment]
> > Thinking aloud, as I have not tried this yet: is it possible to run upspin behind an up-to-date https proxy and remove the need for upspinserver to manage https certs?
> You should be able to do that or use a client like acme.sh but it’s better for v1 to be replaced in source.

Understood, and not to diminish the need to update the library; I wanted also to have upspin not monopolize the port 443. :)

**Comment by filmil** [comment]
> Also, to perhaps save me a couple rounds of creating new GCP servers... Were you using pre-built binaries from somewhere or rebuilding from source yourself?

I used `upspinserver-gdrive` following instructions here: https://upspin.io/doc/server_setup_drive.md.  Which looks to be a minimal addition to the "regular" upspin.

**Comment by n2vi** [comment]
I just now setup upspinserver-drive for my first time.  Let'sEncrypt worked
fine, so we must be using acme v2, which corresponds to my understanding of
our source.

So I'm still mystified about the problems y'all are having; not doubting
you have them, just confused about why. If you rebuild from scratch it
might work, but I realize that's not an entirely satisfactory answer.

**Comment by rmhrisk** [comment]
@n2vi (We miss you btw).

We’re you re-using an existing ACME account at Lets Encrypt? 

I’ve never installed upspin but I do know the boulder (LEs server) fairly well and that error should only happen when it gets a new account registration via ACMEv1.

**Comment by n2vi** [comment]
(I miss my friends there as well.)

Nope, as best I could manage this was a completely fresh install with
nothing copied over. And I couldn't find anyplace in our code where we were
specifying ACMEv1, just calling the Go standard library which defaults to
v2.

**Comment by rmhrisk** [comment]
Hrm.... not sure then.

**Comment by filmil** [comment]
Hm, so in my case the issue was that I compiled with an ancient version of
upspin.  I was probably missing the `-u` parameter when doing the `go get`,
and I already had deps downloaded. :/

Specifically, it seems that one probably needs this commit:

commit 46bda5db8a706c82ddddbff593cad95b483a9375
Author: Andrew Gerrand <adg@golang.org>
Date:   Wed Nov 20 07:37:30 2019 +1100

    vendor: update golang.org/x/crypto

    The ACMEv1 endpoints have been EoL'd, so update the acme libraries
    so that new Upspin users can set up their servers.

    https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

    The update was performed with this command:
      $ dep ensure -update golang.org/x/crypto

    Change-Id: Ib82598113f345cc4234003beafaadfce50e3c3e6
    Reviewed-on: https://upspin-review.googlesource.com/c/upspin/+/19380
    Reviewed-by: Eric Grosse <grosse@gmail.com>

**Comment by lgouger** [comment]
Confirmed, after updating (go get -u) I now have the latest crypto code and the upspinserver is starting and getting a certificate without any problem.

thanks.
