### ISSUE TITLE
https://key.upspin.io/ down?

### ISSUE THREAD

**Issue by ajdevries** [upspin/upspin#639]
Looks like the key server is down?

```
curl https://key.upspin.io/
curl: (7) Failed to connect to key.upspin.io port 443: Connection refused
```

**Comment by aakarim** [comment]
upspin.io too

**Comment by reiman2222** [comment]
go get is also failing to get this package with error:
```
go get upspin.io: unrecognized import path "upspin.io" (https fetch: Get https://upspin.io?go-get=1: dial tcp 104.197.199.242:443: connect: connection refused)
```

**Comment by mennis** [comment]
Maybe the service itself is down or the DNS mapping is wrong now?

% dig key.upspin.io

; <<>> DiG 9.10.6 <<>> key.upspin.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14677
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;key.upspin.io. IN A

;; ANSWER SECTION:
key.upspin.io. 847 IN A 104.154.19.111

;; Query time: 265 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Mon Feb 22 09:24:32 PST 2021
;; MSG SIZE  rcvd: 58

% ping -c 1 104.154.19.111
PING 104.154.19.111 (104.154.19.111): 56 data bytes
64 bytes from 104.154.19.111: icmp_seq=0 ttl=98 time=77.457 ms

--- 104.154.19.111 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 77.457/77.457/77.457/0.000 ms

**Comment by ajdevries** [comment]
I think that the service self is down, getting a http response means that dns and server is running. I guess that it is running on a Google Cloud machine, maybe are there some issues?

**Comment by adg** [comment]
The upspin.io services are back. Apologies for the outage.

There was a Kubernetes issue - I had neglected to upgrade the node pools, which I thought was configured to happen automatically. I'll look into this more and see how it can be prevented in future.
