### ISSUE TITLE
non-trivial typo in overview doc (I think?)

### ISSUE THREAD

**Issue by kanreki** [upspin/upspin#644]
In [the overview doc](https://upspin.io/doc/overview.md) it says "Directory servers never even see user’s data, even unencrypted data...".

Don't you really mean "even encrypted data"?

**Comment by adg** [comment]
No, the implication being that no user content is stored on, nor passes through, the directory server at all (except for metadata).

**Comment by kanreki** [comment]
Sorry, I should have explained my reasoning...

Think about what the word "even" implies. It's clear from earlier parts of the doc that unencrypted (clear-text) data is not stored on (any) servers (at least by default, I guess?). But here we're saying, on the directory server, not only is clear-text data not stored, but even encrypted data is not stored there.

**Comment by adg** [comment]
Ah I see what you mean. Yeah this wording could probably be improved.

**Comment by kanreki** [comment]
I think you could simply change "even unencrypted" to "even encrypted".
