### ISSUE TITLE
Why custom types instead of primitives?

### ISSUE THREAD

**Issue by blank-teer** [upspin/upspin#646]
Sorry if this isn't an issue actually, but rather my curiosity. 
So the question is why some of the custom types located at [/upspin/upspin.go](https://github.com/upspin/upspin/blob/master/upspin/upspin.go) are declared as custom without having any methods or even composition (being just strings or ints, like [UserName](https://github.com/upspin/upspin/blob/master/upspin/upspin.go#L18))? Wouldn't it be more idiomatic to operate primitives as long as we don't need extra behavior like, for example, [Endpoint](https://github.com/upspin/upspin/blob/master/upspin/upspin.go#L58) type [has](https://github.com/upspin/upspin/blob/master/upspin/endpoint.go#L53)?

**Comment by robpike** [comment]
@bundgaard is correct, it's for the errors package and it works great.
