### ISSUE TITLE
keygen needs investigation

### ISSUE THREAD

**Issue by n2vi** [upspin/upspin#647]
I recently noticed that "upspin keygen -secretseed" is not producing the same keys as before. Specifically, I observe that an upspin built in November 2018 produces different results than an upspin built today, and I confirm that cmd/upspin/keygen_test.go fails in a related way.

One potential cause could be the November 2022 change of Go crypto, which intentionally gets rid of deterministic elliptic key generation. See [golang issue #58637](https://github.com/golang/go/issues/58637) where I've started a discussion of this larger point.

But I suspect keygen started to fail earlier, mostly likely because of a change in the standard library rather than upspin source itself. I will track progress here in case anyone else stumbles across the problem or is in a position to help.

Until I fix this potentially catastrophic bug, it would be wise to backup your *.upspinkey files somewhere safe and not only depend on secretseed.

**Comment by n2vi** [comment]
I've created a fix and will be sending it out for review.

In the meantime, if you're one of the few people who have created new keys with an Upspin compiled by Go 1.20.*, please save your current *.upspinkey files in a safe place and, ideally, plan to fetch the fixed version and rotate keys.

**Comment by adg** [comment]
> I see from key.upspin.io/log that a number of people have generated
> keys since November 2022 when Go 1.20 came along. If reviewers
> agree, once the dust settles from this CL I'll email those recent
> addresses to warn that their secretseeds may have been caught by
> this bug and they need to save their *.upspinkey files or update
> their copy of upspin and rotate to new keys.

This seems like a good idea to me.

**Comment by n2vi** [comment]
Done.

There were 16 people potentially affected. If they chose the upspin.io/doc/faq.md#rotate-keys option I encouraged them to send me any questions because I know the process could be intimidating.
