### ISSUE TITLE
client/file: *File.Read incorrect offset when short read

### ISSUE THREAD

**Issue by rschio** [upspin/upspin#650]
I think the PR #649 fixed the `ReadAt` method but broke the `Read`.
Both `*File.Read` and `*File.ReadAt` use the helper method `*File.readAt`.

After the PR `*File.readAt` is returning n > 0 and io.EOF, but the Read method only increments the offset when `err == nil`:
```go
// Read implements upspin.File.
func (f *File) Read(b []byte) (n int, err error) {
	const op errors.Op = "file.Read"
	n, err = f.readAt(op, b, f.offset)
	if err == nil {
		f.offset += int64(n)
	}
	return n, err
}
```

I'm testing a package using the `fstest.TestFS` func which calls `iotest.TestReader` I think this test could help to reproduce the problem.

I also noticed the client test `TestFileZeroFill` is failing, probably because io.EOF is returned in a short read. The io.Reader interface says returning err == nil or err == io.EOF is valid in this case. My suggestion is to use the #649 fix direct inside the `*File.ReadAt` method to preserve the old `*File.Read` old behavior.

**Comment by n2vi** [comment]
Thanks, will get on this quickly.

I did run some tests but unrelated issues were preventing me from running sufficiently comprehensive tests. I'll find some other machines to get around those issues.

**Comment by rschio** [comment]
Thanks for the super fast response. Yeah, I didn't rull all the tests too, the TestFileSeek was timing out in my machine.

**Comment by n2vi** [comment]
PR #651 should fix that immediate issue while I diagnose the TestFileSeek problem and digest the rest of your feedback.

**Comment by rschio** [comment]
Now is never returning EOF, it needs to return EOF when n == 0.

**Comment by n2vi** [comment]
I've attempted to revert both changes while I come up with a better plan.
