### ISSUE TITLE
Handling distributed storage

### ISSUE THREAD

**Issue by hhvn-uk** [upspin/upspin#658]
The documentation makes sense from a cloud storage perspective: the key server tells you where the dir server is, which then tells you where the store server is and what to ask it for. This all makes sense if you have a single store server that is always on and always accessible.

What I would like to understand more is if you can, and if so, how it works, spread the storage across multiple places.

Can a dir server tell the client to use different store servers for different data. If so how would the dir server know what files are stored by what store server?

Could I have a store server on say, a desktop at home which acts like a NAS, as well as have a store server on my laptop for git repositories and such, so that I could access them via upspin, but still keep git repos local to my laptop, so I can access them without internet? If that laptop is then disconnected from the network, how does upspin handle that?

That laptop of course may be on different networks at different times. From what I can tell for upspin to work properly, a store server needs a (sub)domain assigned to it to function, as such I think what I am describing is probably not possible within upspin using the existing architecture and servers.

I would think that in order to implement distributed storage, the only real option would be to create a new server with the same interface as a store server, that would contact and retrieve the stored data from various machines and then present it to any upspin clients. Is this correct?

I haven't actually tried upspin yet, I have only looked at the upspin.io website gopherfest 2017 talk, so this issue probably looks like a complete mess and misinterpretation of what upspin is. Perhaps that shows the documentation needs a bit more.

**Comment by n2vi** [comment]
As usually deployed today, each upspin user has a single dirserver and a single storeserver. There are provisions in the protocol (for example, see the comments in upspin.go at StoreServer.Get()) for distributing across more, but I'm not aware of this scalability feature being used much yet.
