### ISSUE TITLE
docs on upspin.io out of date; fixed at head; docs need to be pushed

### ISSUE THREAD

**Issue by mhansen** [upspin/upspin#659]
Hi, https://upspin.io/doc/overview.md says

> The source for Upspin is hosted on Gerrit (upspin.googlesource.com)

But that link is to two empty repositories

This was fixed in https://github.com/upspin/upspin/commit/f38fa2954c6be9be919a1dcaf0d109a86d6c8938

But it looks like it hasn't been pushed to the website yet.

**Comment by n2vi** [comment]
I recompiled and restarted frontend, which seems to have fixed things, but please reopen if you spot something else wrong.

And thanks for pointing out that we missed this!
