### ISSUE TITLE
doc/access_control.md: glob patterns aren't quoted, giving italics

### ISSUE THREAD

**Issue by alurm** [upspin/upspin#663]
## The issue

The glob stars (asterisks) are interpreted as markdown syntax for italicised text, which is not what was indended.

Precise markdown rules are unclear to me, but this currently happens only once in the doc file.

Section discussed: «Appendix: Summary of access rules»

Problematic sentence:

`For instance, given u@google.com/a/*/b the caller needs List access
for directory 'a' because Glob will search to match the '*'.`

Without backticks (for ones viewing with markdown rendered):

For instance, given u@google.com/a/*/b the caller needs List access
for directory 'a' because Glob will search to match the '*'.

## Images

Website markdown render:

![IMG_20240331_135951](https://github.com/upspin/upspin/assets/108410815/3cf55ded-7afd-42bc-b3fe-a8381a75665e)

Github markdown render:

![IMG_20240331_140931](https://github.com/upspin/upspin/assets/108410815/097ac8b5-3108-4830-bac7-bb5f5a3148e4)

## Suggested solution

Either use backticks or backslashes. Examples:

1) For instance, given `u@google.com/a/*/b` the caller needs List access
for directory 'a' because Glob will search to match the `*`.

2) For instance, given u@google.com/a/\*/b the caller needs List access
for directory 'a' because Glob will search to match the '\*'.

**Comment by alurm** [comment]
Relevant place: https://github.com/upspin/upspin/blob/master/doc/access_control.md?plain=1#L410

**Comment by alurm** [comment]
Thanks. Upspin.io probably needs to be rebuilt for the change to take effect.

**Comment by n2vi** [comment]
Yes. Unfortunately, the manual change is easy. The "automated" part depends on a rarely used system with a huge pile of dependencies. I'll get it going, but there will be a delay. I do appreciate your correction, however!

**Comment by alurm** [comment]
Understood, thanks :)

**Comment by n2vi** [comment]
Ok, system rebuilt. The doc should look ok now.
