### ISSUE TITLE
cmd/upspinfs: panic when coping files

### ISSUE THREAD

**Issue by rschio** [upspin/upspin#670]
OS: MacOS Sequoia

What happened:
I recreate my upspin server with a different storage once again and was coping my backups to the new server.
Something like
```
$ cp -r ./Books ~/u/user@example.com
```
It copied some files and than returned an error (I don't remember the error) that I thought my backup were corrupted but that was not the case.

After looking the upspinfs logs it was a nil pointer dereference.

The logs:
[issue.log](https://github.com/user-attachments/files/18220137/issue.log)

The culprit seems to be this part of code. In some cases the *DirEntry in line 592 is nil:
https://github.com/upspin/upspin/blob/209f0c9c37d75884d380fb31543b770a8d2e0200/cmd/upspinfs/cache.go#L562-L592

**Comment by presotto** [comment]
Think it might have been an xattr file?  My code there is wrong (see
comment line 574).  I should fake up a de.

**Comment by rschio** [comment]
Yes, I think was a xattr file.

**Comment by presotto** [comment]
This is a secondary problem though, i.e. me handling an error badly.
Looks like it was getting unreachable errors trying to write the file.

**Comment by rschio** [comment]
Yeah, the server was freshly created and a copied a lot of stuff... the server was slow, maybe this is the reason why was returning unreachable.

**Comment by presotto** [comment]
better check with no caching on to make sure everything made it and you
aren't just looking at the cache.  I'll consider taking out that special
case for xattr files.  Don't think its still pertinent.

**Comment by rschio** [comment]
OK, thank you.

**Comment by presotto** [comment]
Replace the break on line 583 with:

    // quit trying to write it back.
   cf.dirty = false
   return nil

and you shouldn't have any more problems, at least from this.  Tell me if
it works out.

**Comment by rschio** [comment]
It worked!

I couldn't reproduce the problem naturally, but I was able to force a reproduction.

When the code reaches this part my modified upspinfs sleeps for 5 seconds and ask you to disable the internet. Without internet it reaches the buggy path when the created file is a ._file

e.g: 
`$ cp hello.txt mnt/user@example.com/Debug/._hello.txt`

```go

	log.Info.Printf("************** disable your internet *****************")
	time.Sleep(5 * time.Second)

	// Use the client library to write it back.  Try multiple times on error.
	var de *upspin.DirEntry
	for tries := 0; ; tries++ {
		log.Info.Printf("************** inside tries *****************")
		de, err = cf.c.client.PutSequenced(n.uname, n.seq, cleartext)
		if err == nil {
			n.seq = de.Sequence
			cf.attachDirEntry(n.f.config, de, true)
			n.attr.Mtime = de.Time.Go()
			break
		}
		if tries > 5 || !strings.Contains(err.Error(), "unreachable") {
			log.Info.Printf("************** tries >5 || !strings.Contains(err.Error(), unreachable) *****************")
			if isXattrFile(n.uname) {
				log.Info.Printf("************** inside buggy path *****************")
				// A hack so every server doesn't have to handle
				// xattr files. We pretend the Put worked and
				// increase the ref count for the cached version
				// so that the xattr at least lasts as long as
				// upspinfs stays up. Not perfect but keeps
				// macOS finder happy.
				// TODO(p): this might be improved by constraining
				// to fewer error types.
				cf.file.Pin()
				//	break
				//
				// quit trying to write it back.
				cf.dirty = false
				return nil
			}
			return errors.E(op, err)
		}
		time.Sleep(100 * time.Millisecond)
	}

	// Rename it to reflect the actual reference in the store so that new
	// opens will find the cached version.
	cdir, fname := cf.c.cacheName(de)

```

reproducing the problem without your fix:
[modified_old.log](https://github.com/user-attachments/files/18220936/modified_old.log)

reproducing the problem with your fix:
[modified_new.log](https://github.com/user-attachments/files/18220939/modified_new.log)

**Comment by presotto** [comment]
Cool.  I'll submit a fix.  Thanks.

**Comment by presotto** [comment]
Assuming I remember how...

**Comment by rschio** [comment]
Thank you!

**Comment by presotto** [comment]
As usual, my first attept at pushing it back was from a now dead branch, so
I have yet another change to that branch.   Now pushed it to master I
believe correctly.  I can't not use git for years and expect to do anythign
right.

**Comment by rschio** [comment]
Should this be tagged?

**Comment by presotto** [comment]
Yes, if I could remember how.  Help!

**Comment by rschio** [comment]
https://stackoverflow.com/questions/5195859/how-do-you-push-a-tag-to-a-remote-repository-using-git

Or you could tag using GitHub -> releases -> choose a tag.

**Comment by presotto** [comment]
Given that to date there has been only one release tag created, I think
I'll leave it be.

I will close the issue, now that I finally found a 2 factor device that
still works with github.

**Comment by presotto** [comment]
The original code was just wrong.  No feature change here, just a fix.

**Comment by rschio** [comment]
OK, thank you!
